### ISSUE TITLE
Synced screens

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#100]
Should the screens be synced? How would it even work? Should it be an option? There are lots of problems with syncing them up.

Alternatively, certain content can be synced such as music currently playing or a video on the screen, maybe notifying the player that there is a video playing on the video tab or something. I think this is probably the best way to go about it. Might be able to sync the current open tab and if the menu is open or not but that's about it.

**Comment by SingularMix** [comment]
Sounds good the only thing, is I like to have one screen show the left side of the exterior and the other screen showing the right and then i leave the door open so i can see everything but the back but if screens are synced this wont be possible; so maybe have a enable sync or disable synce option?

**Comment by MattJeanes** [comment]
Synced with other players, not the other screens

**Comment by Noname12345GER** [comment]
You mean that the contents of the screens look for ewery player the same ?
I think it should be an option bound to the Isomorph so the TARDIS Owner is the only one able to see it then.

**Comment by Noname12345GER** [comment]
Else, give ewery screen an ID! This way, the first 20 Screens are the basic ones for Scanner and stuff and if extension Devs would create new Menu points, they have to give them unique! IDs above 20. this way, syncing wouldn't be the biggest Problem i believe. For Videos, they would desync and play the content independently, until interrupted by someone.

**Comment by parar020100** [comment]
I think that with GUI themes and all things you can set up, synced screens are kinda a waste of time.

**Comment by MattJeanes** [comment]
Agree, closing
