### ISSUE TITLE
Multiplayer Manual Destination mode problem

### ISSUE THREAD

**Issue by NovaAstral** [MattJeanes/TARDIS#1004]
In multiplayer, whenever anyone accesses the Manual Destination mode, everyones screen fades to white instead of just the person who accessed it.

**Comment by AmyJeanes** [comment]
I'm unable to replicate this issue, all code is pointing to the single player for the screen fade who pressed the control.

If you can give me some reliable steps to reproduce this issue in a multiplayer setting let me know and I'll take another look
