### ISSUE TITLE
Allow screen interface to be opened in third person mode

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#101]
This is mostly for when the interior cannot spawn. I'll need to run checks to see if the interior exists when the menus are opened and hide some controls such as the door controller. Thinking middle click for this control (by default).

**Comment by Piehthyte** [comment]
Question, I am not sure if anyone else has their controls set like mine; My middle click is the suit zoom. Would that still be applicable for a control? It would probably zoom in every time I were to click the button. If I may, I suggest something like E+RMB instead. Your choice :p Just shooting out ideas!

**Comment by Piehthyte** [comment]
E+RMB or R+RMB or something I have no idea :p

**Comment by MattJeanes** [comment]
Hence (by default), controls are rebindable.

**Comment by Piehthyte** [comment]
Sorry did not see that small part of it! Not a bad idea then!

**Comment by MattJeanes** [comment]
Done for next update
