### ISSUE TITLE
Music not working

### ISSUE THREAD

**Issue by evabay1** [MattJeanes/TARDIS#1018]
whenever i try to play preloaded music it says it cant find the track

**Comment by parar020100** [comment]
Hi
Does music from other sources work? (e.g. from youtube) 
Which branch of gmod are you using?

**Comment by evabay1** [comment]
yes music feom youtube works perfectly fine, im on the default branch of
gmod but ive also tried the chromium branch

**Comment by evabay1** [comment]
though i no longer experience this issue since i got an SSD since

**Comment by parar020100** [comment]
I'm happy to hear that!

@MattJeanes could it just be a performance issue?
Can this one be closed?

**Comment by AmyJeanes** [comment]
The BASS module in GMod seems to be pretty unreliable I've found, it struggles playing even a direct MP3 stream from the web sometimes or cuts out halfway through, I've not found any kind of patterns yet
