### ISSUE TITLE
Half exterior broken and controls broken

### ISSUE THREAD

**Issue by captain3O** [MattJeanes/TARDIS#1044]
every TARDIS in gmod broken am I the only one here? The door doesn't show and when I enter in it noclips me into an interior and it is dark but has sounds and controls do not work. Can someone help me out? only half of the exterior shows.
here is the code 

Initializing Awesomium..
Parent cvar in server.dll not allowed (p2p_enabled)
No Kinect SDK
DEBUG: Clearing CSoundPatches after soundsound... (x2)
Addons have changes - remounting
DEBUG: Clearing CSoundPatches after soundsound... (x6)
PREP OK

[TARDIS] lua/tardis/libraries/libraries/libraries/sh_version.lua:21: Invalid version in tardis/version_sv.txt: 
  1. error - [C]:-1
   2. get_previous_version - lua/tardis/libraries/libraries/libraries/sh_version.lua:21
    3. unknown - lua/tardis/libraries/libraries/libraries/sh_version.lua:45
     4. include - [C]:-1
      5. LoadFolder - lua/autorun/tardis.lua:27
       6. unknown - lua/autorun/tardis.lua:39

[TARDIS] lua/tardis/settings/sh_global_settings.lua:48: attempt to call method 'AddMigration' (a nil value)
  1. unknown - lua/tardis/settings/sh_global_settings.lua:48
   2. include - [C]:-1
    3. LoadFolder - lua/autorun/tardis.lua:27
     4. unknown - lua/tardis/libraries/libraries/sh_settings.lua:439
      5. include - [C]:-1
       6. LoadFolder - lua/autorun/tardis.lua:27
        7. unknown - lua/autorun/tardis.lua:40

[TARDIS] lua/tardis/libraries/libraries/libraries/sh_von.lua:180: vON: Malformed data... Can't find a proper type definition. Char#1:
  1. error - [C]:-1
   2. d_findVariable - lua/tardis/libraries/libraries/libraries/sh_von.lua:180
    3. deserialize - lua/tardis/libraries/libraries/libraries/sh_von.lua:284
     4. LoadSettingsFromFile - lua/tardis/libraries/libraries/sh_settings.lua:241
      5. LoadSettings - lua/tardis/libraries/libraries/sh_settings.lua:248
       6. unknown - lua/tardis/libraries/libraries/sh_settings.lua:440
        7. include - [C]:-1
         8. LoadFolder - lua/autorun/tardis.lua:27
          9. unknown - lua/autorun/tardis.lua:40

[TARDIS] lua/autorun/tardis.lua:44: attempt to call method 'RunMigrations' (a nil value)
  1. unknown - lua/autorun/tardis.lua:44

Using map cycle file cfg/mapcycle.txt.
DEBUG: Clearing CSoundPatches after soundsound... (x2)
Garry's Mod

sandbox
gm_flatgrass
1
76561198384896843
Warning: WorldTwoTextureBlend found on a non-displacement surface (material: gm_construct/flatgrass). This wastes perf for no benefit.
InitFastCopy: only 26% fast props. Bug?
Clientside Lua startup!
Compact freed 839680 bytes
JOY_AXIS_X:  mapped to Turn (absolute)
JOY_AXIS_Y:  mapped to Look (absolute)
JOY_AXIS_Z:  unmapped
JOY_AXIS_R:  mapped to Forward (absolute)
JOY_AXIS_U:  mapped to Side (absolute)
JOY_AXIS_V:  unmapped
Advanced Joystick settings initialized
Redownloading all lightmaps

[TARDIS] lua/entities/gmod_tardis/modules/sh_version.lua:6: attempt to call method 'IsNewVersion' (a nil value)
  1. v - lua/entities/gmod_tardis/modules/sh_version.lua:6
   2. CallHook - lua/entities/gmod_tardis/shared.lua:70
    3. Initialize - lua/entities/gmod_door_exterior/init.lua:76
     4. unknown - lua/entities/gmod_tardis/init.lua:41
      5. Spawn - [C]:-1
       6. SpawnFunction - lua/entities/gmod_door_exterior/init.lua:22
        7. SpawnTARDIS - lua/tardis/metadata/sh_spawn_tardis.lua:60
         8. unknown - lua/tardis/metadata/sh_spawn_tardis.lua:110
          9. unknown - lua/includes/modules/concommand.lua:54

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:133
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. unknown - lua/entities/gmod_door_exterior/init.lua:92 (x3)

[TARDIS] Please wait, finding suitable spawn location for interior..
[TARDIS] Done!

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:133
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. unknown - lua/entities/gmod_door_exterior/init.lua:92 (x22)

Wrote 'screenshots/gm_flatgrass0048.jpg':  2.76 MB (1280x720) compresssed (quality 90) to 181.65 KB

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:133
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. unknown - lua/entities/gmod_door_exterior/init.lua:92 (x33)

Wrote 'screenshots/gm_flatgrass0049.jpg':  2.76 MB (1280x720) compresssed (quality 90) to 96.37 KB

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:133
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. unknown - lua/entities/gmod_door_exterior/init.lua:92 (x26)

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:120
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. CallCommonHook - lua/entities/gmod_tardis/shared.lua:49
       6. TogglePower - lua/entities/gmod_tardis/modules/sh_power.lua:39
        7. ext_func - lua/tardis/controls/sh_control_power.lua:4
         8. Control - lua/tardis/sh_control.lua:49
          9. unknown - lua/tardis/sh_parts.lua:298

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:133
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. unknown - lua/entities/gmod_door_exterior/init.lua:92

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:120
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. CallCommonHook - lua/entities/gmod_tardis/shared.lua:49
       6. TogglePower - lua/entities/gmod_tardis/modules/sh_power.lua:39
        7. ext_func - lua/tardis/controls/sh_control_power.lua:4
         8. Control - lua/tardis/sh_control.lua:49
          9. unknown - lua/tardis/sh_parts.lua:298

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:133
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. unknown - lua/entities/gmod_door_exterior/init.lua:92 (x6)

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:240
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. CallCommonHook - lua/entities/gmod_tardis/shared.lua:49
       6. Control - lua/tardis/sh_control.lua:59
        7. unknown - lua/tardis/sh_parts.lua:298

[TARDIS] Time Rotor Handbrake engaged

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:133
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. unknown - lua/entities/gmod_door_exterior/init.lua:92

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:240
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. CallCommonHook - lua/entities/gmod_tardis/shared.lua:49
       6. Control - lua/tardis/sh_control.lua:59
        7. unknown - lua/tardis/sh_parts.lua:298

[TARDIS] Time Rotor Handbrake disengaged

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:133
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. unknown - lua/entities/gmod_door_exterior/init.lua:92 (x3)

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:240
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. CallCommonHook - lua/entities/gmod_tardis/shared.lua:49
       6. Control - lua/tardis/sh_control.lua:59
        7. unknown - lua/tardis/sh_parts.lua:298

[TARDIS] Time Rotor Handbrake engaged

[TARDIS] lua/tardis/libraries/libraries/sh_settings.lua:134: Requested setting artron_energy does not exist
  1. error - [C]:-1
   2. GetSetting - lua/tardis/libraries/libraries/sh_settings.lua:134
    3. v - lua/entities/gmod_tardis/modules/sh_artronenergy.lua:133
     4. CallHook - lua/entities/gmod_tardis/shared.lua:70
      5. unknown - lua/entities/gmod_door_exterior/init.lua:92 (x11)

Crazy origin on entity [-1][class C_PhysPropClientside]
	Origin:           [0.000000, 0.000000, -29310.972656]
	Angles:           [0.000000, 0.000000, 360.000000]
	Velocity:         [0.000000, 0.000000, -1708.147217]
	Angular Velocity: [0.000000, 0.000000, -0.000000]
Defusing!
![gm_flatgrass0048](https://github.com/MattJeanes/TARDIS/assets/129918129/cb0111de-a1da-4571-b3f5-a9fb6742b0eb)
![gm_flatgrass0049](https://github.com/MattJeanes/TARDIS/assets/129918129/b80e4b6f-c98d-47c6-afd2-1554a90f753b)

**Comment by AmyJeanes** [comment]
I'm not sure how that's happened but if you clear any file or folder containing the name 'tardis' in your garrysmod/data folder (game should not be running when you do this) it should hopefully fix it 

Note you will lose your TARDIS settings and customisations but the errors are indicating that the files are corrupted so they need clearing.

**Comment by MrSkeptickk** [comment]
> I'm not sure how that's happened but if you clear any file or folder containing the name 'tardis' in your garrysmod/data folder (game should not be running when you do this) it should hopefully fix it
> 
> Note you will lose your TARDIS settings and customisations but the errors are indicating that the files are corrupted so they need clearing.

I can't seem to find anything? 
![idk](https://github.com/MattJeanes/TARDIS/assets/129918129/27843891-b94c-4496-8d25-360051966bb9)

**Comment by captain3O** [comment]
thank you it finally works now!

**Comment by AmyJeanes** [comment]
Glad to hear!
