### ISSUE TITLE
E2 tardisFastDemat() not respecting Vortex Flight mode

### ISSUE THREAD

**Issue by jasontomasi** [MattJeanes/TARDIS#1046]
(Version: Steam workshop: 2 December 2023)

E2 hook for tardisFastDemat() only demats TARDIS for a second, then remats at same location a second later, even when Vortex Flight mode is active

Example E2 code:

`if(TARDIS:tardisLongflighted()==0) {
	TARDIS:tardisLongflight()
}

TARDIS:tardisFastDemat()`

**Comment by AmyJeanes** [comment]
This is intended behaviour, although I will admit it hasn't really got a great name. It's purpose is basically to turn off long flight (or vortex flight) just for that one trip.
