### ISSUE TITLE
Addon Suggestion. Admin Modifications

### ISSUE THREAD

**Issue by Piehthyte** [MattJeanes/TARDIS#105]
I was thinking, since world portals cause lots of lag issues for many people especially if you have a lot of tardises, There could be an admin option that would close all tardis doors. Also maybe an autoclose timer on the tardis doors to prevent from having too many world portals active at any given time.

**Comment by MattJeanes** [comment]
Doors auto close when you're far enough from the interior and I'm going to make the distance configurable, as well as a clientside option to disable portal rendering entirely.

**Comment by Piehthyte** [comment]
Good point. Did not think about any of that :p
