### ISSUE TITLE
Singleplayer: Doors are not Functioning Through Door Controller or Thirdperson 'f' Key

### ISSUE THREAD

**Issue by SingularMix** [MattJeanes/TARDIS#106]
This is not functional as of most recent update.

**Comment by SingularMix** [comment]
Double checked the bind was 'f' for thirdperson door controller.

**Comment by SingularMix** [comment]
Update: Tardis only behaves this way when in Singleplayer

**Comment by MattJeanes** [comment]
Does it still happen if you reboot your game?

**Comment by SingularMix** [comment]
Restarted game and computer works fine now.
