### ISSUE TITLE
InfMap support

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#1068]
Support for [InfMap addons](https://steamcommunity.com/sharedfiles/filedetails/?id=2905327911)

This issue is created to document an often requested feature (so that it can be found) + for its discussion

**Current status**:
Both the TARDIS and InfMaps are using their own rendering hacks

Infmaps are basically loading different parts of the map in the existing limited space, and controls which parts of the map are being shown; the TARDIS interior spawns at a random position within the world

Currently there's no known way to make the TARDIS work with infmaps

**Comment by AmyJeanes** [comment]
I have attempted to do this, but it seems really difficult to make them work together. People really want to see this though, so I may re-visit this in future but the amount of rendering hacks both addons use, making them both work together would be nearly impossible.
