### ISSUE TITLE
Singleplayer: Thirdperson keys not functioning

### ISSUE THREAD

**Issue by SingularMix** [MattJeanes/TARDIS#107]
Can not even turn on flight. RMB is non functioning along with: 'r', 'f', or 't'.
I believe the bind system is the affected part.

**Comment by SingularMix** [comment]
This is as of latest update.

**Comment by SingularMix** [comment]
Update: Tardis only behaves this way when in Singleplayer

**Comment by MattJeanes** [comment]
#106
