### ISSUE TITLE
Documentation correction: E2 tardisDoor()

### ISSUE THREAD

**Issue by jasontomasi** [MattJeanes/TARDIS#1079]
https://github.com/MattJeanes/TARDIS/blob/fdef6e54bf56feede633627c55c4fae73d93eb42/lua/entities/gmod_wire_expression2/core/custom/cl_tardis.lua#L18

Documentation states E2 hook as "tardisDoors" but should be "tardisDoor"

**Comment by AmyJeanes** [comment]
Thank you!
