### ISSUE TITLE
Third person random failure

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#110]
Sometimes going into third person fails for some reason, and the view is stuck in the players head

**Comment by MattJeanes** [comment]
![image](https://cloud.githubusercontent.com/assets/2363642/8764607/01719a4c-2ddd-11e5-98fd-37e676644610.png)

**Comment by MattJeanes** [comment]
Removing the tardis while stuck in this state seems to completely screw up the game - this needs investigating but I cannot cause it to happen - it is random

**Comment by DeadFuze** [comment]
This occurs when your fov changes from default.

**Comment by Noname12345GER** [comment]
I believe it's because if a TARDIS dematts, the exterior gets removed from the game. If it reappears, the Addon doesn't know that it has to assign the viewpos and aimpos to the TARDIS exterior again. Therefore it will Fallback to the player.

**Comment by MattJeanes** [comment]
Doctor Memes: 'Hey mate , I saw it on github that you know about the bug when you can't go to the third person view in the rewrite , I've been experementing with it and I found one thing that's causing it , if you enter the tardis while the exterior is not standing perpendicularly to the ground , the screen will not be straight and will be a little bit shaked to the side , while the screen is in that position you can't enter the third person mode and you will look at your playermodel in the sky , I hope that helps a little bit'

**Comment by MattJeanes** [comment]
I cannot reproduce the issue still:
@DeadFuze can't get it to happen when changing FOV in settings 
@Noname12345GER unfortunately this is unrelated to dematting as it can happen anywhen in my experience
And can't get it to work by trying Doctor Memes method either.

**Comment by DeadFuze** [comment]
@MattJeanes I meant an addon that changes your fov, and forces it to remain static.

**Comment by benrob0329** [comment]
Happened to me after reinstall without restarting.

**Comment by MattJeanes** [comment]
Not heard much about this in a while, hopefully fixed - let me know if anyone still sees this (with only tardis addon enabled!)
