### ISSUE TITLE
Feature Suggestion: Ability to add custom exteriors

### ISSUE THREAD

**Issue by Piehthyte** [MattJeanes/TARDIS#112]
So I saw my friend turtle uploaded the interior we were working on to be an extension of your Rewrite. I was curious if it would be possible to do the same with Exterior skins! I would really love to add some of my custom exteriors I have made to be used with your tardis.

**Comment by MattJeanes** [comment]
This is planned, I didn't include it with the multiple interior update though because it would be quite a bit of work

**Comment by MattJeanes** [comment]
Interiors can now specify custom exteriors in the next update
