### ISSUE TITLE
portal bug

### ISSUE THREAD

**Issue by cory16** [MattJeanes/TARDIS#114]
there is a bug were if i open the tardis rewrights doors the portal turn into a black box and i cant see through anymore.

**Comment by MattJeanes** [comment]
Picture? Errors? does it still happen after rebooting your game? I need details.

**Comment by cory16** [comment]
Yes I have pics of the bug send them to you tomarow

**Comment by cory16** [comment]
matt here is the glitch i spawn the tardis once despawn it and this happens
and my only fix is to restart the game
