### ISSUE TITLE
Videos on screens

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#115]
This links with #100, since music and videos would need to be synced to work properly. Might implement this to begin with clientside-only though, like the music feature

**Comment by SetyGames** [comment]
It should work like the Media Player or PlayX using the Awesomium browser.

**Comment by MattJeanes** [comment]
Not really worth implementing imo when such addons as media player / PlayX exist when you can just use those. Added issue is syncing on screens which will not be done so no point for this.
