### ISSUE TITLE
Wind sound

### ISSUE THREAD

**Issue by Galbi3000** [MattJeanes/TARDIS#116]
I don't know why your TARDIS rewrite does this or if it's peculiar to certain maps but while inside the TARDIS I hear wind, even before the latest update that includes sound effects.

I know it's because the interior is spawned somewhere high up in the air and being up high produces a wind sound in the game, however the original TARDIS mod somehow stops the wind from being heard, yours does not :/

In case it's peculiar to maps, the main map I play on is gm_construct_flatgrass_v6-2

**Comment by MattJeanes** [comment]
It is related to maps, and there's not much I can do about it

**Comment by Galbi3000** [comment]
WOW That was rude to close this so fast! The original mod does not allow the wind sound to be heard so it must be possible!

**Comment by MattJeanes** [comment]
It's related to where the interior spawns, the function that finds the position has been improved in the rewrite. It will happen in either tardis if the interiors spawned in the same place.

**Comment by Galbi3000** [comment]
I have never heard it on the original mod, and I use it a lot on that one map.

Is it possible to spawn the interior outside the map someplace? That would get rid of the sound.

**Comment by MattJeanes** [comment]
It needs to be spawned in a physical location or it won't work properly. The only thing that could have caused this is changes to the finding position function as mentioned, and the benefits for that are way too high than to revert them to potentially fix a small sound problem on one map

**Comment by Galbi3000** [comment]
It's not really a small sound problem as it's rather loud! Spoils the effect of the TARDIS. A shame really because I am so vastly impressed with your version.

**Comment by Galbi3000** [comment]
My apologies to you. It's definitely the map! I don't know why I did not notice it before but the wind sound is even there, very quietly, on the ground!

Top mod though, keep it up :)
