### ISSUE TITLE
The Future Implementations

### ISSUE THREAD

**Issue by Werner1201** [MattJeanes/TARDIS#117]
First things First , I'd like to Thank you for all the effort and time you spend on this awsome mod. If I were to know all this code stuff  I would already be helping you but I don't know. Now that you know my Feelings about this time to what a came for that is to ask What could be next implementations ?And a suggestion : Would be some kind of time vortex travel (teletransport/materialize and Dematerialize) diferent form the Addon you created ?
(sorry for the errors I'm not finish with my english curse :-) )

**Comment by MattJeanes** [comment]
In the next update, you're getting a time vortex - hopefully what you're looking for. This isn't really an issue or suggestion so I'm closing this.
