### ISSUE TITLE
Add a global mute function/setting

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#120]
This will allow me to mute audio either clientside or serverside, as a setting or for example while invisible. Sounds should be marked as ext/int so they can be muted separately. Solves the problem of easy muting everything on MP.

**Comment by Jimmycuhula** [comment]
Heya, I remember back in the Legacy Tardis where if you played a song it would stop if you re-enter the interior. So what would be cool if that when you re enter into the interior the song you were playing resumes itself.

**Comment by Jimmycuhula** [comment]
Also anyone who enters the Tardis whilst a song is currently playing gets to hear it too

**Comment by MattJeanes** [comment]
This would cause all sorts of sync issues.

**Comment by xSwindle** [comment]
I'm really hoping you're putting this as a button in the tardis rather than a setting! D:
