### ISSUE TITLE
Door windows do not match rest of skin on other skins

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#123]
Likely a model issue.

**Comment by MattJeanes** [comment]
Not sure how I fixed this but it seems fixed now

**Comment by MattJeanes** [comment]
Apparently still a problem, @theangelcastiel you got info on how to make this happen?

**Comment by theangelcastiel** [comment]
Just change the skins. The windows don't change at all.

**Comment by theangelcastiel** [comment]
If it doesn't replicate for you, I'll try doing a fresh install of gmod and the rewrite. This has always persisted for me though

**Comment by parar020100** [comment]
It all works for me
This is a very old one, so I'm closing it 
If the error happens again, please reopen
