### ISSUE TITLE
3 Bug.

### ISSUE THREAD

**Issue by LouFox-Play** [MattJeanes/TARDIS#126]
1. http://steamcommunity.com/sharedfiles/filedetails/?id=524383190 ( Are Not a phone ).

2. http://steamcommunity.com/sharedfiles/filedetails/?id=524383113 ( Are not on the screen ).

3.http://steamcommunity.com/sharedfiles/filedetails/?id=524383013 ( 2 throttle ).

**Comment by MattJeanes** [comment]
Addon out of date and conflicting with extensions.
