### ISSUE TITLE
(questio/suggestion) Logistics pipes/buildcraft pipes

### ISSUE THREAD

**Issue by Bellwar** [MattJeanes/TARDIS#127]
Is there way you can make buildcraft or maybe logistics pipes able to be transport trought roundel?

**Comment by MattJeanes** [comment]
what

**Comment by Piehthyte** [comment]
This isn't for minecraft Bellwar. This is for Garry's Mod. Buildcraft and logistics pipes are mods for Minecraft XD

**Comment by Bellwar** [comment]
-______________- i found one garrys mod this may be another......... how many time i will come to garrys mod well sorry :/ my bad and i hate it what something have same name....
