### ISSUE TITLE
TARDIS Spawn Point (RP Maps)

### ISSUE THREAD

**Issue by TobyAwesome** [MattJeanes/TARDIS#128]
I want to use the TARDIS re-write on my RP server (rp_downtown_v4c_v2) but it spawns in the walls of a hotel building on the map, I heard its because of the skyboxes being too low. would it be possible for a setting or console button to work for RP maps?

The legacy double spawn trace option fixes it, but I would much prefer to use the re-write over legacy so I could have it as a base.

Thanks for reading & great work with this mod Matt.

**Comment by xSwindle** [comment]
Maybe a superadmin-only tool to configure areas in which TARDIS-es spawn, though the way it is will be default and the owner can reset to default.

**Comment by Noname12345GER** [comment]
Should be possible to Pre-define places where the interior itselve should spawn regardless of the spawn trace with is used upon spawn of a TARDIS. Currently, i have to mark spots on the map where the TARDIS will spawn flawlessly. 

So i made up the idea that there would be a "list" with possible spawn places for the interior, with can switch between 2 or more conditions;

-Obscured
-in use
-Free

So if no more predefined coordinates are aviable, the normal spawn trace would run.

**Comment by benrob0329** [comment]
I think that the interior spawning should check for an interior in the default, and spawn net to it if obscured. 

Or perhaps a grid system for spawning, so that the maximum amount of interiors can be spawned?

**Comment by MattJeanes** [comment]
The latest update should vastly improve spawning in unusual areas. See if it fixes your issues.

**Comment by Noname12345GER** [comment]
Nope.
