### ISSUE TITLE
Cant fly TARDIS Rewrite!

### ISSUE THREAD

**Issue by Alldaygaming** [MattJeanes/TARDIS#130]
I have seen youtube videos and all oof them show the tardis rewrite flying!
It does not fly for me when i go into third person and press R.
Plus in the settings i do not see a flight button!

**Comment by MattJeanes** [comment]
Your addon is out of date or is being overridden by an extension. Uninstall all extensions and reinstall the rewrite.

**Comment by Alldaygaming** [comment]
Thanks!

**Comment by Alldaygaming** [comment]
Ummm?

**Comment by Alldaygaming** [comment]
I realaunched garrys mod and everything went wibbly wobbly.
Its like the portal is not working the tardis monitors are not place.

**Comment by MattJeanes** [comment]
Screenshot?

**Comment by Alldaygaming** [comment]
k

**Comment by Alldaygaming** [comment]
Ok i fiddled around witha few files and i fixed it!

But still cant fly it

**Comment by MattJeanes** [comment]
Can you get into third person mode? Pressing R in that should activate flight.

**Comment by Alldaygaming** [comment]
i can get in third person mod but door toggle,float toggle,and flight not work!

**Comment by MattJeanes** [comment]
Can you take a screenshot?

**Comment by Alldaygaming** [comment]
yes but how do i take a screenshot of my keys?

**Comment by Alldaygaming** [comment]
![gm_construct0008](https://cloud.githubusercontent.com/assets/15713319/11179990/4d548cf4-8c7d-11e5-87d3-005ed8b4e223.jpg)
![gm_construct0009](https://cloud.githubusercontent.com/assets/15713319/11179996/5baab35a-8c7d-11e5-91a1-1fb0259306bf.jpg)

**Comment by MattJeanes** [comment]
Ah, yes your addon is still out of date. Remove any extensions and ensure you're using the latest workshop version.

**Comment by Alldaygaming** [comment]
Thank You Dr.Matt!

You will inspire everyone just like you inspired me.
I hope you havea good life ahed of you thnk u dr matt
We love your work dont stop doing what you are doing!
