### ISSUE TITLE
AE2 compatibility oversight

### ISSUE THREAD

**Issue by NightOps007** [MattJeanes/TARDIS#131]
Trying to run tardis mod on a previously working instance, gives this crash report:
http://pastebin.com/d3zKYVSe

If I understand the report correctly, at line 57 in the report, tardis mod is trying to call to a function in the AE2 api. That api is unable to be called because AE2 is not installed and tardis mod doesn't know what to do in that case.

Adding AE2 mod fixed the issue, but I do not believe it is intended that it be a required mod. I didn't check to see if a similar error occurs with thaumcraft or the other interfaces; may be worth looking into.

**Comment by MattJeanes** [comment]
I think you've got the wrong TARDIS. This one is for Garry's Mod.
