### ISSUE TITLE
Fly into vortex

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#139]
There could be a flightmode where if you fly forwards enough the vortex starts to appear around you and you can demat like that.

Complications:
1. Need a fully textured vortex model
2. How do we calculate the speed at which it starts to demat, rewrite top speed is not constant (weight stool/carrying stuff) - probably can use some maths to determine this
3. How are we going to make a vortex appear around the tardis without it looking weird
4. What are other players not in the tardis going to see during the process

**Comment by SetyGames** [comment]
I can do number one!

**Comment by 200h** [comment]
For number 3, you can maybe look into doing something like the following:

https://www.youtube.com/watch?v=DNEjx6XUbfQ

It's a great fan-made demat where it's done from the perspective of the TARDIS.

Not sure precisely how you could do something like this, but I'd imagine something with Portals would work. Possibly a spherical with a portal projection which wraps around the main camera and allows a transition between the two states. But I'm not sure how you could do something like this in Source without dropping frames on the blend.

**Comment by NotGigo** [comment]
What kind of texture do you need? I've made a lot of vortex textures for use in After Effects before. https://www.youtube.com/watch?v=sqCBf7MQebg

**Comment by xSwindle** [comment]
Maybe it could use the uncloak effect for it to appear around the TARDIS?

**Comment by UnheardPi** [comment]
1. People are willing to do/already have. If they aren't what you are looking for, I'm pretty sure you have the skillage to make one.
2. Maths thing
3. Vortex is clientside - as in only those in that TARDIS can see it; like what you did with the interiors looking invisible to others. it doesn't need to appear around it either, it can be infront of it and you move into the vortex (if you don't you get damaged but it cancels? idk) like this https://www.youtube.com/watch?v=ni4pYFkHzuQ 
4. Regular demat. kek.

**Comment by Noname12345GER** [comment]
What about an onscreen overlay effect similar to hl2 where you have been teleported?

**Comment by Noname12345GER** [comment]
Else i thought that the TARDIS have to hold a top speed for 3 seconds, so from the outside it has a similar sparking Effect like the DeLorean and a Portal prop from hl2 citadel from b2df while the TARDIS is actually fastdematting controls are locked, so the TARDIS is forced to go in 1 way,

um too tired to write this, ill correct tomorrow

**Comment by MattJeanes** [comment]
![image](https://cloud.githubusercontent.com/assets/2363642/18041986/b7ee3c58-6db5-11e6-8794-1404ded52ce0.png)

**Comment by Noname12345GER** [comment]
Since mass affects the shape of space-time it is possible that a TARDIS may find it easier to enter and exit the Vortex away from large masses like a planet. During dematerialization it would shift itself slightly out of time - making it insubstantial and invisible. It would then lift-off to reach a safe distance from the nearest gravitational body. At this point it would enter the Vortex. Minor faults in the visual stabilization circuits would explain the numerous scenes of the TARDIS hanging or travelling through normal space.

Reference from:
http://www.whoniverse.net/tardis/dematerialisation

**Comment by MattJeanes** [comment]
This feature is now made a lot easier by the fact #54 is now complete, but I am still unsure about if I want to add this

**Comment by MattJeanes** [comment]
Apparently I completely missed this one, done!

**Comment by theangelcastiel** [comment]
What happened to this? Why was it scrapped? I thought it sounded cool.

**Comment by MattJeanes** [comment]
It's pretty much there apart from it being activated by fast speed, you can just click and fly away to achieve the effect
