### ISSUE TITLE
sh_teleport 341

### ISSUE THREAD

**Issue by DIABLOxMJ** [MattJeanes/TARDIS#141]
[TARDIS Rewrite] lua/entities/gmod_tardis/modules/sh_teleport.lua:341: attempt to call method 'GetExteriorEnt' (a nil value)
  1. v - lua/entities/gmod_tardis/modules/sh_teleport.lua:341
   2. unknown - lua/includes/modules/hook.lua:84

**Comment by MattJeanes** [comment]
This is caused by not having Doors installed or installed correctly. It can also be a result of you having too many addons installed.

**Comment by DIABLOxMJ** [comment]
[ERROR] lua/entities/gmod_tardis_interior/modules/cl_idlesound.lua:13: attempt to index field 'metadata' (a nil value)
  1. v - lua/entities/gmod_tardis_interior/modules/cl_idlesound.lua:13
   2. CallHook - lua/entities/gmod_tardis_interior/shared.lua:32
    3. func - lua/entities/gmod_door_interior/cl_init.lua:23
     4. unknown - lua/includes/extensions/net.lua:32

Installed update new error.

**Comment by MattJeanes** [comment]
It's conflicting with an older version of itself or you still have too many addons installed.

**Comment by DIABLOxMJ** [comment]
Thank you I will try to remove the addons

**Comment by MattJeanes** [comment]
Let me know how it goes.

**Comment by DIABLOxMJ** [comment]
The same error

**Comment by MattJeanes** [comment]
Ensure you do not have an old version of world-portals, the rewrite itself or doors in your addons folder. Then try unsubbing and resubbing to doors + rewrite

**Comment by DIABLOxMJ** [comment]
Too bad I will re install the addons or the game Thank you =)
