### ISSUE TITLE
Player falls through the TARDIS interior

### ISSUE THREAD

**Issue by lvivtotoro** [MattJeanes/TARDIS#143]
The player enters the TARDIS, once in the player falls.
Here is some video footage of it:
https://www.youtube.com/watch?v=eCKGoSSHrQU

This is why I think it is happening:
http://i.snag.gy/BgpTs.jpg

**Comment by MattJeanes** [comment]
Quite simply, the server doesn't have the legacy tardis addon which it needs for collision.
