### ISSUE TITLE
TARDIS Mat and Demat SFX

### ISSUE THREAD

**Issue by TGemzon** [MattJeanes/TARDIS#144]
On my client, the sounds have been changing, and I would think for the rewrite these sounds would be great!
Demat:
https://www.youtube.com/watch?v=mqNsSxvuT94
Mat:
https://www.youtube.com/watch?v=L3gqZOtt7VY

**Comment by MattJeanes** [comment]
The sounds likely changed because an extension was overriding them. I've got a big collection of sounds which likely includes the ones you sent above and I'll look into possible better sounds at some point.
