### ISSUE TITLE
Sonic Screwdriver Dispenser

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#147]
Like in the S9 finale and the S5 opener, the TARDIS had an opening to deposit Sonic Screwdrivers.

**Comment by Noname12345GER** [comment]
Should be able to choose model. Maybe you can recharge a screwdriver? (If you ever planned to add sorta battery to it)

**Comment by Alexandroid99** [comment]
It's actually not just for Sonic Screwdrivers, but for anything (in case you will put a label on it. As an extremist nerd, it would bother me :P): http://whoniverse.net/tardis/fabrication

**Comment by Cerbinwedd** [comment]
You could implemenf a feature where you can switch models of the sonic. If you already have a sonic spawned, whether from the QMenu or from the dispenser, you can press E on the dispenser to put it back, them either a prompt would pop up (like the selector from the QMenu) or you can go to the TARDIS screen menu and reselect a new model.

The sonic entity would be despawned upon placing it back respawned upon taking it out. And a sonic from the dispenser would be automatically linked to the TARDIS.

**Comment by parar020100** [comment]
Brundoob's extension has a dispencer. Perhaps we could port the existing code?

**Comment by MattJeanes** [comment]
Yeah should be relatively easy to do and a fun integration between the addons. It would need to handle if the addon doesn't exist as not everyone will have the sonic

**Comment by MattJeanes** [comment]
Added as part of #491
