### ISSUE TITLE
Visualising TARDIS teleporting onto player

### ISSUE THREAD

**Issue by SingularMix** [MattJeanes/TARDIS#148]
There should be some kind of effect for when the TARDIS teleports onto you, and you are teleported into the interior. You could use an effect already built into Gmod and that would be cool enough. Coding-wise I imagine this would probably be somewhat simple as all it would have to do is detect that a player was teleported onto and then play the effect. A cool teleportation effect used in another addon is the Buddy Finder. When you teleport there's a pretty cool effect.

**Comment by Noname12345GER** [comment]
Don't make it instant Teleport like the current Legacy feataure. Make something like it will take a total of 3 seconds to fullify the Teleport. The player is Frozen in the process. If possible, the rendermode of the player will be set to Fading, and so he will fade inside somehow. There will be no sound for entering tho.

**Comment by MattJeanes** [comment]
I like this idea, but I'm not entirely sure how possible it is, will need further investigating.

**Comment by Noname12345GER** [comment]
In first Person it's the Teleportation Effect from the beginning of Half Live 2

(If you go to Q/Post-Process you can find some nice effects.)

And else some scaling Effect with scales down the player and scales him up inside.

**Comment by Noname12345GER** [comment]
Like this one?

https://youtu.be/p5iCn0BZEoM?t=37s

**Comment by MattJeanes** [comment]
I know how the effect should work it's more a problem from on a technical perspective

**Comment by Noname12345GER** [comment]
Make the player drugged like the drug Mod! It's an Overlay with will make a washy, persistent Effect and Delay onscreen. This way if they are teleported inside, they can see the fade between world and interior.

**Comment by parar020100** [comment]
Perhaps this could be done with the white effect, like when a person is blinded by a city scanner light?

**Comment by parar020100** [comment]
Done
