### ISSUE TITLE
Suggestion: Something cute and not very big to add to the tardis

### ISSUE THREAD

**Issue by Shigbeard** [MattJeanes/TARDIS#149]
Or would we be removing something?

![Incase you for some reason cannot see this image, go ask the boneless what I'm talking about. But be careful, I hear they aren't too BIG on SIZE jokes.](http://i.imgur.com/gw17XPC.gif)

~~Incase jokes aren't your forte, basically a feature to make the tardis all so cute and tiny, but lock everybody in/out at the same time because the door is too small.~~

**Comment by MattJeanes** [comment]
I'd like to add some sort of scaling but I'm not sure the technicalities behind it at the moment.

**Comment by Noname12345GER** [comment]
If you leave door open during remat ?

Reference:
If the doors open during a Re-materialization the dimensional space pressure would compress the dimensional stability of the interior, drastically shrinking the TARDIS and its crew. Possibly even to the point of being able to explore molecules. This dimensional compression would reverse itself when the TARDIS next dematerialized. For these reasons failsafes keep the TARDIS lock from being taken apart during flight (though this can be bypassed by disconnecting the Time Rotor).

Taken from TARDIS Technical index at:
http://www.whoniverse.net/tardis/maindoors

**Comment by MattJeanes** [comment]
That's not what I meant - I meant the code required to perform such scaling

**Comment by Noname12345GER** [comment]
There is a possibility of making a collision model by Lua coordiantes

**Comment by Noname12345GER** [comment]
Else 4 Clip Planes with resize the interior door, and making a change in scale,

from the exterior the same? Kek

**Comment by Noname12345GER** [comment]
For the Portals however, a FOV change

**Comment by MattJeanes** [comment]
I see limited use in a feature that would be very complicated to write so unfortunately I'm going to close this, even though it would be kinda cool. Sorry
