### ISSUE TITLE
Odd Sonic Screwdriver destination selection.

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#150]
if you dematerialize the TARDIS with the sonic and long-flight enabled, it will just jump into the Vortex. If it is in the Vortex, you could still alter the destination where the TARDIS will land if you press R. On the Rewrite this is no longer possible. Please port it to the rewrite.

**Comment by MattJeanes** [comment]
This would be a request on the sonic, not here.

**Comment by Noname12345GER** [comment]
Actually the TARDIS is doing this. Not the Sonic.
