### ISSUE TITLE
TARDIS won't recognize Owner on DarkRP

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#151]
So I am using the TARDIS on my DarkRP server.

I am also using a script (thanks to @roboderpy) with will set the TARDIS as FPP Owner using CPPISetOwner. Unfortunately, the TARDIS is unlinkable and the isomorphic won't allow me to enable it.

In short, it won't recognize me as Owner.

**Comment by MattJeanes** [comment]
Is this on legacy branch? I'm not sure what you mean by the isomorphic bit - that's off by default and only whoever spawned it can change it.

**Comment by Noname12345GER** [comment]
Yes it's Legacy. And spawned entities from the F4 Menu in  DarkRP are World entities by default.

**Comment by MattJeanes** [comment]
`ENT.owner` needs to be set on sent_tardis at spawn time for legacy or it won't work.

In rewrite branch, you could use `ENT:SetCreator(ply)`

**Comment by Noname12345GER** [comment]
I´m horrible in lua. Couldyou please be more precise?

**Comment by Noname12345GER** [comment]
local Entities = {
	'mediaplayer_tv',
        'sent_tardis',
}

local function Buy(ply, _, ent, cost)
	if not table.HasValue(Entities, ent:GetClass()) then return end
	ent:CPPISetOwner(ply)
        ent:owner(ply)        <= Like so?
end

hook.Add('playerBoughtCustomEntity', 'DOwnability', Buy)

**Comment by MattJeanes** [comment]
`ent.owner = ply`, depending when that gets run it may not get copied over to the interior and all the parts. It should be run before the entity gets initialized.

**Comment by Noname12345GER** [comment]
thats a 50/50 chance

**Comment by Noname12345GER** [comment]
I will try that.

**Comment by Noname12345GER** [comment]
ok Screwdriver linking works, but isomorph still not. 

I dont know how to make it run before Init, but
you can make this low-priority though.

**Comment by Noname12345GER** [comment]
maybe adding the sent_isomorph to the script ?

**Comment by MattJeanes** [comment]
Two options: Either run that cppisetowner and ent. owner = ply on the interior and loop around and do it on all parts or set it before it gets initialised. I don't know how your script works other than what you gave me. Maybe your friend @roboderpy can assist?

**Comment by Noname12345GER** [comment]
I´m uncertain what you mean with the looparound.

But the script seems to setowner the sents given in the table. So should i add "sent_interior" and/or "sent_isomorph" to the table ?

**Comment by roboderpy** [comment]
@MattJeanes you mean all the constrained entities?

**Comment by roboderpy** [comment]
Will look into that

**Comment by Noname12345GER** [comment]
Nice to see you joining us, roboderpy :]

**Comment by roboderpy** [comment]
```

local Entities = {
	'mediaplayer_tv',
	'sent_tardis',
}

local function Tardis(ply, ent)
	if not IsValid(ent.interior) then return end
	
	ent.owner = ply
	ent.interior.owner = ply
	ent.interior:CPPISetOwner(ply)
	
	local self = ent.interior
	if not self.parts then return end
	
	for k, v in ipairs(self.parts) do
		if not IsValid(v) then continue end
		v.owner = ply
		v:CPPISetOwner(ply)
	end
end

local function Buy(ply, _, ent, cost)
	if not table.HasValue(Entities, ent:GetClass()) then return end
	ent:CPPISetOwner(ply)
	
	if ent:GetClass() == 'sent_tardis' then
		Tardis(ply, ent)
	end
end

hook.Add('playerBoughtCustomEntity', 'DOwnability', Buy)
```
![20160721112715_1](https://cloud.githubusercontent.com/assets/6339511/17011258/03a8bf40-4f36-11e6-804c-846002885e2b.jpg)
Works with DPP, should work with FPP too

**Comment by Noname12345GER** [comment]
We should Pin this thread or make it in the Wiki for others Users who want to use it in RP

**Comment by MattJeanes** [comment]
@roboderpy rewrite has better support for this and I'll continue to improve it. I'll make it so you can just call SetCreator on the exterior and it will apply it to everything else

**Comment by MattJeanes** [comment]
I've added Doors function `Doors:SetupOwner(ent,ply)` in the next update - passing the exterior as ent will recursively set ownership on all parts and the interior and all its parts too
