### ISSUE TITLE
Portals/Doors appear Black sometimes

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#152]
(Im not sure if this should better go in Doors section?)

Sometimes the inside will not be rendered on the exterior's door with cause it to appear Black. Entering TARDIS works normal though.

I presume it's something about the rendering if interior and exterior are too far away?

**Comment by Noname12345GER** [comment]
Any ideas?

**Comment by MattJeanes** [comment]
Do you have any more examples or screenshots or errors or something?

**Comment by Noname12345GER** [comment]
You requested Screenshots. I finally found some time to make them:

![4000_screenshots_20160909145052_1](https://cloud.githubusercontent.com/assets/20496554/18463757/b2ade5b2-798c-11e6-8e80-7479d75d177e.jpg)
![4000_screenshots_20160909145053_1](https://cloud.githubusercontent.com/assets/20496554/18463756/b2ac63f4-798c-11e6-9358-9067e9b2537e.jpg)
![4000_screenshots_20160909145054_1](https://cloud.githubusercontent.com/assets/20496554/18463760/b2afdb6a-798c-11e6-9e0b-6a93110ccb92.jpg)
![4000_screenshots_20160909145100_1](https://cloud.githubusercontent.com/assets/20496554/18463758/b2ae51d2-798c-11e6-9232-aa76362b67ec.jpg)
![4000_screenshots_20160909145132_1](https://cloud.githubusercontent.com/assets/20496554/18463761/b2b1413a-798c-11e6-828b-442838e36fb9.jpg)
![4000_screenshots_20160909145150_1](https://cloud.githubusercontent.com/assets/20496554/18463759/b2ae81ca-798c-11e6-996d-62a9ed35868a.jpg)
![4000_screenshots_20160909145202_1](https://cloud.githubusercontent.com/assets/20496554/18463762/b2c3a082-798c-11e6-9af4-a0c7ff7aa951.jpg)

**Comment by MattJeanes** [comment]
Can I get details of your computer and your graphics settings in GMod?

**Comment by Noname12345GER** [comment]
Could it be the GPU?

I would have to remind myselve to check because one I started gmod, I'll do nothing else for hours. Except making matt come for my ass.

**Comment by Noname12345GER** [comment]
http://steamcommunity.com/profiles/76561198129998583/screenshots/

**Comment by Noname12345GER** [comment]
AMD Radeon HD 6450 (GMod is playable...)

![20161006220859_1](https://cloud.githubusercontent.com/assets/20496554/19168814/3146d950-8c12-11e6-8ad5-12048f7b200f.jpg)
![20161006220901_1](https://cloud.githubusercontent.com/assets/20496554/19168809/2d7d78c4-8c12-11e6-8eee-7249bb1a2d29.jpg)

**Comment by MattJeanes** [comment]
I haven't heard much on this issue and I'm putting it down to a graphics card / source engine rendering issue so closing.
