### ISSUE TITLE
Antlions or NPCs will fear the TARDIS

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#153]
What about making the antlions or all NPC fear the TARDIS like they fear the thumpers?

**Comment by lvivtotoro** [comment]
I noticed that entities don't see you when you're in the TARDIS, because in actuality the interior is high in the sky. If you spawn in any nextbot enemy (for an example, Sanic or Merio) and walk into the TARDIS, they'll stop following you.

**Comment by Noname12345GER** [comment]
In the legacy TARDIS you would normally change your playermodel to the TARDIS itselve if you are in flight mode. In this state NPCs will target the TARDIS.

**Comment by kennyrkun** [comment]
if you want want npcs to always target the TARDIS, maybe spawn an invisible npc with no A

**Comment by MattJeanes** [comment]
This is something I want to look at, I'm not sure yet how I'd go about it but that's more on the technical side.

**Comment by Noname12345GER** [comment]
An tiny invisible Version of the actual thumper with fits into the exterior maybe? (Just without the dust effect)

**Comment by parar020100** [comment]
Relates to #370

**Comment by MattJeanes** [comment]
Closing in favour of #370
