### ISSUE TITLE
Hbombs messes with the TARDIS

### ISSUE THREAD

**Issue by benrob0329** [MattJeanes/TARDIS#154]
I set off a cluster nuke outside the TARDIS, and this happened:

![20160802184330_1](https://cloud.githubusercontent.com/assets/19180682/17348126/3b762e84-58e2-11e6-9d41-92b65e29346b.jpg)
![20160802184335_1](https://cloud.githubusercontent.com/assets/19180682/17348127/3b778414-58e2-11e6-96a5-2da6eeb8b8f6.jpg)
![20160802184343_1](https://cloud.githubusercontent.com/assets/19180682/17348123/3b73790a-58e2-11e6-8d72-fcc431b60c85.jpg)
![20160802184359_1](https://cloud.githubusercontent.com/assets/19180682/17348125/3b755f72-58e2-11e6-8106-6b08bde71934.jpg)

Thought the camera was tilted? Think again:

![20160802184414_1](https://cloud.githubusercontent.com/assets/19180682/17348128/3b792f58-58e2-11e6-9601-8f9b94c30a09.jpg)
![20160802184448_1](https://cloud.githubusercontent.com/assets/19180682/17348124/3b743070-58e2-11e6-89d2-cc7daf7998b6.jpg)

So then i set off a gadget inside the TARDIS, and Gmod couldn't handle the paradox created by it:

![screenshot_20160802_184616](https://cloud.githubusercontent.com/assets/19180682/17348158/7e4d2a32-58e2-11e6-93b8-2150772fb0ce.png)

Not sure if this should be considered a feature report or a bug report 😛

**Comment by MattJeanes** [comment]
It happens because nukes in gmod tend to unfreeze everything near it, including the tardis interior which makes it fall out of the sky. I think I'll keep this as a 'feature'.

**Comment by Noname12345GER** [comment]
What about a repair functionality with will re-initialize the interior? You just need to find the dismounted repair lever :P
