### ISSUE TITLE
sh_teleport.lua error at line 301

### ISSUE THREAD

**Issue by lvivtotoro** [MattJeanes/TARDIS#157]
This happens whenever I dematerialize the TARDIS (The gamemode is DarkRP):

`[ERROR] addons/tardis-master/lua/entities/gmod_tardis/modules/sh_teleport.lua:301: Tried to use a NULL entity!
  1. EmitSound - [C]:-1
   2. unknown - addons/tardis-master/lua/entities/gmod_tardis/modules/sh_teleport.lua:301
    3. func - addons/tardis-master/lua/entities/gmod_tardis/modules/libraries/sh_message.lua:30
     4. unknown - lua/includes/extensions/net.lua:32`

**Comment by MattJeanes** [comment]
Make sure your addon is up to date first and all dependencies are installed and up to date
