### ISSUE TITLE
No door animations

### ISSUE THREAD

**Issue by lvivtotoro** [MattJeanes/TARDIS#158]
Not sure if this is a problem on the Doors addon or not but here goes:

The TARDIS doors work, except for the fact that they do not have animations, they don't open or close, while their "hit-boxes" move normally: https://www.youtube.com/watch?v=BEf1Kr8Z88g&feature=youtu.be

No errors in the console, I have downloaded (not through the Steam Workshop):

- TARDIS Rewrite
- TARDIS Legacy
- Doors
- World Portals
- Wiremod
- Sonic Screwdriver
- DarkRP

**Comment by MattJeanes** [comment]
Does this happen on every map? Make sure everything's up to date as well.

**Comment by lvivtotoro** [comment]
Everything is up to date (I downloaded all of that from all GitHub repositories).
I noticed this only happens in rp_chaos_city_v33x_03, even though the interior and teleportation works fine.

**Comment by MattJeanes** [comment]
Okay yeah thought it could be the map, some maps have special things in them to optimise FPS by only drawing what's around you. Wherever the interior has spawned it's likely outside of this area on the map and will not draw correctly. It is unfortunately not something I think I can fix.
