### ISSUE TITLE
Exterior ghost mode can get stuck/activate when it shouldn't

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#159]
According to Doctor Memes

**Comment by MattJeanes** [comment]
It can apparently get stuck if you hold attack 1 when exiting flight and it can activate by firing the physgun just while inside the interior, even when not pilot:

Thorns: 'I know this is quite late, but it's a bug with the inside of the tardis (it still happens) where the TARDIS goes transparent with the red X (What happens when you hold left click in flight mode for easier aiming) even when not in flight mode.

To clarify: I call flying the TARDIS flight mode'

**Comment by JoshuaWierenga** [comment]
I found that this can happen if you walk just inside the doors then point sonic screwdriver at console and hold left click while walking backwards out of the doors. [image](http://prnt.sc/cb9niz)
It fixes if i walk in and out of the tardis.

**Comment by MattJeanes** [comment]
Found the cause, you never release left click once you exit the tardis still holding it so i've added a bit of code that will automatically turn off the ghost as soon as the pilot changes. Fixed for next update

**Comment by MattJeanes** [comment]
Fixed in https://github.com/MattJeanes/TARDIS/pull/174
