### ISSUE TITLE
Make TARDIS Rewrite Lockable?

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#160]
Rightclick with sonic will lock, Leftclick will open doors.
What about the Cloaking (if planned) ?
What you guys think?

**Comment by lvivtotoro** [comment]
Pretty sure left click already opens the doors
Rightclicking with the Sonic screwdriver usually cloaked it, so i'm not sure.

**Comment by MattJeanes** [comment]
Not sure why I didn't have an issue raised for this already, but this is definitely something I'll be doing.

**Comment by Noname12345GER** [comment]
The DarkRP i am playing on definently needs this!

**Comment by Noname12345GER** [comment]
Legacy:
Leftclick lock
Right click cloak

Rewrite suggestion:
Leftclick doors
Right click lock
LRclick cloak
Hold R Destination derma Menu?

**Comment by Noname12345GER** [comment]
It's very important to make the TARDIS able to toggle lock in flightmode in my opinion.

What about an function like, if the doctor entered the TARDIS, it would lock itselve?
(Maybe for the Tasker thing the TARDIS might get?)
Because many players will Rush into the TARDIS if they see it.

I know this belongs to sonic, but what about an feataure with makes players able to bind controls for the sonic themselves?

**Comment by lvivtotoro** [comment]
I think it would be awesome if the sonic had the frequency shown on itself and different frequencies do something else.

**Comment by Noname12345GER** [comment]
Sonic screwdriver Advanced Mode? Like Legacy TARDIS Advanced Mode?

And then a Menu similar to the Harry Potter Wand spell Selector?

**Comment by Paddel1504GER** [comment]
That would be so cool. Like a little Display where it Shows the current Frequency and you have like a table with set frequencys which all do something different.

350hz - Locking 
450hz - Cloaking
550hz - Flying/Demat and maybe Tracking.

That would really clean up the keybind problems.

(Table just as an example of course)

**Comment by Noname12345GER** [comment]
I am imagining an 8th screwdriver GUI where you can see the black Tip on the end with would Twist and make clicking Sounds if you select or cycle thru the frequencys listed next to it. 

I would also LOVE to NOT have a documentation ingame, so you are required to bookmark the frequency yourselve out of doctor who trivia and others sources similar to the legacy programmable flightmode where you have to build a Database yourselve.

I would also LOVE if the Sonic Settings can be set via Console commands to make keybindings possible.

Then Reserve 10 to 20 custom frequencys so people can write their own modules/extentions?

Like a Sonic Rewrite Extension.

And please don't tell me it's a Problem with my server (again).

**Comment by Noname12345GER** [comment]
I came to the conclusion, that the old Sonic might not have the ability to pack all these functions in just left and rightclicks.

**Comment by MattJeanes** [comment]
I don't know if you guys have seen the original sonic screwdriver addon which did have that, you right clicked to change frequencies and it would do different functions depending on what frequency you had.

I wrote my version of the sonic screwdriver because I thought I could do better, and one of my main goals in that was not to rely on switching between modes or 'frequencies' to do everything you want it to do. It should be point and click just like on the show, no thought required.

I'm not going to be adding frequencies to the sonic, but if you want to suggest new things for it to do you can suggest them on the [Sonic-Screwdriver](https://github.com/MattJeanes/Sonic-Screwdriver) repo. This discussion is about adding a lock to the TARDIS.

**Comment by Noname12345GER** [comment]
Yes this post vent kinda offtopic.
It kinda pulled me.

**Comment by MattJeanes** [comment]
I've added basic lock/unlock functionality in next update, things like whitelist/blacklists will come later

**Comment by MattJeanes** [comment]
I've now added lock sounds and flashing light like in legacy. Also chat messages when you try to open the locked door. Fixed a bug that would make locking take longer than it should too.
