### ISSUE TITLE
TARDIS self fixing?

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#161]
What about a function with will Respawn the TARDIS interior to an different spot if it's spawned wrong?
Like, a chat command or something?

Frequently i have to request a refund on DarkRP because it didn't Spawn as intended.

**Comment by MattJeanes** [comment]
Again this is a problem with your DarkRP, not the addon itself. I've not seen it spawn wrong since the newest update.

**Comment by Noname12345GER** [comment]
No, just a command about the 

Finding suitable place for interior to Spawn...
WARNING: no place found

To Trigger the search algorythms a second time
