### ISSUE TITLE
sv_alltalk 2 voice transfer

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#162]
Is it possible to transfer voice thru the open door if voice chat is set on DarkRP Setting? (Only players near you can hear you.)

**Comment by MattJeanes** [comment]
DarkRP would have to add support for it I think, and it's advantage is not worth the effort in my opinion.

**Comment by Noname12345GER** [comment]
Maybe I can make something with the police voice chat Addon that is used on some Servers. It looks like there is something like a function called CanHearVoice. Else i would use this Police Radio Addon and Mount it to the exterior somehow:

function Attachvoice()
local Tardises = [ ]
local Tardises = [ent.GetAll]

for k, v in pairs do
---if Tardises == FindByClass(TARDIS_exterior) then
---Mountvoice(self:pos)
end

//Should locate the new TARDIS upon remat

function Mountvoice(pos)
---ent.create(microfone, pos + Vector(0,0,300))
end

hook.add(TARDIS.remat)
--- Attachvoice()
end

Wouldn't work in practice, but just as an example.

**Comment by Noname12345GER** [comment]
The TARDIS gained an increasing popularity for darkrp. At some point not only myselve will suggest it.

**Comment by Noname12345GER** [comment]
Code as much as you can. Even if it's hard. It starts to go in eventually.

Don't be scared to code stuff you think is useless and will never get released. It's all good practice.

Look at other people's code. People who are much better than you at coding.

Never stop learning. If you think you have learned everything, find something you don't understand and learn it (templates).

~Garry James Newman

**Comment by Noname12345GER** [comment]
Btw i checked it, DarkRP HAS SUPPORT for it, else others voice addon's wouldn't be possible.

**Comment by Noname12345GER** [comment]
Have you reconsidered ?
