### ISSUE TITLE
TARDIS is permanent/persistent?

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#163]
What about an feataure with makes the TARDIS survive server restarts if in vortex and linked to a player?

If it's required to do a cleanup, it would Trigger an hook with notifies the admin in chat if a TARDIS is permanent. Then, the admin may decide to clean tardises aswell.

I like the idea of not having to buy a new TARDIS in DarkRP for the next day.

**Comment by MattJeanes** [comment]
This sounds like an issue with your DarkRP server, not my addon.

**Comment by Noname12345GER** [comment]
Would the TARDIS be compatible with gmod's make  persistent?
