### ISSUE TITLE
Whitelist for lockable TARDIS?

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#164]
I thought this doesn't fit into the locking discussion so I made a new topic for that.

Clicking an User with Sonic adds him to the Whitelist?

**Comment by Noname12345GER** [comment]
You know the sky, fog and Sun Editor of gmod? You can open a Settings Menu from the context menu. Maybe the same for the exterior? Just with Whitelist stuff?

**Comment by MattJeanes** [comment]
Everything will just go through the already existing 3D ui thing

**Comment by MattJeanes** [comment]
This falls under #60 so closing
