### ISSUE TITLE
Nanites (player healing / armour)

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#165]
What if the doctor can obtain nanites (swep) upon opening or pressing something in the TARDIS with could serve serveral purposes depending on what the doctor will send them?

-Healing
-Armor
-Disable firearms in TARDIS

For balancing, this swep can only be used inside the tardis.

How it would look:
In first Person it's the grenade/bugbait hold type with some glowing mosquitoes flying around it.

**Comment by MattJeanes** [comment]
I don't think a SWEP is the way to go with this, if I were to put this in I'd likely make it an ambient thing inside the TARDIS controlled from the settings. Similar to how I'm adding spacebuild life support, auto healing and maybe disabling firearms could work. I'll put some thought into it at some point.

**Comment by Noname12345GER** [comment]
Well, you need a way to control them. I thought of the black gmod background and the creep Holding an Orb. Knive would be an suitable hold type for this with would Switch to pistol upon shooting in an sending matter...

**Comment by MattJeanes** [comment]
They would be controlled from the tardis settings

**Comment by parar020100** [comment]
IMO, this isn't worth doing, since there are a lot of healing tools in the game, and there was nothing in the series that such gameplay would resemble

**Comment by MattJeanes** [comment]
Agreed, only thing that comes close is the nanites from The Doctor Dances but that's unrelated to the TARDIS. Closing issue.
