### ISSUE TITLE
Interior doesnt spawn / doesnt get initialzed properly

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#166]
It's a real gamble to get a perfect TARDIS:

![20160822085131_1](https://cloud.githubusercontent.com/assets/20496554/17846173/55fc4b20-6847-11e6-822e-da37174693eb.jpg)

does anyone know the cause ?
I know, it is most likely be the map, but the map doesnt have any lag reducing fog or something. The only thing the map got is a large skybox above the map. I was courios and spawned the TARDIS in the perfect middle of this skybox, (you can see the ropes and the blocks i placed in ewery corner.) but yet i get different results.

![20160822090614_1](https://cloud.githubusercontent.com/assets/20496554/17846281/ea2737f6-6847-11e6-8372-022e8fdab412.jpg)

Would'nt it be hard to define spots on the map where the interior spawns ?
Atleast as a workaround until the real cause is found?
Would it be worth the effort ?
Like, a chat command with would save all spawned TARDISes interior spots where freshly spawned TARDISes would make use of. If none of the defined spots are left, theTARDIS will use the default search algorythm for an interior to spawn.

**Comment by MattJeanes** [comment]
The TARDIS spawn algorithm was changed recently to essentially random fire 10,000 times and test the destination to see if it's within the map and that nothing is blocking the space. It picks the highest spot it could find. I'm not sure what could cause this as it should no longer spawn outside of the map or within things.

**Comment by Noname12345GER** [comment]
Is this behavior changeable? like the sonic selector drop-down menu?

Select Spawning Algorythms:
--->Make it fit in the Map
--->Seek Highest spot Possible and randomfire 10k times
--->Use Pre-Defined Spots
--->Seek largest spot possible
--->Spawn above TARDIS

**Comment by MattJeanes** [comment]
Making this customizable is not a good idea, it should be something I handle. If my code can't find a good place for it then it shouldn't spawn

**Comment by Noname12345GER** [comment]
I think that's the root of the Problem - Scripts can't always define the best spot. And people were perfectly fine with the doubletrace with fixed alot of Maps.

**Comment by Noname12345GER** [comment]
In my opinion, it should be the disabled doubletrace Type with will Spawn it above the TARDIS, but as an addition, it will check if nothing is blocking. This would be the perfect algo because you leave the players some choice, but still let the code do it.

**Comment by Noname12345GER** [comment]
What about algorythms with will depend on the most frequently used Maps?

Specially fit for the task, Hardcore, all managed by the script.

**Comment by Noname12345GER** [comment]
To revive this, i removed the coroutine for spawn selection and hardcoded a map spot in it with works for sure, And the map won't change. So I got this going for me.

I've merged a Spawn Limiter with will limit total TARDISes at one. (It's RP).

Im sorry Matt but I had to take Matter into own Hans as halve the server requested it. You should really be more open about the spawning algs.

**Comment by Noname12345GER** [comment]
I would suggest an Map loading Module with will assign TARDIS Positions accordingly by human-made points. This information will go into a Micro Addon




local pos{}
pos{
[1]=Vector(,,)
[2]=Vector(,,)
}

local maxtardis = table.count(pos)
local map = "gm_site19_v43"

TARDIS.RegisterPositions(pos, maxtardis, map)

**Comment by MattJeanes** [comment]
My understanding is that this is largely fixed at least to the degree it is possible to do so, so I'm closing this
