### ISSUE TITLE
Random lua error

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#167]
File exists in two addons - possible conflicts! lua/entities/gmod_tardis_interior/shared.lua (TARDIS Rewrite and Doors)

[ERROR] lua/entities/gmod_door_interior/modules/sh_handleplayers.lua:41: attempt to call method 'PlayerEnter' (a nil value)
  1. CheckPlayer - lua/entities/gmod_door_interior/modules/sh_handleplayers.lua:41
   2. v - lua/entities/gmod_door_interior/modules/sh_handleplayers.lua:52
    3. CallHook - lua/entities/gmod_door_interior/shared.lua:29
     4. CallHook - lua/entities/gmod_tardis_interior/shared.lua:26
      5. unknown - lua/entities/gmod_door_interior/init.lua:83

Reproducing:
Upon having one TARDIS on the map (on the very center of the skybox i mentioned in a previous post) and walking near this area:

![20160822091048_1](https://cloud.githubusercontent.com/assets/20496554/17846370/566a7d7e-6848-11e6-8ac2-7258e4fae38d.jpg)

EDIT: Another Error, upon spawning an TARDIS:

Please wait, finding suitable spawn location for interior..

File exists in two addons - possible conflicts! lua/entities/gmod_tardis_interior/shared.lua (TARDIS Rewrite and Doors)

[ERROR] lua/entities/gmod_door_interior/modules/cl_cordon.lua:46: bad argument #1 to 'LocalToWorld' (Vector expected, got nil)
  1. LocalToWorld - [C]:-1
   2. UpdateCordon - lua/entities/gmod_door_interior/modules/cl_cordon.lua:46
    3. v - lua/entities/gmod_door_interior/modules/cl_cordon.lua:109
     4. CallHook - lua/entities/gmod_door_interior/shared.lua:29
      5. CallHook - lua/entities/gmod_tardis_interior/shared.lua:26
       6. func - lua/entities/gmod_door_exterior/modules/sh_players.lua:134
        7. unknown - lua/includes/extensions/net.lua:32

Done!

Is it a problem on my side?

EDIT2:

Is this a plain addon incompantibility?

upon suiciding outside of the TARDIS then:

] kill
File exists in two addons - possible conflicts! lua/ulib/shared/hook.lua (ULib and Cable Ties Swep)

[ERROR] lua/autorun/server/addaddonfiles.lua:34: attempt to index global 'ply' (a nil value)
  1. fn - lua/autorun/server/addaddonfiles.lua:34
   2. unknown - lua/ulib/shared/hook.lua:110

Is it a problem on my side?

**Comment by MattJeanes** [comment]
This would appear to be an issue on your end, either your game didn't load correctly or some addon is causing conflicts somewhere. I was unable to reproduce your problem. If you can reliably reproduce the issue with no other addons installed then I will re-open this.
