### ISSUE TITLE
Custom (de)mat sounds

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#168]
Currently hardcoded in sh_teleport in gmod_tardis, should be from interior file (exterior section??), easy enough to do!

**Comment by Noname12345GER** [comment]
I hardly can imagine to not hear the Vwooorp!
I think the brakeless (de)mat sound would be cool if aquireable.

**Comment by doctorwho1200** [comment]
Btw, just checking out. Will you add it only to the exterior section, or make two paths for the interior and exterior?

**Comment by MattJeanes** [comment]
I'm not sure I understand, there is 2 sounds - demat and mat - they are the same between exterior and interior, unless you need them to be different? I'd like to ask why if that's the case

**Comment by doctorwho1200** [comment]
Yeah, this is exactly what i need- different exterior and interior sounds. Okay, i'll try to explain. In some episodes ( New Earth, Blink) the tardis has a bit different interior demat sound. It's a sort of accelerating flight loop sound. So I was inspired by this idea and made a special interior demat and mat sounds to use in my own project

**Comment by MattJeanes** [comment]
Makes sense, ok - done for next update

**Comment by Noname12345GER** [comment]
What about the unimplemented emergency landing Sound?

Maybe if the TARDISis in vortex and damaged to zero, it would play the emergency Land Sound instead?

If we go far enough, what about an Crash landing with makes the TARDIS Stick into the ground similar to a headcrab cannister?

**Comment by kennyrkun** [comment]
@Noname12345GER  **a** crash landing sounds like it would be pretty neat.

maybe it could look neat too?

![20160904111030_1](https://cloud.githubusercontent.com/assets/13459291/18232207/5b4c7a3e-7290-11e6-890c-3346a8c24fa7.jpg)

**Comment by MattJeanes** [comment]
Fixed in https://github.com/MattJeanes/TARDIS/pull/174
