### ISSUE TITLE
Make internal controlls always toggle

### ISSUE THREAD

**Issue by benrob0329** [MattJeanes/TARDIS#178]
For e.g. if you use the third person controls, the internal controls don't reflect the state of the TARDIS (or if you use the sonic)

My suggestion is to make them full toggles, always reflecting the state of the TARIDS.

This could also give the side effect of allowing you to quick cancel a demat (perhaps playing the ending "bang" of the remat sound and stopping the demat sound when doing so)

**Comment by MattJeanes** [comment]
The built in interiors do not have any such controls. These are all on extensions. Talk to extension developers instead for this enhancement.
