### ISSUE TITLE
Vortex does not freeze angles sometimes

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#180]
I've had this issue myself but after restarting the game it fixed itself magically and I cannot get it to happen again. In a nutshell there is code that is supposed to lock the vortex angle in place

Specifically these bits:
https://github.com/MattJeanes/TARDIS/blob/d75a854a1f7853db528e889518eaf9a94afe4714/lua/tardis/parts/vortex.lua#L25-L28
https://github.com/MattJeanes/TARDIS/blob/d75a854a1f7853db528e889518eaf9a94afe4714/lua/entities/gmod_tardis/modules/sh_vortex.lua#L95-L97

But apparently something's not quite working correctly for some people. It ends up not locking and just spinning around with the exterior instead. Difficult to fix since I cannot reproduce the problem, if anyone else has this and can reproduce it let me know!

**Comment by benrob0329** [comment]
Its happened to me, but I don't know why.

I'll let you know if you I figure anything out.

**Comment by benrob0329** [comment]
Ok, so I just reinstalled TARDIS rewrite from the workshop and (without restarting the game) opened up a game in gm_flatlands and dematted.

As per this issue, the vortex is fixed, and the TARDIS can spin freely (and independently) from it.

**Comment by MattJeanes** [comment]
How strange, seems like some sort of installation issue then

**Comment by benrob0329** [comment]
I cant seem to get it to go back to normal behavior now...

**Comment by MattJeanes** [comment]
Yeah that's exactly the problem I have - can't fix it if I can't make it happen on my computer lol

**Comment by Noname12345GER** [comment]
Is this issue about the door always facing into the blue part of vortex?

**Comment by benrob0329** [comment]
Its an issue about it not always facing the blue part of the vortex.

**Comment by benrob0329** [comment]
```
[TARDIS Rewrite] lua/tardis/parts/vortex.lua:26: bad argument #1 to 'LocalToWorld' (Vector expected, got nil)
  1. LocalToWorld - [C]:-1
   2. PreDraw - lua/tardis/parts/vortex.lua:26
    3. unknown - lua/tardis/sh_parts.lua:21


[TARDIS Rewrite] lua/tardis/parts/vortex.lua:26: bad argument #1 to 'LocalToWorld' (Vector expected, got nil)
  1. LocalToWorld - [C]:-1
   2. PreDraw - lua/tardis/parts/vortex.lua:26
    3. Draw - lua/tardis/sh_parts.lua:21
     4. unknown - gamemodes/base/entities/entities/base_anim.lua:50
```

Filled the console, and the vortex is stuck.

**Comment by benrob0329** [comment]
```
File exists in two addons - possible conflicts! lua/worldportals/render_cl.lua (Doors and TARDIS Rewrite)

[ERROR] lua/tardis/parts/vortex.lua:26: bad argument #1 to 'LocalToWorld' (Vector expected, got nil)
  1. LocalToWorld - [C]:-1
   2. PreDraw - lua/tardis/parts/vortex.lua:26
    3. Draw - lua/tardis/sh_parts.lua:21
     4. unknown - gamemodes/base/entities/entities/base_anim.lua:50
      5. RenderView - [C]:-1
       6. v - lua/worldportals/render_cl.lua:84
        7. unknown - lua/includes/modules/hook.lua:84

```

**Comment by MattJeanes** [comment]
Stuck how?

**Comment by benrob0329** [comment]
Stuck like it doesn't turn with the TARDIS.

**Comment by MattJeanes** [comment]
Ok but that's the intended behaviour? Not sure what problem you're describing

**Comment by benrob0329** [comment]
Ok wait, I think I misunderstood what the intended behavior was.

So the vortex is supposed to be stationary, and the TARDIS spin seperatly from it?

**Comment by MattJeanes** [comment]
Yeah

**Comment by MattJeanes** [comment]
Okay I've spoken to someone else who had this problem and they too were able to fix it by reinstalling the addon from workshop, so this leads me to believe it's some kind of issue with GMod not updating addons correctly. Closing as outside of my scope.
