### ISSUE TITLE
Weight toggle.

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#181]
I have noticed the TARDIS weight can be 5000 Tons, to 100 Kilograms. In some episodes, people can even Push it around.

What about a lever with toggles the weight?

As a reference, i took a Ford Raptor from TDMCars with is a Pickup with is big enough for the exterior to fit on. I would like to be able to Transport it this way.

I also thought about an Switch with enables players to Pickup the TARDIS with the Gravgun.

**Comment by xSwindle** [comment]
+1, though this should reset itself during flightmode, because that causes issues

**Comment by Noname12345GER** [comment]
There are so many unbind Buttons on the rewrite. Give it a go matt :)

**Comment by MattJeanes** [comment]
Not really seeing the massive need for this. Why not just use the weight stool?

**Comment by Noname12345GER** [comment]
Because I want an damn button and it's not worth putting an second Addon on my server with can be solved in 5 lines.

**Comment by MattJeanes** [comment]
Nice reason

**Comment by Noname12345GER** [comment]
The TARDIS got enough Buttons for that.

**Comment by Noname12345GER** [comment]
Then I'll do it then.
