### ISSUE TITLE
Stop going into 3rd person while trying to use a non-existent control 

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#184]
I noticed that if I am trying out control buttons n stuff and press E on things on the console with aren't Buttons but LOOK LIKE functional buttons, i often go into flightmode with isn't my wish.

What about Holding E on Console for 1 Second to enter flightmode?

**Comment by benrob0329** [comment]
+1

**Comment by kennyrkun** [comment]
+1 (but toggleable)

**Comment by Brundoob** [comment]
I think it should just be a separate button on the console near the flightmode switch

**Comment by kennyrkun** [comment]
that could work, we could use the telepathic circuits. it would be fitting.

**Comment by Brundoob** [comment]
That was exactly what I had in mind, or for others that don't have it, for example the 1973 TARDIS, you could use the joystick and so on.

**Comment by Noname12345GER** [comment]
Im NOT for an flightmode button.
The Console itselve fits the purpose well for Piloting.

**Comment by MattJeanes** [comment]
Maybe like hold E on the console and a small like loading bar will come up to allow you to cancel?

**Comment by Noname12345GER** [comment]
For example, yes.

**Comment by MattJeanes** [comment]
I'm thinking for this adding halos around interactive controls help the player understand what will put them into third person and what will do something on the controls, rather than a loading bar which will just slow down players when they actually want to get into third person view

**Comment by parar020100** [comment]
There might not even be a bar, it should be configurable and last for a second or half a second.
Highlighting isn't really realistic, and many people might not want it. And yes, I know those who just complain about it, as they do about every detail.

Also, it doesn't let you know which controls do what. There should be a "learning" mode with labels for all controls, but without it, there shouldn't be highlighting. A very short delay actually sounds like the best option.

**Comment by parar020100** [comment]
I've created #596 to fix this, it should happen soon
I believe this one is no longer required
