### ISSUE TITLE
What if you can leave the door open on demat?

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#185]
In the series it will cause a vaacuum or something with kills eweryone in the TARDIS. What if players have to take care of themselves to have the door shut before departure?

**Comment by doctorwho1200** [comment]
I think Matt has added an automatic door closing feature because it looks weird on the outside when the tardis disappears

**Comment by MattJeanes** [comment]
Yes, the door is forced closed during demat/mat because it looks just outright bad with the portals. There is no work-around for this and even if there was I don't really like the idea.
