### ISSUE TITLE
Kick Driver?

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#186]
I noticed it's quite hard to make a Person leave the pilot Mode on the TARDIS if they don't want to. What about an kicking feataure for the Owner?

This also applies to the legacy branch.

**Comment by Noname12345GER** [comment]
Or more importantly, preventing them to go into Pilot mode if Isomorph is on ?

**Comment by MattJeanes** [comment]
Related to https://github.com/MattJeanes/TARDIS/issues/60
