### ISSUE TITLE
Player view angle in interior rolled if the exterior is not upright 

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#187]
What about making the passengers FOV turn (like gmod camera rightclick) if the TARDIS isn't standing upright? This shouldn't affect the driver as flying would be hard then. 

It should only Tilt to 45 Degrees with is enough to fix it, and just enough that it is unbearable.

Similar to Episode "Blink" where the passengers we're shaken around inside as the Angles tried to get in.

Im not sure about that if I am making a ceiling landing. Disable it then?

EDIT: For now, it is not necessary to make the players slide around in the TARDIS. It is just Visual.

**Comment by Noname12345GER** [comment]
Im taking about this, but less extreme:
https://youtu.be/ByPrDPbdRhc?t=2m38s

**Comment by MattJeanes** [comment]
It may be worth doing something like this but I would have to make it a client option. In flight the exterior goes all over the place and we don't want passengers throwing up so the effect would have to be significantly reduced. I'll consider it but no definites yet.

**Comment by Noname12345GER** [comment]
If the TARDIS goes all over the place, it will just Quake hard with occasional 5 degree tilt with is fine.

**Comment by Noname12345GER** [comment]
I thought of that the seats will disable the effect totally.

**Comment by parar020100** [comment]
I think that TARDIS is supposed to have its own gravity, as shown in "Journey to the Centre of the TARDIS", "Day of the Moon", "Halloween Apocalypse" and many other episodes

Adding the rolled angle will ruin gameplay a lot, since flying isn't usually "smooth"

**Comment by MattJeanes** [comment]
I think the added interior shake on collision helps to bring the context of the outside world inside even if just a bit. I think practically this change would be difficult and with not really any benefit so will close this.
