### ISSUE TITLE
What about an dark interior?

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#188]
What if we make a very dark interior by default so it's actually dark if you turn the power off?

For sweet Effects, dusty light will enter the TARDIS then coming from the door.

**Comment by Noname12345GER** [comment]
Im talking about something like this: 
https://youtu.be/G8jM3Kop9eI?t=54s

Beware of Spoilers.

**Comment by kennyrkun** [comment]
I think this would be better [https://www.youtube.com/watch?v=OrFpjh4KF4U](url)

**Comment by Noname12345GER** [comment]
EXACTLY! Fantastic.

**Comment by Noname12345GER** [comment]
Put some more thought into it:

**Comment by MattJeanes** [comment]
This is covered as well as it's going to be by the addition of the power switch
