### ISSUE TITLE
Chamelion Circuit

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#189]
I don't know if someone made that up already but normal cloak gets boring.

Technicalities:
Should work like model manipulator and will disable exterior light.

How it would look:
If a prop is placed within the TARDIS and a button is pressed, there will be something like scanning, similar to the shipment spawning Effect in DarkRP using ClipPlane and an transparent texture. 
Else as a placeholder for Release, an option where you can specify an model path in Settings.

Unlike a series where a TARDIS can cloak as a building, it should not be twice as big as the original exterior. It should not be so timy that you can't go inside. I would go for the size of the square Tube in the Builder spawnlist.

**Comment by Paddel1504GER** [comment]
+1

**Comment by MattJeanes** [comment]
Just FYI you can thumbs up comments now without having to put +1

![image](https://cloud.githubusercontent.com/assets/2363642/18586509/ce5af6d0-7c14-11e6-9f1b-e3d1df93a455.png)

**Comment by Noname12345GER** [comment]
Not aviable on App.

**Comment by Noname12345GER** [comment]
#188

Close this ?

**Comment by MattJeanes** [comment]
Yeah, duplicate of #61
