### ISSUE TITLE
Transparent props / effects can disappear entirely in the interior

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#190]
If something Transparent is within the interior of any TARDIS, it can vanish unless a prop is placed behind it.

**Comment by Noname12345GER** [comment]
Why does the interior renders over ewerything after all?

**Comment by MattJeanes** [comment]
Source engine rendering issues with big enclosed models with transparency like that. I don't think there's anything that can be done.

**Comment by Noname12345GER** [comment]
What if we Split the interior in Serveral parts and make the "lid" of the interior translucent?

**Comment by kennyrkun** [comment]
does the model have to be enclosed?

**Comment by Noname12345GER** [comment]
It has to be enclosed because it will look kinda derpy without. That's why I thought of seperating these parts to not make it enclosed. By the time I am writing this I am thinking about E2 Holo Elements for the ceiling as they don't need collision.

**Comment by Noname12345GER** [comment]
Would it be possible to add some control for this? I would be fine with the imperfect lighting inside as long as it would me enable to see transparent stuff. Like its enabled by default and can be disabled with an hidden ConVar.

**Comment by MattJeanes** [comment]
The only possible solution would be to split the model up as @kennyrkun somewhat implied, not sure how well it would work though but may be worth looking at.

**Comment by Noname12345GER** [comment]
It would be worth if transparency is fixed. Many transparent player Models and future Content for the rewrite could benefit from this.

**Comment by Noname12345GER** [comment]
You could have a better cloaking system

**Comment by MattJeanes** [comment]
Closing due to source engine limitation, extensions are recommended to split up their interiors into separate models to avoid the issue
