### ISSUE TITLE
Stand on door edge in flight

### ISSUE THREAD

**Issue by SingularMix** [MattJeanes/TARDIS#192]
(I make this sound complicated so to sum it up: Stand on edge of doors while tardis is in flight/hovering.) Sounds somewhat silly and so small that i understand if you wouldn't even consider it (definitely low priority), but what about 1) make it so the flight is more firm. What i mean by this is if I stand on the exterior while the tardis is above the ground in flight then make it so the tardis doesn't slowly start going down because of the weight of at least a player. 2) Moving the portals around seems touchy, so instead of doing that extend the bottom "floor" of the Tardis police box exterior. That way you can, while in flight, stand out and look over the edge of the tardis doors while not being half in and half out of the portal as it makes it difficult to stand on edge. This would also as a bonus make it easier for the player to enter portal in a way cause you would be on the platform of Tardis floor then walk through portal on flat surface (Rather than walking up steps through portal)

**Comment by Noname12345GER** [comment]
Im for an invisible 4x4 plate on the ground to ease standing in flight.

**Comment by Noname12345GER** [comment]
I have realized, if you use the "Climb Swep" on an car in DarkRP, you can Hang on it without taking damage and with a nocollided player entity. I thought, if you could look into this, this might be possible to Peek.

**Comment by MattJeanes** [comment]
@SingularMix definitely right about low priority lol, this may just be a case of extending the collision model slightly in which case it's going to be different for each exterior anyway.

Attaching things to the exterior will affect flight and stability so it'll be difficult to do that.

**Comment by MattJeanes** [comment]
Don't think this is worth doing, would need adjusting for each extension too. You can already kind of stand on the exterior anyway as it flies

**Comment by parar020100** [comment]
Could be done in #374 , otherwise is to be closed
