### ISSUE TITLE
Spare parts system

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#194]
I have read about an emergency demat button with will dematerialize immideately, but without stabilizer modules in action. This will result an an rough takeoff and possible destroy of the zyton 7 crystals. Before the next takeoff, the user has in fact, have to replace the crystals.

Else, the following Items can be replaced too:
-Time Rotor
-Demat Circuit
-Telepathic Mercury
-Zyton 7
-Arton Vial

What I want to say is, the TARDIS shouldn't Serve only as an generic space -time machine. Make some interaction with it like maintenance.

But in fact, the TARDIS is still wip, i would prefer looking at this later.

**Comment by kennyrkun** [comment]
I'd rather this not turn into the Fallout Who mod. In Garry's Mod, it wouldn't fit. Most people just want to dick around, not worry about replacing crystals. This could be a cool feature for roleplayers, but as I say with things it should be either included in advanced mode or it should be toggleable.

**Comment by Noname12345GER** [comment]
Of course. I thought of an Gamemode detector with will enable and disable it if DarkRP is run. But this feataure must also be toggleable.

**Comment by Noname12345GER** [comment]
Of course. I thought of an Gamemode detector with will enable and disable it if DarkRP is run. But this feataure must also be toggleable.

**Comment by Noname12345GER** [comment]
If Matt just want to add Support for it, a simple check with would check if any modules were written like:

TARDIS.AddMainentance{
---if local Mercury == 0 then
------TARDIS.DematSound("sounds/emergencydemat.wav")
---end
---else
------TARDIS.DematSound(TARDIS.DefaultDematSound())
---end
}

**Comment by MattJeanes** [comment]
Related to #285

**Comment by MattJeanes** [comment]
I think some form of this could appear under #285 but as for specifically this issue I will close this.
