### ISSUE TITLE
Add page down as a valid key

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#195]
Maybe some others too

**Comment by kennyrkun** [comment]
how about support for mouse buttons 4 & 5?

**Comment by MattJeanes** [comment]
If they don't already work and it is possible to add them I will. What comes up when you try them - 'Invalid key' or something?

**Comment by Brundoob** [comment]
It just doesn't respond to them being pressed as far as I can remember

**Comment by kennyrkun** [comment]
Nevermind, it uses them just fine. Not sure if it works for the rest 9 buttons on a mouse like the Naga, but I don't have one.

**Comment by Noname12345GER** [comment]
I think source Support until fifth Mouse button

**Comment by MattJeanes** [comment]
Looks like 4th/5th mouse button support was already there, only one really missing was page down which is done for next update
