### ISSUE TITLE
Ability to change demat/mat sequence

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#196]
Both the speed and the 'sequence' so like 255 -> 100 -> 150 -> 50 -> 100 -> 0 alpha stuff

Should be pretty easy, just need to put them into the interior configs instead of hardcoded.

https://github.com/MattJeanes/TARDIS/blob/d75a854a1f7853db528e889518eaf9a94afe4714/lua/entities/gmod_tardis/modules/sh_teleport.lua#L375-L392 for sequence

and

https://github.com/MattJeanes/TARDIS/blob/d75a854a1f7853db528e889518eaf9a94afe4714/lua/entities/gmod_tardis/modules/sh_teleport.lua#L433 for speed

**Comment by Noname12345GER** [comment]
Should open some possibilities.

**Comment by MattJeanes** [comment]
Done for next update

**Comment by MattJeanes** [comment]
Worth mentioning this is for extension developers, not an in-game thing

**Comment by kennyrkun** [comment]
> Worth mentioning this is for extension developers, not an in-game thing

isn't that the reason for the developer label?

**Comment by MattJeanes** [comment]
Yeah but just incase anyone thought this was a new ingame feature
