### ISSUE TITLE
Cannot walk from one tardis to another if target is in vortex

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#198]
Unconfirmed myself, but @Philo-Wintercoat posted a video:

https://youtu.be/5VCTWxj_WGY

**Comment by Noname12345GER** [comment]
You mean the invisible Barrier with prevent you from exiting the TARDIS if it is in vortex?

**Comment by Philo-Wintercoat** [comment]
No, I mean if you teleport into the console room of a TARDIS that's in the vortex, the console room will be invisible and uninteractable until the TARDIS rematerializes.
Furthermore, if you die in the invisible console room, you respawn at map spawn, not in the TARDIS.

**Comment by Noname12345GER** [comment]
The Map Spawn is Triggered because you exited yours and did not officially enter the vortex one either am i right?

**Comment by Philo-Wintercoat** [comment]
Yes. I think all of the symptoms can be explained by the vortex TARDIS not considering the player to be in it… for some reason.

**Comment by MattJeanes** [comment]
Yeah that is exactly what's happening

**Comment by Noname12345GER** [comment]
If we would make a fix for making players able to enter an interior by being in it, wouldn't it consider noclip as entry?

**Comment by Noname12345GER** [comment]
I hate that nosy Admins could enter by noclipping

**Comment by MattJeanes** [comment]
This is existing behaviour, just not while it's in the vortex

**Comment by Noname12345GER** [comment]
No. I meant if an admin Clips inside the interior, he won't see the interior. It WOULD be annoying if an admin can enter ( = make interior visible) by simply flying inside.

**Comment by MattJeanes** [comment]
I know what you meant. That is current behaviour as I said, only it doesn't work in the vortex due to this bug.

**Comment by Philo-Wintercoat** [comment]
You can noclip-proof the interior by making a hollow box of teleport triggers around it.
And I think being able to stack TARDISes is more important than sorta-kinda protecting against teleportation.

**Comment by Noname12345GER** [comment]
Right.

**Comment by Noname12345GER** [comment]
It's about the doors failing to let a player inside due being Teleport locked. (You can still open them but can't walk thru) and I think the doors are triggering the Rendering of the interior right?

**Comment by MattJeanes** [comment]
Fixed this for next update but also had to decrease security a bit. People can now teleport to you or visit the interior in the sky to get pulled into the interior. I'll fix all of these problems when we get to the security options.
