### ISSUE TITLE
Add Support for Weaponized Type 70+ TARDISes

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#200]
It doesn't have to be done by yourselve Matt,
but I would believe that the extension coders would like to play around with it.

**Comment by kennyrkun** [comment]
if you don't think Matt should do this, don't raise an issue. contact an extension developer and request one direct from them.

**Comment by MattJeanes** [comment]
I agree

**Comment by Noname12345GER** [comment]
I thought there are technical requirements
