### ISSUE TITLE
Players visible while in TARDIS

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#202]
I have noticed that players tend to be influenced by the players Seen in the invisible interior.

What about an rendermode like distortion if players are inside? ( exept doors are open to ensure visibility if someone is looking inside )

**Comment by Noname12345GER** [comment]
I know it has to do something about the Cordon, but what about Diamond it if the doors are closed?

**Comment by MattJeanes** [comment]
It may work, I'll have to give it a go

**Comment by Noname12345GER** [comment]
Players also Shooting the interior for the lolz. Is there a way to stop damage if outsiders shoot it? Maybe check if attacker is actually in the TARDIS?

**Comment by MattJeanes** [comment]
Closing as dupe of #83
