### ISSUE TITLE
Possible fix for the vortex/map problem

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#206]
Wouldnt it fix the problem if we make the vortex smaller?

**Comment by benrob0329** [comment]
It would still end up showing the ground.

**Comment by MattJeanes** [comment]
I experimented with the vortex size when I was making it, for it to look like an actual vortex and not just some tiny thing surrounding the box it needed to be big

**Comment by Noname12345GER** [comment]
Ah.

**Comment by Noname12345GER** [comment]
Also for the Orbit of the third Person right?

**Comment by MattJeanes** [comment]
yes
