### ISSUE TITLE
Alternative Scanner

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#207]
I thought of placing all 4 Scanner Screens on  1 screen in a '+' pattern for easy checks on all Screens at the same time

**Comment by MattJeanes** [comment]
4 scanners at once would likely lag the game a lot, as it's 4 different renders of the world

**Comment by Noname12345GER** [comment]
What about a circular radar on the Scanner screen? Or maybe a very own Menu entry for this?

**Comment by Noname12345GER** [comment]
This way, the radar object in the 2010 could be utilized

**Comment by MattJeanes** [comment]
Closing due to the massive performance impact of this, although it would be cool it's just not feasible
