### ISSUE TITLE
Screen idea.

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#208]
So, developers tend to disable/move the Screens out of sight because their prefer their Screens. What if we activate the screen only if someone presses E on it? This way, the screen by the extension developers will become a "Screensaver".

**Comment by Noname12345GER** [comment]
Scaling might be a Problem then.

**Comment by MattJeanes** [comment]
I see limited use case in this, I've never heard any of the main extension devs asking for this so I'm closing this but it could be done if they ask for it
