### ISSUE TITLE
Materialization and in-vortex errors

### ISSUE THREAD

**Issue by RowanSkie** [MattJeanes/TARDIS#209]
I was toying around and checking, then I saw the vortex mode and to my shock, it just stays in the position where it dematerialized and the vortex would just appear. The map models would be inside the vortex.

I then heard that they fixed it by making the TARDIS teleport to the bottom of the map, but my TARDIS doesn't. I got pictures.

I deleted, reinstalled, and redeleted, and reinstalled the TARDIS Rewrite GMAs, and as well as the extensions... 

![gm_freedom_city0000](https://cloud.githubusercontent.com/assets/11764533/19585247/7212bc26-977d-11e6-925f-4f29e1043faf.jpg)
![gm_freedom_city0001](https://cloud.githubusercontent.com/assets/11764533/19585248/72153f6e-977d-11e6-90d4-ae678e2fb8ab.jpg)

**Comment by MattJeanes** [comment]
This is known and whoever said about moving it to the bottom of the map was wrong I never did that.

**Comment by RowanEx** [comment]
I'd also point out that you can open the doors while on the vortex (the second picture.)

**Comment by MattJeanes** [comment]
This is intentional

**Comment by Noname12345GER** [comment]
Well Rowan,

all is new.

**Comment by Noname12345GER** [comment]
But let's take an approach to this. Does the vortex work below Map?

**Comment by MattJeanes** [comment]
Taking anything outside the maps screws lighting and physics up

**Comment by Noname12345GER** [comment]
The TARDIS doesn't even collide with World of its in vortex. I tried by doing a crash landing and succseeded to Demat right before impact. I slided below the map and it didn't seem to Bug around.

**Comment by MattJeanes** [comment]
I apparently have fixed this since, if you're still seeing this issue let me know
