### ISSUE TITLE
Decals stay after dematting

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#211]
According to Boubach in Bug Reports thread

![image](https://cloud.githubusercontent.com/assets/2363642/19658890/a74d3eb0-9a21-11e6-950e-d89f9852202a.png)

**Comment by Noname12345GER** [comment]
A: Do r_cleardecals on (de)mat

B: Prevent Decals from being drawn on the exterior's by

---Delete the actual exterior and create a new, fresh exterior on demat. 
(This would open up possibilities such as changing extentions on-the-fly without respawning)

---by some rendergroup witchcraft.

---by making some Kind of hull on the exterior (for later shields)

---Intervention in the swep code

**Comment by MattJeanes** [comment]
Fixed for next update, decals are cleared at the point the exterior totally disappears, but the decals don't fade with it (don't think is possible to do)
