### ISSUE TITLE
[Legacy] Choose Position of Health HUD

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#213]
I would find it useful to choose the position of the HUD because other HUD elements tend to cover it.

**Comment by MattJeanes** [comment]
I'm not sure you understand the concept of 'legacy'

**Comment by Noname12345GER** [comment]
Not the rewrite obviously

**Comment by Noname12345GER** [comment]
So you just want to ensure compatibility?

**Comment by MattJeanes** [comment]
It means I'm no longer updating it, only fixing issues caused by GMod updates.
