### ISSUE TITLE
Function to open Locations GUI

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#215]
Like "TARDISLocationsGUI(ply)"
Will open GUI of the players currently linked TARDIS.
Currently it's a net.send function.
Im planning to make a remote.

(For Rewrite)

**Comment by MattJeanes** [comment]
Can you explain what you're trying to accomplish?

You can toggle the HUD screen with `TARDIS:HUDScreen()`

**Comment by Noname12345GER** [comment]
Incase you want to use the legacy typewriter on the rewrite

**Comment by Noname12345GER** [comment]
I want to activate the typewriter in a TARDIS legacy with a Lua function. In case you want to migrate the old legacy typewriter into the new rewrite, i would suggest that you add a function called TARDIS.Typewriter(ply) to open the GUI of the players linked TARDIS up.

**Comment by MattJeanes** [comment]
When the locations thing is added to the rewrite it will be possible to open the menu from your code

**Comment by Noname12345GER** [comment]
Nice.

**Comment by MattJeanes** [comment]
This is now possible as of #320
