### ISSUE TITLE
Selectable Height for scanner

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#216]
You know that Problem back In legacy:
The interior spawns on the wrong Height, resulting the Scanner in a difficult Position for selecting rooftops or similar.

I would add a selectable FOV, or a better Zoom.

**Comment by kennyrkun** [comment]
You can zoom in the Legacy, by right clicking. I think what you want is the ability to move up and down freely on the Y axis.

**Comment by Noname12345GER** [comment]
Sometimes, with disabled Zoom, you may still want to Zoom out further because rooftops appear zoomed in. I want to see it properly done in the rewrite. If we are going to use a 3d Scanner, this thread will be quite useless then.

**Comment by MattJeanes** [comment]
I'm already sorting this as part of #33

**Comment by Noname12345GER** [comment]
The original Threads are too damn old in my opinion.
