### ISSUE TITLE
Clicking on Fadmin Menu will control TARDIS unintentionally

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#219]
As the title says. Go on DarkRP and try to kick a player with fadmin while you are pilot.

**Comment by MattJeanes** [comment]
I'm not sure if this is possible to stop but I'll try and see if it's possible to detect any popup windows

**Comment by Noname12345GER** [comment]
The old one handled it well. Else check if Mouse is locked.

**Comment by Noname12345GER** [comment]
I think it's about the TARDIS hands swep

**Comment by MattJeanes** [comment]
I know exactly what causes it, it's the new way of handling input so I can use any key on the keyboard

**Comment by Noname12345GER** [comment]
So the legacy used Pod Controller?

**Comment by MattJeanes** [comment]
I've fixed this by stopping input if any panel is hovered
