### ISSUE TITLE
Better Time-Rotor Handbrake

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#221]
What if the TRH will actually remove the brake Sound (Boringer)? I would think it will be very realistic.

Links with #205

**Comment by Noname12345GER** [comment]
If you Release it midflight, it will... Do the same as in the show;

Clash,
*cloister*
Woop
Woop
Woop

**Comment by MattJeanes** [comment]
This is the same thing as #205

**Comment by Noname12345GER** [comment]
Made this seperate as it topics the time Rotor Handbrake is actually used for releasing the brakes. The other Thread was about the functionality.
