### ISSUE TITLE
Interior portals

### ISSUE THREAD

**Issue by doctorwho1200** [MattJeanes/TARDIS#224]
Idea is simple - you place two portals on the inside of the tardis (in the corridors for example) to make it even more bigger on the inside. It will create an illusion of endless corridors leading into the console room

**Comment by MattJeanes** [comment]
Ah yes I remember you talking to me about this. Sure.

**Comment by Noname12345GER** [comment]
Amazing idea. Question is, if the interior can be made little, can it utilize many small places in the map for an huge interior? Im still suggesting that the user should have control on how the interior spawns.

**Comment by Noname12345GER** [comment]
By the way, can your check your Mail Lex?

**Comment by Noname12345GER** [comment]
Then I would make doors near the Portals to safely deactivate them if not needed. Similar to The Doctors turquise TARDIS.
