### ISSUE TITLE
Time vortex draws on top of TARDIS interior itself ("next" branch)

### ISSUE THREAD

**Issue by Win7yes** [MattJeanes/TARDIS#226]
![image](https://cloud.githubusercontent.com/assets/7284418/22445519/8f1b005a-e726-11e6-8a49-3f7f7737446c.png)
This happens on the "next" branch probably due to the way you're rendering the vortex on top. Just demat the TARDIS.
Happens on default interior as well (the one in the picture is the 2010 extension)

**Comment by Win7yes** [comment]
![image](https://cloud.githubusercontent.com/assets/7284418/22445605/056d014a-e727-11e6-8fb3-b3d9e1fb74cd.png)
Just spotted this too

**Comment by MattJeanes** [comment]
Make sure you're also using next version of doors and latest world-portals teleport branch

**Comment by Win7yes** [comment]
Yeah I think that might be the problem lol
