### ISSUE TITLE
Automatically re-mat if left empty in vortex with no linked sonic

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#228]
As suggested by Philo Wintercoat in feature discussion.

**Comment by Noname12345GER** [comment]
Isn't that intended?

**Comment by MattJeanes** [comment]
Somewhat, which is why I'm unsure about it

**Comment by Noname12345GER** [comment]
If then, the TARDIS gets removed.

**Comment by Noname12345GER** [comment]
Unless wiremod is involved.

**Comment by Noname12345GER** [comment]
Suggestion: If you leave the TARDIS empty with no means of control (Sonic/wire) it will be removed.

If you have an "Companion" in the TARDIS while it's in vortex it's fine.

If said Companion Disconnects, the TARDIS will remat.

**Comment by MattJeanes** [comment]
I think with wiremod involved we don't know what the user might want to do here so the safest bet is to do nothing. It's not really a concern and is kind of intended behaviour so will close this
