### ISSUE TITLE
Vortex emits sound to your specific TARDIS that you spawned, and when you are in 3rd person mode 

### ISSUE THREAD

**Issue by Uriel-Diaz** [MattJeanes/TARDIS#232]

**Comment by MattJeanes** [comment]
Can you explain this a bit more? Not sure what you mean

**Comment by Uriel-Diaz** [comment]
I mean't if the TARDIS could emit sound while in the vortex like how the flight mode emits sound but can you make it so other people outside the TARDIS cannot hear it?

**Comment by MattJeanes** [comment]
Yeah it's possible but what sound would it make?

**Comment by kennyrkun** [comment]
I believe he wants [this](https://www.youtube.com/watch?v=_wJMvg1KJZU) to be played while the TARDIS is in flight, and only to those inside the TARDIS.

**Comment by Noname12345GER** [comment]
Nice and such. But Personally,I think this is annoying. An disabled Setting by default?

**Comment by Uriel-Diaz** [comment]
It would make it more alive it shouldn't be disabled that would make it disabled for everyone -_-

**Comment by kennyrkun** [comment]
It would only be disabled *by default*. If you wanted it you could enable it yourself. But as @Noname12345GER said, I doubt most people will want this sound playing while they travel. It is quite annoying. The old looping of the flight sound sounded fine.

**Comment by Uriel-Diaz** [comment]
i said for the 3rd person view on the console

**Comment by Uriel-Diaz** [comment]
not in the interior -_-

**Comment by Uriel-Diaz** [comment]
the interior flighr sound would be normal as usual

**Comment by Uriel-Diaz** [comment]
*fight

**Comment by MattJeanes** [comment]
You realise you can edit comments right? A feature that would be disabled by default is in my eyes not a good feature to add. The vortex sound linked gets annoying fast, I used to love it but it's just too irritating to play constantly, even just in third-person mode. If you can find a better sound I will reconsider.

**Comment by Uriel-Diaz** [comment]
what about the normal flight noise?

**Comment by MattJeanes** [comment]
Considering that was in the original addon and no one had any complaints about it, most likely yes.

**Comment by Uriel-Diaz** [comment]
i wss talking about 3rd person in the console

**Comment by kennyrkun** [comment]
@Uriel-Diaz what he means exactly that. It would play the same sound on the inside and out.
(And people not *using* the TARDIS in some fashion would not be able to hear it.)

**Comment by Noname12345GER** [comment]
I would rather reconsider your opinion about the disabled Features, Matt. It will allow more space for customization on the side of the user. This way you will feel sightly unfamiliar if you're in a TARDIS with isn't your own. And personally I would think every new addition is worth adding if it has a practical use.

Even something small like a Sound edit field for the Sounds accessible thru the options Tab.

**Comment by MattJeanes** [comment]
There is lots to be done, I may reconsider disable-by-default features when everything else is done.

**Comment by Noname12345GER** [comment]
Adding an Label for later reviewing? Or is this the purpose of Encancement?

**Comment by MattJeanes** [comment]
If this is still wanted when everything else is done then a new issue can be raised. This isn't going to be done for the foreseeable future so I've closed it
