### ISSUE TITLE
Can you make it so that players can change the bodygroups of objects of the interior if they have different bodygroups?

### ISSUE THREAD

**Issue by Uriel-Diaz** [MattJeanes/TARDIS#233]

**Comment by Noname12345GER** [comment]
Bodygroups of Props spawned by the TARDIS?

**Comment by MattJeanes** [comment]
I don't really get what you mean here.

**Comment by doctorwho1200** [comment]
Hmmm i think i have a small guess. Maybe he wants to change bodygroups of the interior parts? Because with the prop protection you cant access that small menu

**Comment by Uriel-Diaz** [comment]
Thanks, Doctor for explaining it. That's what I mean't.

**Comment by MattJeanes** [comment]
Right okay, what kind of props would have bodygroups that you would change? They're supposed to be part of the tardis not just random props.

**Comment by Uriel-Diaz** [comment]
I was talking about tardis parts since in my tardis there is alot of stuff that will have different bodygroups

**Comment by MattJeanes** [comment]
So you're making a TARDIS interior and you want people to be able to change the bodygroups for the purposes of customization?

**Comment by Noname12345GER** [comment]
Hmm, can the bodygroups be controlled by Scripts for more realistic damage?

**Comment by Uriel-Diaz** [comment]
Not so much customization more like different interior parts being changed such as my coat hanger i will have will be brown, and then another texture grouo will be white. Aswell a different body group for the coat hanger will look more victorian in the 2nd body group for my tardis

**Comment by Uriel-Diaz** [comment]
I personally don't think that would work for custom TARDISes, such as mine mostly due to the fact that I want it clean aswell as it being formal, and not to be damaged by some random person who doesn't care about specific rules. So, maybe there should be a feature for extensions to enable a bodygroup damage system? I'm not to sure about this, it is for Dr. Matte to decide.

**Comment by Noname12345GER** [comment]
Bodygroups for Props Sound nice, but it's different to have bodygroups for damage.

**Comment by kennyrkun** [comment]
@Uriel-Diaz bodygroup based damage won't work if there aren't damaged bodygoups, so it's completely up to the interior developer.

**Comment by Uriel-Diaz** [comment]
That makes sense I was just refining his idea.

**Comment by MattJeanes** [comment]
Closing as I don't believe this feature will see much use, the recommended workaround is to use the parts system instead of bodygroups and create a new interior extension (interior files can inherit other interiors) and override to add in the bits you need
