### ISSUE TITLE
Editing of Sounds Ingame

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#234]
#232

Editing of TARDIS Sounds if you provide a valid Sound path in the TARDIS Settings Tab. If the field is empty, the default Sound will play:

TARDIS.Sound = TARDIS.Setting.Sound or TARDIS.DefaultSound

This way, Users can't  "lose" the default settings if they mess around.

**Comment by kennyrkun** [comment]
@Noname12345GER where would custom sounds be placed?

**Comment by Noname12345GER** [comment]
Q > Top-Right-Options > Tardis

**Comment by kennyrkun** [comment]
I mean the actual files.

**Comment by Noname12345GER** [comment]
sounds/tardis/custom.
You can browse the Sounds with Sound Browser.

**Comment by MattJeanes** [comment]
Closing as I don't think this would see much use. Recommended work around is to create an extension with your preferred sounds as you can inherit other extensions and just override the property you want e.g. sound
