### ISSUE TITLE
TARDIS block zones

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#236]
Players should be able to create a kind of box area where a tardis cannot teleport into, mostly to stop abuse - especially with the upcoming scanner (#33)

**Comment by Noname12345GER** [comment]
You can make one into the interior.

**Comment by theangelcastiel** [comment]
#122 
?

**Comment by MattJeanes** [comment]
Yea good catch, wasn't sure if I had an issue for this one.. closing as dupe of #122
