### ISSUE TITLE
TARDIS Interior does not load from outside

### ISSUE THREAD

**Issue by iiEpicMan** [MattJeanes/TARDIS#237]
For some reason,whenever I spawn the TARDIS and open the doors,instead of showing the interior it shows the skybox. This happens with any TARDIS interior/exterior and any map. This also happens when viewing the outside from inside the TARDIS.

Here is what I'm talking about:
![tardis bug](https://cloud.githubusercontent.com/assets/22002151/24588750/b5e43d2a-17c6-11e7-88c0-14882f99daa6.jpg)

**Comment by iiEpicMan** [comment]
Also,one other bug is when I spawn the TARDIS an try to link it,it says "You cannot link a TARDIS you did not spawn" when I am the person who spawned it.

**Comment by kennyrkun** [comment]
@iiEpicMan please don't put two bug reports into one issue, it makes it more difficult to track things down later. 

I don't know anything about the interior not showing up, but you might try using a different extension and checking if it works then. 

As for the sonic issue, check https://github.com/MattJeanes/TARDIS/issues/151

**Comment by iiEpicMan** [comment]
Ok,sorry I'll remove the 2nd part. Also I do not understand th esoloution to thjat linking problem.

**Comment by iiEpicMan** [comment]
Also,I have tried mutliple interiors,as stated abovee,it works on none of them.

**Comment by iiEpicMan** [comment]
Um...I just went on gm_flatgrass and the interior loaded fine. Maybe it just dosn';t load on maps with multiple planets?

**Comment by MattJeanes** [comment]
SpaceBuild has been known to interfere with rendering, maybe that is why?

**Comment by iiEpicMan** [comment]
Yeah. Both maps I've tried before this were spacebuild. This hasn't happened on Spacebuild maps before though. Any idea how to fix it?

**Comment by MattJeanes** [comment]
I'm closing this as an incompatibility with SpaceBuild
