### ISSUE TITLE
Materialize Player & More

### ISSUE THREAD

**Issue by Septonix** [MattJeanes/TARDIS#238]
Ok, i realise upon using this that it would be cool if that the TARDIS materializes on you then what if you got teleported into the interior? Just a cool feature i thought would be fun to use in RP situations.
Also, wouldnt it be cool if you had the option to have the Cloister Bells play in the Interior and any players inside when the TARDIS takes damage? (Similar to the old tardis when it got destroyed) but it made the lights flash in the TARDIS and played it to them for a second while the damage is sustained?
Ok, Last suggestion... What about seige mode of the TARDIS? Now, wouldnt that be cool  : 3

P.S: I Know your gonna hate me for asking this, but why no shield? If the TARDIS is used for RP then wouldnt it be cool if for say you were surrounded by enemies with weapons, you could summon the TARDIS using the Sonic and be protected from all incoming gunfire (While its materializing)? Dont hate me for asking but i had to ask.

**Comment by kennyrkun** [comment]
If the TARDIS materialises on top of you, it will teleport you inside (I'm not sure if that's true in the rewrite, but it was in Legacy) however, without any sort of visual effects.

+1 for controllable Cloister and flashy lights.

**Comment by MattJeanes** [comment]
Can you please split out your suggestions into multiple GitHub issues, otherwise I can't respond to them properly. Thanks
