### ISSUE TITLE
Actual binding of TARDIS functions / NonPilot binds

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#244]
Nice to see so many Updates Matt! I really appreciate the effort!

The normal binds only take effect when you're Piloting the TARDIS. What if you can use them if you're just inside the TARDIS aswell?

Im thinking about an bind button in the TARDIS Settings with has a master checkbox to disable the nonpilot binds altogether.

**Comment by MattJeanes** [comment]
Non pilot binds are already there, it's just most of them are restricted to the pilot because they wouldn't make sense otherwise. How would you suggest they work?

**Comment by Noname12345GER** [comment]
I like the concept of the Q menu. If you go to top-right, Option, and TARDIS rewrite, you got the open Settings GUI button. Below that, you have these bind boxes:

vgui.Create("DBinder")

So essentially the QMenu looks like this:







-----------------------------------+

**|-------------------------|
**| Open Tardis Settings***|
**|-------------------------|

+--------------------------------------+
| Advanced Settings (Click to Expand) |
+--------------------------------------+
// A blue Spoiler


[X] Enable Nonpilot Binds

// Checkbox to disable the binds altogether. Will run tardis_use_np_binds 0/1


Demat*****************Remat
+-----------+*********+--------------+
|************| ********* |***************|
|**(NONE)**| ********* |*(Numpad +)* |
|************| ********* |***************|
+-----------+ *********+--------------+



Looks choppy, I'll try to make an actual derma with Screenshots later. This binds will enable you to control the TARDIS without having to use a vgui menu. Not that I don't like it, i just like regular binds more.

**Comment by Noname12345GER** [comment]
In addition, if You have the menu opened in the QMenu, you can open context menu to have a miniaturized Version of it.

**Comment by MattJeanes** [comment]
Ok you essentially you just want binds to do certain things that you could do in the UI with a keyboard shortcut, like say N to launch destinations or M to demat and stuff like that?

**Comment by theangelcastiel** [comment]
That sounds cool being able to press M to demat. But would you be able to do it from outside the TARDIS?What would happen when the whitelist system is implemented? Could I let certain people do the same?

**Comment by MattJeanes** [comment]
It's a good question about other people, it will need thinking about.

**Comment by theangelcastiel** [comment]
Another thing to think about. What if advanced mode is a thing for the rewrite too? Are these disabled completely since they let you quickly do things?

**Comment by Noname12345GER** [comment]
I would say this is Advanced Mode.
As I know Matts opinion about disabled defaults, let the Server Owners decide if they wish to do this.

About the Buddy, you can only be linked to one TARDIS at time. I would say binds apply to linked tardis.

**Comment by theangelcastiel** [comment]
How would this be advanced mode? 
Go more in-depth please

**Comment by Noname12345GER** [comment]
It was your idea.

**Comment by Noname12345GER** [comment]
I think Advanced mode is an greyed-out button in the UI, with will be accessible if the Owner wishes so. Advanced Mode could enable a majority of disabled defaults like damage, the DeLorean Selector etc.

**Comment by Noname12345GER** [comment]
Another way to bind stuff could be Console commands. You can bind them via Menu and via Console. I don't know if this would be more practical.

**Comment by Cerbinwedd** [comment]
I think a workaround for this would be if you could use binds only while wielding a linked sonic screwdriver - much like how the sonic has a number of functions in the series.

For instance, with a linked sonic, you could press a bind (maybe Alt+R) to make the TARDIS materialize around you and teleport you to the console.

**Comment by IMADICK666** [comment]
Or maybe the sonic could remotely control the TARDIS but with the controls being less responsive

**Comment by parar020100** [comment]
Relates to #374

**Comment by MattJeanes** [comment]
Most of this will be achieved either with #374 or can be achieved with wiremod E2, so closing this
