### ISSUE TITLE
Easier rotation for destination control

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#246]
Maybe a button to toggle between movement and rotation might be a nice idea, should fix all the weirdness in the controls we have at the moment. If anyone has any ideas do let me know in the comments.

**Comment by AlexerZoderia** [comment]
Maybe also a button that snaps the TARDIS to the nearest floor surface. Often times I have to carefully move it down to make sure it lands properly upright.

**Comment by benrob0329** [comment]
And no auto-dematting

**Comment by theangelcastiel** [comment]
Yeah that really bothers me too. It would also fix the sound not playing because of that

**Comment by benrob0329** [comment]
Having the cursor like we do now when dematting would help with placement.

**Comment by Noname12345GER** [comment]
If anfällig becomes a thing, Be mindful of the possibility to Land on a ceiling.

**Comment by theangelcastiel** [comment]
Yeah I would like rotating all ways and snapping all directions.

**Comment by parar020100** [comment]
+ (if it isn't there, which I haven't found) a way to rotate in all 3 axis, not only horizontally
