### ISSUE TITLE
See other TARDISes in the vortex.

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#250]
If you are in the vortex, and there are 2 or 3 other tardises on the map in the vortex, you can see each others exterior in the vortex.

Because the vortex is just Visual stuff, you wouldn't need to make entities but shrinked TARDISes to appear in the Funnel. So they would just be representations. 

They will have a mat and Demat effect aswell (maybe. But then they would be entities.). If they move around a little, this would be awesome.

(This should be enhancement as porting legacy is more important.)

**Comment by MattJeanes** [comment]
I don't see this being feasibly possible nor worth it for the amount of effort and work it would require.

**Comment by Noname12345GER** [comment]
Make tiny TARDIS as Effect and place it as bodygroups into the vortex.
