### ISSUE TITLE
Instantly dematerializing after remat makes vortex instantly appear

### ISSUE THREAD

**Issue by theangelcastiel** [MattJeanes/TARDIS#251]
Nothing too horrible, just thought it should be known?
It's not conflicting with any addons cause I literally only have the three required for the rewrite to work.

**Comment by theangelcastiel** [comment]
For some reason I've only noticed this happens on gm_construct, but then again I don't have any maps downloaded other than this and flatgrass.

**Comment by MattJeanes** [comment]
@Win7yes are you able to verify if this bug exists in the newest version?

**Comment by MattJeanes** [comment]
This should be fixed in next update, let me know if it isn't
