### ISSUE TITLE
Tennant and War skins don't 'fade' properly

### ISSUE THREAD

**Issue by theangelcastiel** [MattJeanes/TARDIS#254]
![image](https://cloud.githubusercontent.com/assets/14117498/25783257/5660ea7c-3316-11e7-89ec-729faf8be767.png)

I don't have any recording software and don't want to download any but the best I can explain is it stays at one transparency while dematerializing/materializing 
I tested with the four skins after noticing it with the war, here's all at once

![image](https://cloud.githubusercontent.com/assets/14117498/25783269/a953e9dc-3316-11e7-9baa-12738fc27cb6.png)

**Comment by MattJeanes** [comment]
This is just the way those extensions are modelled. As they are issues with extensions I cannot help and you should tell the authors.

**Comment by theangelcastiel** [comment]
They aren't extensions- they're the skins that come with the rewrite. I only have the rewrite, sonic, doors and vortex addons installed.

**Comment by MattJeanes** [comment]
Oh right ok, sorry my bad- i'll take a look sometime

**Comment by theangelcastiel** [comment]
Is it also worth mentioning the door windows not changing or do you already know of this?

**Comment by parar020100** [comment]
@MattJeanes I suggest we close this one as won't fix
