### ISSUE TITLE
Take a Peek at other TARDIS mods

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#263]
Just wanted to throw this one in as it looks very Inspirational.

Jump to 7:30
https://youtu.be/fWrQJ5wmt6M

My thoughts about this are;

Can we accomplish such lighting in the interior?
Possibly with #188

Can we make flight more Interactive?

If we are going to add these coordinates discs,
would they be more a swep or an entity?
#59

Is interior editing a thing, and if yes even in menas of Height and staircases?

For now, im not really Promoting the RP and survival characteristics of #194 as other things have priority.

(The Hashtags are soon linked to the appropriate issue on GitHub.)

**Comment by Noname12345GER** [comment]
Im just Posting this here in an early state of development because if we would like to add  some more complicated stuff, we can make the Code pretty open minded so it's not a pain in the ass to add them later where 3/4 of the base would have to be rewritten.

**Comment by theangelcastiel** [comment]
#59 is what you're looking for

**Comment by Noname12345GER** [comment]
Added. thank you.

**Comment by MattJeanes** [comment]
Please raise any suggestions wherever they may come from as separate issues if they do not already exist, no need for this issue
