### ISSUE TITLE
Lua Conflict

### ISSUE THREAD

**Issue by TheBlackDeaf** [MattJeanes/TARDIS#264]
Hey. Having issues with the TARDIS Rewrite, any interior on any map brings up the error below. 

File exists in two addons - possible conflicts! lua/entities/gmod_tardis_interior/shared.lua (TARDIS Rewrite and Doors)

[ERROR] lua/entities/gmod_door_interior/modules/sh_portals.lua:140: attempt to index global 'wp' (a nil value)
1. v - lua/entities/gmod_door_interior/modules/sh_portals.lua:140
2. CallHook - lua/entities/gmod_door_interior/shared.lua:31
3. CallHook - lua/entities/gmod_tardis_interior/shared.lua:28
4. DrawOverride - lua/tardis/sh_parts.lua:12
5. v - lua/entities/gmod_tardis_interior/modules/cl_parts.lua:7
6. CallHook - lua/entities/gmod_tardis_interior/shared.lua:34
7. v - lua/doors/sh_hooks.lua:32
8. unknown - lua/includes/modules/hook.lua:84

**Comment by Noname12345GER** [comment]
First guess would be make sure all is up to date.
Reinstall it.

**Comment by MattJeanes** [comment]
You may have too many addons installed, gmod starts breaking after so many

**Comment by Noname12345GER** [comment]
Matt, sorry to bother you here but,

where can I find documentation about interior creation?

**Comment by MattJeanes** [comment]
No documentation just see how it's done and copy https://github.com/MattJeanes/TARDIS/tree/master/lua/tardis/interiors

**Comment by Noname12345GER** [comment]
I think it's time to make one :)

**Comment by MattJeanes** [comment]
There is a bit of documentation here but it's not much
https://github.com/MattJeanes/TARDIS/wiki

**Comment by TheBlackDeaf** [comment]
Have reinstalled everything, Doors Addon, TARDIS Rewrite and all extensions and also have removed some unused addons. Still having issues.

**Comment by Noname12345GER** [comment]
Have you tried replacing the zyton crystals?
Nah just joking.
ULib can cause Problems in Singleplayer.

**Comment by TheBlackDeaf** [comment]
I don't have ULib. It was literally working fine before the latest update.

**Comment by MattJeanes** [comment]
Gmod I believe does some reordering of addon loading when an addon updates and that can mess with it. Just as a test try disabling every single addon apart from the rewrite and doors

**Comment by Noname12345GER** [comment]
Just Kiwi in pairs Workshop.Unsubscribe()

**Comment by TheBlackDeaf** [comment]
Sorry it's been a while since the last comment, I've been busy.

Disabled all addons, enabled Doors and TARDIS rewrite. Still a lua conflict.

**Comment by MattJeanes** [comment]
Do you have any legacy addons, particularly older versions of Doors or the rewrite that may be conflicting with workshop versions?

**Comment by TheBlackDeaf** [comment]
No, these are all the latest Workshop versions.

**Comment by MattJeanes** [comment]
Are you sure you have no legacy addon folders in `garrysmod/addons` and you've definitely got both Doors and rewrite from workshop and enabled?

**Comment by TheBlackDeaf** [comment]
Just checked, there is no legacy addon folders and I am definitely sure
that both Doors and TARDIS Rewrite is enabled.

Patrick

**Comment by MattJeanes** [comment]
Ok, try deleting the `.gma` files in your addons folder and the `garrysmod/cache` folder and then start the game back up, should force a redownload from workshop

**Comment by TheBlackDeaf** [comment]
Deleting the TARDIS rewrite and Doors gma/cache folder didn't work, but for
some reason, deleting those two AND the original TARDIS gma file worked.
However, loaded a new GMod session and the problem returned.

Patrick

**Comment by MattJeanes** [comment]
How very strange, have you tried disabling all workshop addons including rewrite/doors and trying the legacy versions from workshop? Remember that world-portals is not included with Doors on GitHub and must be downloaded separately

**Comment by TheBlackDeaf** [comment]
I could try that. Could also try a fresh install, but I don't feel like
reinstalling almost 300 addons.

**Comment by MattJeanes** [comment]
Closing due to this common GMod issue, best advice is to not have as many addons installed unfortunately.
