### ISSUE TITLE
Teleport

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#27]
This can probably be mostly taken from the old one and refined.

**Comment by Matspyder51** [comment]
Maybe create a (Fake) tardis with the teleport effect on the coordonates and remove him to add the real (Simulate the time effect)

**Comment by SingularMix** [comment]
Will you be able to teleport with doors open? Or will they close if doors are open?

**Comment by MattJeanes** [comment]
idk why this is still open, fixed a while ago
