### ISSUE TITLE
Default interior railing collisions do not exist

### ISSUE THREAD

**Issue by ProfessorNAW** [MattJeanes/TARDIS#272]
The railings on the default interior skin aren't solid.

**Comment by francodml** [comment]
The default interior has been swapped out for the "legacy" interior, so this doesn't really apply to this addon anymore. It does however apply to the "Old default" extension, but I don't know if we'll be updating that.

**Comment by MattJeanes** [comment]
We won't be updating the old default extension unless it's broken or incorrect to how it originally was when it was the default
