### ISSUE TITLE
Interior

### ISSUE THREAD

**Issue by ProfessorNAW** [MattJeanes/TARDIS#273]
If you put a zombie in the TARDIS from the outside it will crash the game.

**Comment by kennyrkun** [comment]
I tested this, doesn't seem to be an issue.

**Comment by MattJeanes** [comment]
I've never seen an issue like this one before. Are you able to provide steps to reproduce the issue?

**Comment by MattJeanes** [comment]
Also please change your issue titles, they are not very descriptive

**Comment by ProfessorNAW** [comment]
I will try right now

**Comment by ProfessorNAW** [comment]
It didn't happen this time

**Comment by ProfessorNAW** [comment]
I guess it was a one-off
