### ISSUE TITLE
Spacebuild (and similar addons) compatibility

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#28]
If you turned engines off in zero-g on spacebuild, it would fall with gravity. Need to add checks to prevent this behaviour.

Also, could do with life support being present in the interior if possible.

**Comment by MattJeanes** [comment]
[Environments](http://steamcommunity.com/sharedfiles/filedetails/?id=104484308)

**Comment by iNoPeRaTiVe** [comment]
If it's possible, when life support is turned off could gravity be turned off in the TARDIS? I don't know if that's something you can do.

**Comment by MattJeanes** [comment]
Turning gravity off on power-off would be a nice idea

**Comment by Noname12345GER** [comment]
Give objects in the TARDIS a slight applyforce upwards to make that cozy, chaotic space feeling. Ceiling collision is a Problem then.

**Comment by theangelcastiel** [comment]
Should also be a button that makes an oxygen shell around the TARDIS. Small though, so it's not OP

**Comment by theangelcastiel** [comment]
Possibly the instant the TARDIS dematerializes the set destination should have said oxygen shell too

**Comment by parar020100** [comment]
![image](https://user-images.githubusercontent.com/32988384/213815908-9c3c3e52-dadf-4d50-aaa8-d607bc9101d0.png)
![image](https://user-images.githubusercontent.com/32988384/213815917-a74764b5-375d-4076-9a2b-14a31cb3249f.png)
