### ISSUE TITLE
Cannot go through face up

### ISSUE THREAD

**Issue by MysteryPancake** [MattJeanes/TARDIS#281]
[I cannot go through when the Tardis is face up.](https://steamuserimages-a.akamaihd.net/ugc/778407480110436556/12D55401BC0B455F9C5E4E3395A50B70F49F672F/)

**Comment by MattJeanes** [comment]
This is in relation to player hitboxes as it don't think it rotates with the player, if the tardis is at the correct angle you can still go in or workaround by holding alt while entering it will force you in, or noclipping
