### ISSUE TITLE
Bullets face down

### ISSUE THREAD

**Issue by MysteryPancake** [MattJeanes/TARDIS#282]
When the Tardis is face down and bullets are fired, this is what should occur:
[The bullets hit the floor.](https://steamuserimages-a.akamaihd.net/ugc/778407480110454779/E05ED0324ABD756784422E61DE49B805C9F87DFF/)
This is the reality:
[The bullets hit the Tardis model.](https://steamuserimages-a.akamaihd.net/ugc/778407480110449133/31D79CD198F1B90C358D1CEABD196E8FBF18D890/)
I understand the complication of bullet traces at this time, but it'd be great to get this fixed.

Also, for extra realism, if you could calculate whether the Tardis is face down, you could temporarily disable the portals so objects bounce off the Tardis opening as if it were a solid wall.

**Comment by SvenyTheFox** [comment]
Stargate does this, so its probably possible, I'm not sure tho.

**Comment by MattJeanes** [comment]
It's entirely possible, the calculations just don't account for exterior rotation

**Comment by MattJeanes** [comment]
This was fixed by https://github.com/MattJeanes/world-portals/pull/9
