### ISSUE TITLE
Regenerating shield to compliment health bar (not actual shields)

### ISSUE THREAD

**Issue by AlienGamer10** [MattJeanes/TARDIS#284]
I know it's been mentioned plenty of times in the past that there won't be any shields added to the TARDIS.  I even checked through the issues on here to make sure I wasn't bringing up any old points. But I have mentioned this before on the Discussion Board and I think it could work out.

Rather than appearing as some type of force field around the TARDIS, used to block oncoming powers, makes it easier to smash through things without taking damage and all that nonsense, the TARDIS would receive a secondary health bar which would be drained upon taking damage. Once that health bar is depleted, the initial health bar would be used. All this feature would really do is add extra health essentially and perhaps a few chat messages indicating the "shield" condition.

To make sure this feature is used accordingly and not recklessly, it should be more advanced pilots (if advanced mode is still around that is) and would only take damage from weapons lightly. Smashing the TARDIS against structures would deal more damage to the "shields" or perhaps the initial health bar would also take damage. This should only really be used to defense anyways, protecting TARDISes from excessive damages without being used offensively. This extended health method seems like the only way shields could make it in without being used recklessly.

**Comment by theangelcastiel** [comment]
+warning on screen when shields depleted?

**Comment by SvenyTheFox** [comment]
I know its just to make the tardis fair in the addon but...as mentioned in the show the tardis's exterior is completely indestructible.

**Comment by theangelcastiel** [comment]
No it's not. In The Witch's familiar I think Missy mentioned a TARDIS is destructible, and the doctor was always lying about it.

**Comment by Noname12345GER** [comment]
Shields are important. Im actually working on my own TARDIS with is heavily focused on realism according to the TARDIS technical Index and Fallout who. It should be heavily configurable for DarkRP Servers. Anyway, it's Matts decision and you should accept that.

**Comment by parar020100** [comment]
I've created issue #371, which includes these ideas and some others
Will close this one as a duplicate, discussion should be moved there
