### ISSUE TITLE
When door is open, door controller displays it as "closing"

### ISSUE THREAD

**Issue by theangelcastiel** [MattJeanes/TARDIS#286]
I did test this through, disabled all addons except TARDIS/TARDIS rewrite, doors, sonic SD.

![image](https://user-images.githubusercontent.com/14117498/27007056-9979ea96-4e02-11e7-8ed2-61dda7582970.png)

**Comment by MattJeanes** [comment]
Thanks

**Comment by MattJeanes** [comment]
Assigning to @Win7yes
