### ISSUE TITLE
"You may only link a TARDIS you spawned." issue in p2p servers

### ISSUE THREAD

**Issue by SvenyTheFox** [MattJeanes/TARDIS#288]
I don't know about dedicated multiplayer servers but I am getting an issue, if im not the host of the p2p server with my friends I can't link my own tardis to my sonic screwdriver, but only the host can, its annoying since my friend who hosts the p2p server (mostly) always trolls us all by linking his sonic to our tardises and just messing everything up.
This is the message that appears when I try to link a tardis I spawned with my sonic:
You may only link a TARDIS you spawned.

**Comment by MattJeanes** [comment]
Heya, this message appears as I'm sure you can guess when you're not the owner of the tardis. Server admins however are able to, so the solution to this is that your friend needs to install some basic admin mod that allows them to make you an admin, then you can link to any tardis. You can't stop the P2P server hoster from being able to control everything as they are super admin. Hope that helps.
