### ISSUE TITLE
Buying Tardis In F4 [DARKRP]

### ISSUE THREAD

**Issue by JRServers** [MattJeanes/TARDIS#291]
Hello so when i put tardis in the f4 so people can buy it but when you buy it its invisible but its still there but when you click on it you get this error 

[TARDIS Rewrite] lua/entities/gmod_tardis/modules/sh_doors.lua:176: attempt to index field 'metadata' (a nil value)
1. v - lua/entities/gmod_tardis/modules/sh_doors.lua:176
2. CallHook - lua/entities/gmod_tardis/shared.lua:37
3. unknown - lua/entities/gmod_tardis/modules/sh_doors.lua:172
4. func - lua/entities/gmod_tardis/modules/libraries/sh_message.lua:34
5. unknown - lua/includes/extensions/net.lua:32

**Comment by MattJeanes** [comment]
How are you putting it in the F4 menu? It's complaining because it's not being spawned correctly

**Comment by JRServers** [comment]
DR Who rp want timelords to beable to buy tardis

**Comment by JRServers** [comment]
This is the code its been put in by 

DarkRP.createEntity("TARDIS", {
    ent = "gmod_tardis",
    model = "models/drmatt/tardis/exterior.mdl",
    price = 100,
    max = 1,
    cmd = "TARDIS",
    category = "TimeLords",
    customCheck = function(ply) return CLIENT or
        table.HasValue({TEAM_DOCTOR, TEAM_MASTER, TEAM_TIMELORD}, ply:Team())
    end,
    CustomCheckFailMsg = "You can not buy this",
})

**Comment by MattJeanes** [comment]
Not familar with DarkRP but it's probably spawning it weirdly under the hood, try adding a spawn property like this:

```
DarkRP.createEntity("TARDIS", {
	ent = "gmod_tardis",
	model = "models/drmatt/tardis/exterior.mdl",
	price = 100,
	max = 1,
	cmd = "TARDIS",
	category = "TimeLords",
	customCheck = function(ply) return CLIENT or
	table.HasValue({TEAM_DOCTOR, TEAM_MASTER, TEAM_TIMELORD}, ply:Team())
	end,
	CustomCheckFailMsg = "You can not buy this",
	spawn = function(ply, tr, tblEnt)
		local ent = ents.Create("gmod_tardis")
		ent:SetCreator(ply)
		ent:Initialize()
		ent:Spawn()
		return ent
	end,
})
```

Again, completely guessing here but try it out and see what happens

**Comment by JRServers** [comment]
Now its Please wait, finding suitable spawn location for interior..
Please wait, finding suitable spawn location for interior..
[DarkRP] You have bought TARDIS for $100.
Done!
 but no tardis is there  it says it spawned one but not tardis appears

**Comment by JRServers** [comment]
There is 1 Lua problem!
	Please check your console for more information!
[ERROR] A runtime error has occurred in "addons/darkrpmodification-master/lua/darkrp_customthings/entities.lua" on line 35.
The best help I can give you is this:

bad argument #1 to 'SetAngles' (Angle expected, got nil)

Hints:
	- No hints, sorry.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. addons/darkrpmodification-master/lua/darkrp_customthings/entities.lua on line 35
	2. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	4. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	5. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	6. gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua on line 357
	7. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 17
	8. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 255
	9. lua/includes/modules/concommand.lua on line 54
------- End of Simplerr error -------

**Comment by JRServers** [comment]
ALSO IT looks like this 
http://i.imgur.com/H3EZuQF.jpg

**Comment by JRServers** [comment]
i got it to work i removed the  ent:SetAngles(tr.HitAngles)

**Comment by JRServers** [comment]
you can close this thread as fixed thank you for your help, my friend.

**Comment by MattJeanes** [comment]
Ah yeah `tr.HitAngles` isn't a thing, forgot about that.. Glad to see it all works now. You're welcome.
