### ISSUE TITLE
There should be an option for lowtech skins

### ISSUE THREAD

**Issue by Noname12345GER** [MattJeanes/TARDIS#292]
Alot of gmod players have poor Hardware. An option to set ewerything to lowtex?

Probaly more an Ext.Dev thing but would be nice to have im the main code

**Comment by MattJeanes** [comment]
If the models are designed correctly setting the game to low settings will do this as they are supposed to

**Comment by Noname12345GER** [comment]
So it's exdev fault?

**Comment by MattJeanes** [comment]
Basically
