### ISSUE TITLE
Show all interiors in the spawn menu

### ISSUE THREAD

**Issue by molda76** [MattJeanes/TARDIS#296]
Hi, i would really like to see good old spawning system like legacy had, in q menu under entites/Doctor Who/2010 Tardis ( for example). This interactive spawn menu that is now isn't bad that old spawning would be much better and it would save so many time

**Comment by kennyrkun** [comment]
How would it save time? You have to scroll through so much instead, of Addons > Doctor Who > TARDIS

simple.

It'd take me like five minutes to spawn via that menu. Besides, that menu isn't really something that can be modified with addons, if I recall correctly. That one just shows you the stuff the model has.

**Comment by DoctorCZE** [comment]
I dont think you really understand what i mean

**Comment by MattJeanes** [comment]
Perhaps this could be done by adding all registered interiors into the spawn menu so you can just pick to spawn a particular one rather than just spawning the tardis which uses your saved preference. Sounds interesting!

**Comment by Win7yes** [comment]
I think the best way to go about this would be to move the TARDIS into its own "tab" in the spawnmenu, like certain addons do (CAP, Simfphys, SCars, the Pill Packs). Thoughts?

**Comment by MattJeanes** [comment]
I don't think there's enough to warrant a whole tab and most people won't have many extensions so I think it would just be an annoyance for most

**Comment by Win7yes** [comment]
Make that "one of the ways" instead of "the best way", my bad
I can't seem to find a way to just "add" entries to the existing spawnlist tab

**Comment by parar020100** [comment]
If this is somehow done, same should be done for the sonics
