### ISSUE TITLE
PULL to open?

### ISSUE THREAD

**Issue by IMADICK666** [MattJeanes/TARDIS#298]
Mabey if you press e on the little sign you'll get a message in chat that says "I think I'm opening the doors wrong" and then you can open the doors outwards and when you do for the first time the TARDIS will make a 'happy sound' (because it bugged her that the doctor always opened the doors wrong.

**Comment by IMADICK666** [comment]
And maybe more a more reactive TARDIS that makes sounds when you do stuff like when you're randomly pressing buttons when advance mode on the TARDIS will snarkly activate the vocal interface tutorial. Or when you repair the TARDIS along with a sound the lights flair up for a second. Stuff like that

**Comment by MattJeanes** [comment]
This would unfortunately result in an animation nightmare for the various exterior models so I'm going to close this, although I do think it would be a fun little idea it's just not practical
