### ISSUE TITLE
[ BUG ] Tardis inhales vechiels and props

### ISSUE THREAD

**Issue by IMADICK666** [MattJeanes/TARDIS#299]
The doors hitbox is super sensitive to everything BUT players, I can suck large trains into the TARDIS lagging the Shit out of the game without even having the doors faceing that direction, But alot of players can't get through the doors without nocliping

**Comment by tidusjar** [comment]
+1 Same issue here

**Comment by IMADICK666** [comment]
And the asthma pump ejects the giant props

**Comment by MattJeanes** [comment]
Closing as this is more a bug on https://github.com/MattJeanes/world-portals

I believe progress has been made since about only teleporting entities moving towards the portal so you can just suck up stuff by moving the portal at entities
