### ISSUE TITLE
Better notification system than chat messages

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#30]
Instead of printing to chat for things, I need a better way to do it.

**Comment by AshtonBrigman** [comment]
On this you could use the hint system as with E2 using hint( "Text", 10 ). It should be something like ply:SendHint( "Text", 10 )

**Comment by MattJeanes** [comment]
I'd rather not use GMod inbuilt stuff because it looks awful. I'd like to use something more in-universe.

**Comment by AshtonBrigman** [comment]
Maybe a voice system to play inside of the interior to alert players inside to things.

**Comment by MattJeanes** [comment]
A voice system would get pretty annoying and players with sound off wouldn't be able to know what was happening. I'm thinking of an on screen notification, sort of like the GMod hints but not the GMod hints.

**Comment by AshtonBrigman** [comment]
Oh hm maybe on the monitors inside of the tardis and a hologram representation and maybe on-hud notification system kind of thing?

**Comment by AshtonBrigman** [comment]
and/or

**Comment by MattJeanes** [comment]
Yeah something like that

**Comment by Noname12345GER** [comment]
Arton Manframe is what you are looking for

**Comment by Noname12345GER** [comment]
That's it
Subtitles!
If people need help, there will be an hint saying they need to turn on subtitles ingame.

**Comment by parar020100** [comment]
Should be done after #367
