### ISSUE TITLE
Rewrite Errors

### ISSUE THREAD

**Issue by xDarkAcidx** [MattJeanes/TARDIS#305]
Whenever I spawn a tardis of any type, I occasionally get the same error: It spawns in the tardis exterior and then has all white on the inside and does not allow you to go in. It gives me this in the console:

File exists in two addons - possible conflicts! lua/entities/gmod_tardis_interior/shared.lua (TARDIS Rewrite and Doors)

[ERROR] lua/entities/gmod_door_interior/modules/sh_portals.lua:140: attempt to index global 'wp' (a nil value)
  1. v - lua/entities/gmod_door_interior/modules/sh_portals.lua:140
   2. CallHook - lua/entities/gmod_door_interior/shared.lua:31
    3. CallHook - lua/entities/gmod_tardis_interior/shared.lua:28
     4. DrawOverride - lua/tardis/sh_parts.lua:12
      5. v - lua/entities/gmod_tardis_interior/modules/cl_parts.lua:7
       6. CallHook - lua/entities/gmod_tardis_interior/shared.lua:34
        7. v - lua/doors/sh_hooks.lua:32
         8. unknown - lua/includes/modules/hook.lua:84

This happens a lot, and is fixed only when I disable all addons, restart the game, and then enable them. This has also happened while all addons were disabled except for the rewrite and extentions, so it isn't a conflicting addon that the problem is occuring from. It also isn't my PC since this has happened to my friends as well. Please let me know if there is anything that I can do to stop/lessen the amount of times this happens. It would be greatly appreciated.

**Comment by MattJeanes** [comment]
As far as I'm aware this is caused by general GMod weirdness, if this is still happening consistently let me know
