### ISSUE TITLE
TARDIS Health

### ISSUE THREAD

**Issue by SuperDoggo** [MattJeanes/TARDIS#306]
So, I was looking in the tardis rewrite options and found nothing about health (the one in the legacy tardis)

and I got this idea:
once tardis is destroyed (0% health) you will have to use self repair lever, once used tardis interface will ask you: "what interior will you choose next?" and if you choose you can exit the tardis if not tardis self repairing will cancel automatically. when self repair completes damaged tardis will despawn and you will get a new one with the interior that you choose. So what do you think of that?

Almost forgot! you could add "drifting feature" if handbreake is not on tardis will teleport to random location (or interior) and to summon it you will need to get some sorta remote (like the rani one) and summon it or if tardis summoned itself inside the interior you have to press some combination on tardis console

**Comment by MattJeanes** [comment]
Health features are implemented in #320 to reach feature parity from the legacy but your other two suggestions are not covered here. The switching interior on repair is covered in #289 and please raise a new issue for your other one about drifting feature if you like.
