### ISSUE TITLE
Dynamic-lit Lantern(maybe windows?)

### ISSUE THREAD

**Issue by GsTheMann** [MattJeanes/TARDIS#307]
Make the TARDIS rewrite have an option to make all neon-lit things(windows, pull-to-open etc.) dynamic.

**Comment by Win7yes** [comment]
Individual extension devs will have to apply this to their exteriors I'm afraid.
There are hooks and data values to check on the power state and switch model skins accordingly.

**Comment by MattJeanes** [comment]
@Win7yes The lantern could be done for them all but the exterior windows will need work by each extension author

**Comment by MattJeanes** [comment]
Duplicate of #72
