### ISSUE TITLE
Using the sonic screwdriver to pilot the tardis makes it demat.

### ISSUE THREAD

**Issue by Ulisse54** [MattJeanes/TARDIS#310]
I'm assuming it's because I have to hold mouse1 to start piloting and driving mode picks it up as me dematerialising, as if I pressed mouse 1 while driving.

**Comment by MattJeanes** [comment]
Please see https://steamcommunity.com/workshop/filedetails/discussion/307175678/1733212454825614492/

**Comment by Ulisse54** [comment]
Awh :(
