### ISSUE TITLE
Tardis Door Glitch

### ISSUE THREAD

**Issue by CapeyBoy** [MattJeanes/TARDIS#316]
The Tardis has been having issues when entering the Tardis. The Tardis makes a weird glitch while entering and then when you turn around to look at the door, The doors look shut but they aren't. When you interact with it then it makes the door closing sfx and actually closes the door. Can this be fixed.

**Comment by MattJeanes** [comment]
Hi there, are you able to reproduce this consistently? I've not personally come across this issue

**Comment by MattJeanes** [comment]
I'm closing this issue to clean up the repo but will reopen if you can reproduce it
