### ISSUE TITLE
"Shield Force Field" on taking damage

### ISSUE THREAD

**Issue by SupinePandora43** [MattJeanes/TARDIS#319]
i want make Dalek base (maybe cyber man also) like in dalek mod for minecraft.
i'm need to know is there any way to add force field (enabling on damage) to tardis?

**Comment by MattJeanes** [comment]
There is no plans currently to add a shield to the TARDIS in the sense of something you bounce off that physically blocks props and bullets. There is however an idea for a kind of rechargeable shield the compliments the main health bar in #284
