### ISSUE TITLE
Add scanner to default interior

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#325]
Has a weird freeze frame on it

Maybe should just be replaced with a cool texture now that we have a proper scanner built in?

**Comment by parar020100** [comment]
I think it can be a normal scanner if #365 is done

**Comment by AmyJeanes** [comment]
Done, is off by default for FPS but new button enables it 
![image](https://user-images.githubusercontent.com/2363642/187089989-fe26fd8d-4a01-4802-92be-1b14a3c37e98.png)
![image](https://user-images.githubusercontent.com/2363642/187089998-c9c4bace-1f0a-4055-95b2-eeac2a02175c.png)
