### ISSUE TITLE
Destinations

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#33]
Some have suggested using an SCars DeLorean type thing, with a ghost mode 3D selector to get around the top down issue.

**Comment by Noname12345GER** [comment]
Should be an option that only admins can enable for players to use.

**Comment by MattJeanes** [comment]
Going for next update on this, still not sure if i'm just going with the old system or looking into this new one.

**Comment by Noname12345GER** [comment]
Why not both?

**Comment by Noname12345GER** [comment]
This way, it would be moddable for the users.
Moddability is key.

**Comment by MattJeanes** [comment]
The people have spoke on feature discussion, it's gonna be delorean style!

**Comment by benrob0329** [comment]
I do request that you make the camera be collision-less whilst dematted, as you otherwise cant go through floors. (though having it be configurable might be best)

**Comment by Noname12345GER** [comment]
DeLorean has one Problem:

 out of Map = no reliable Position Updates for Cam n stuff and total out of map will remove it.

**Comment by MattJeanes** [comment]
I'm renaming this destinations as scanner is already taken, if anyone has a better name let me know (but pls no i've already named all the code destinations lol)
