### ISSUE TITLE
Move server-side settings into a UI panel

### ISSUE THREAD

**Issue by Win7yes** [MattJeanes/TARDIS#330]
People seem to have trouble with the concept of using the Source console so we'll just make things easier for them. Granted this should have been a thing from the start maybe, but I thought the console was fine for starters.

**Comment by MattJeanes** [comment]
You will need to consider permissions as I believe currently there are no serverwide admin controls in the settings panel

**Comment by Win7yes** [comment]
I could use the same toolpanel we use for the Interface button. I've asked around and people would rather have it separate from the screens

**Comment by MattJeanes** [comment]
Yep that's a good idea, and they only are enabled for admins (ply:IsAdmin() or ply:IsSuperAdmin())
