### ISSUE TITLE
Clients with high latency get metadata indexed before it exists

### ISSUE THREAD

**Issue by francodml** [MattJeanes/TARDIS#334]
```
[ERROR] lua/entities/gmod_tardis/modules/sh_lock.lua:71: attempt to index field 'metadata' (a nil value)
1. unknown - lua/entities/gmod_tardis/modules/sh_lock.lua:71
2. func - lua/entities/gmod_tardis/modules/libraries/sh_message.lua:34
3. unknown - lua/includes/extensions/net.lua:32 
```

Adding a check for the variable being existing before anything is done should be enough

Known error entry points:
- sh_lock.lua:71 (85)
- sh_power.lua:32
- sh_doors.lua:230

**Comment by MattJeanes** [comment]
Good luck

**Comment by Win7yes** [comment]
>:(

**Comment by francodml** [comment]
Found out this can also happen in several other places when a player joins and there's TARDISes already spawned

**Comment by parar020100** [comment]
Also happens at sh_doors.lua:230

**Comment by parar020100** [comment]
This has been related to in #638
