### ISSUE TITLE
Zoom out view when in 3rd person flight

### ISSUE THREAD

**Issue by Moranic** [MattJeanes/TARDIS#335]
Compared to the legacy addon, the TARDIS model size was increased a bit to accomodate for the player having to fit through the doors. However, the camera distance when flying around the map in 3rd person flight remained the same. This means that a much larger portion of the screen is occupied by the TARDIS.

It would be nice if the view could be zoomed out a bit so that the TARDIS takes up roughly the same amount of screen space as in the legacy addon.

**Comment by MattJeanes** [comment]
Off the top of my head I believe you can scroll to do this?

**Comment by Moranic** [comment]
Oh wow, just tried it out and it works. I'm not sure if I've just never tried that before or if that was added after I tried it. Regardless, that resolves the issue, thanks!

**Comment by MattJeanes** [comment]
Haha you're welcome!
