### ISSUE TITLE
HADS Bug

### ISSUE THREAD

**Issue by Starbug10** [MattJeanes/TARDIS#336]
[TARDIS Rewrite] lua/tardis/screens/sh_fallbackscreen.lua:28: attempt to call method 'ToggleHADS' (a nil value)
  1. func - lua/tardis/screens/sh_fallbackscreen.lua:28
   2. Control - lua/tardis/sh_control.lua:38
    3. func - lua/tardis/sh_control.lua:53
     4. unknown - lua/includes/extensions/net.lua:32

**Comment by Win7yes** [comment]
Unfortunately I can't replicate this. Are you sure your addon is up to date?

**Comment by Starbug10** [comment]
I have fixed the issue by uninstalling the extra rewrite models etc and
start from scratch. Not 100% sure which addon caused it but I will have a
look and see.

**Comment by Win7yes** [comment]
Alrighty then. I guess I can close this.
