### ISSUE TITLE
Setting up movement coordinates.

### ISSUE THREAD

**Issue by AntohaKapitoha** [MattJeanes/TARDIS#338]
When setting the movement coordinates, you cannot select the direction the doors will be directed to. The doors of the TARDIS are always directed in one direction, which makes it impossible to get out or in when moving into a narrow space.

**Comment by MattJeanes** [comment]
Is this for the destinations? Try holding alt + shift + A/D it should rotate the ghost view

**Comment by AntohaKapitoha** [comment]
Thank you, everything works.
