### ISSUE TITLE
Host crashes when TARDIS engines are on for more than about 30 seconds

### ISSUE THREAD

**Issue by rullinoiz** [MattJeanes/TARDIS#339]
I've been having this issue for a while now, and it's when I turn on the engines. Any interior I use has this bug, so I know it isn't the extensions. I even turned off the vortex thing and it still crashes.

**Comment by parar020100** [comment]
Hello, sorry for the long reply
Please, try disabling all other addons and tell me whether the issue still happens

**Comment by parar020100** [comment]
I'm closing this issue due to the lack of response
If you come back and the problem still happens, feel free to reopen - we'll be happy to help
