### ISSUE TITLE
thirdperson is broken

### ISSUE THREAD

**Issue by PhazonOverlord115** [MattJeanes/TARDIS#342]
when i go into third person controls in the any rewrite the view camera is stuck in the player model's head and does not view the exterior like normal, can someone send me the incompatible addons in a list or text document please. thanks

**Comment by francodml** [comment]
Anything that messes with the camera. Stuff like SharpeYe, GMod Legs, all thirdperson mods. Most of these can probably be disabled. If you have any of these, especially SharpeYe and GMod Legs, try to uninstall them, or disable from their config menus.

**Comment by PhazonOverlord115** [comment]
never mind i found my conflice, its "Cbobing" but i disabled it and its working again, but thanks
