### ISSUE TITLE
Add properties/a way to control what parts isomorphic/security affects.

### ISSUE THREAD

**Issue by francodml** [MattJeanes/TARDIS#346]
Using the legacy rails with the new isomorphic from #344 will prompt you that isomorphic is turned on if you don't own the TARDIS. 
This is technically intended, as you aren't meant to be able to use anything except for the doors, but it seems ridiculous to warn for parts that aren't even controls.

Could be implemented automatically by checking if `PART.o.Use` is nil or empty (no use function, therefore it won't do anything if used).

As an added bonus I should probably add a property to control if a part shouldn't be locked down by isomorphic. (corridor doors on the interior)

**Comment by MattJeanes** [comment]
Done
