### ISSUE TITLE
Map textures deteriorate when entering and exiting Tardis

### ISSUE THREAD

**Issue by Jordiwho39** [MattJeanes/TARDIS#349]
Just updated the mod today and I'm Experiencing this weird issue on every map i test on. When i enter and exit the tardis the textures of the map i'm on deteriorate in the immediate area. Tested with most of the Rewrite Extensions and it happens with all of them. 
Example Here: 
![Screen Shot 2021-01-31 at 5 52 40 pm](https://user-images.githubusercontent.com/78293704/106376933-766a2980-63ed-11eb-91c5-3d7a423b7f60.png)

Thanks, Jordiwho39

**Comment by francodml** [comment]
Hey there, could you try to replicate this with nothing but the TARDIS Rewrite and its dependencies installed? (Doors, world-portals if you're using github)
And please, tell me what your advanced video settings are set to in GMod, it might be handy to try and reproduce this on my end.

**Comment by Jordiwho39** [comment]
I just had a fiddle around after seeing your reply, i believe it may have just been my game resolution settings, as lower resolution has fixed the issue. The game console was giving errors like "Too many vertex format changes in frame, whole world not rendered" when the door was opened but lower resolution has fixed this too. 

Regards, Jordiwho39

**Comment by MattJeanes** [comment]
Thanks for the info! Will be useful if others run into this issue in future :)
