### ISSUE TITLE
Tardis repair sets exterior to a different one that has been previously used.

### ISSUE THREAD

**Issue by MW2541** [MattJeanes/TARDIS#350]
Hello again, an obscure thing has happened. 

I had spawned two different Tardis rewrite extensions (2005 and Smith II), both of which eventually had 0% health. 
So I enter one tardis and start the 'self repair' function and wait. Once that had completed I did the same to the other tardis. When this finished, the exterior and subsequently interior changed from the Smith II extension to the default 2005 tardis. 
However I think what caused this was that I had closed the 2005 tardis doors (one on the left in the image) just at the moment the other tardis was about to finish repairing itself. 

From observation, it looks like it has set the tardis exterior to the default 2005 because of the window colour. The screen froze as though you were spawning in a new rewrite and it looks this way in the console.

There wasn't any console errors so I haven't the foggiest as to how this has happened. But I'll submit the recent console activity just in case there are any hints:

You are now the pilot.                                                                                   (2005)
Unknown command: headtrack_reset_home_pos
This TARDIS has been set to self-repair. Please vacate the interior.
You are no longer the pilot.

You are now the pilot.                                                                                   (Smith II)
Unknown command: headtrack_reset_home_pos
This TARDIS has been set to self-repair. Please vacate the interior.
You are no longer the pilot.

This TARDIS is repairing. It will be done in 2 seconds. (2005)
Your TARDIS has finished self-repairing  

This TARDIS is repairing. It will be done in 5 seconds. (Smith II)
Please wait, finding suitable spawn location for interior..
Done!

**Comment by francodml** [comment]
This is working as intended. Assuming you first spawned Smith II and, later selected in the settings, and spawned 2005; since Smith II's interior is different from the selected one (2005), the interior changes to the currently selected one on repair.

There's no way to prevent this as of right now, since every time you repair a TARDIS with an interior that doesn't match the selected one, the interior will change. This was added in the latest update.

**Comment by MW2541** [comment]
https://user-images.githubusercontent.com/78262838/106587323-5e0b2380-6541-11eb-94ab-c61058e77fa2.mp4

Hopefully this video works. It's a re-creation of what more or less happened.

**Comment by francodml** [comment]
The interior will always change to the currently selected interior. It doesn't store the interior that was selected when repair was initiated.
