### ISSUE TITLE
Add proper Time Rotor Handbrake control

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#357]
"2005 Improved" and "2010 Improved" have different versions of it
The best way to do it is to take best from both of them

Current implementations and ideas:
- [both] When handbrake on, TARDIS cannot dematerialise
- [2005] Special sound and effects for being unable to dematerialise (currently - shaking in 2005)
- [2010] A way to dematerialise with handbrake on, but explosions and damage ("engine release lever")
- [2010] It should prevent fast return and even HADS
- [both] Handbrake inside the vortex could lead to crash landing and major damage
- [2005] It should be left possible to block the ability to dematerialise by other circumstances (2005's artron absorber)
- [none] Maybe there should be a way to block materialisation too (for example, by time distortions, like "Angels take Manhatten" one), it could be easy to implement with this feature

Questions:
- Should it allow real world flight? In 2005 it does, in 2010 it used to be same as physlock (which it definetely shouldn't be, as it's often required to demat with physlock on)

**Comment by CrethFox** [comment]
The artron absorber works for both demat and remat within a radius of the device
I dunno why thats split into two points if the absorber is going to be one

**Comment by JEREDEK** [comment]
> The artron absorber works for both demat and remat within a radius of the device
> I dunno why thats split into two points if the absorber is going to be one

Actually, it doesn't fully work.
I have no ide why it doesn't work on release, since it worked on testing, but oh well.

**Comment by Mrleplayz** [comment]
The reason i made the handbrake act as a physics lock is to force players to use forced demat if they absolutely need the handbrake on. It adds a reason to use forced takeoff. I'm not implying that i want it to stay that way, all i'm saying is i thought about the idea gameplay-wise.

**Comment by parar020100** [comment]
> The reason i made the handbrake act as a physics lock is to force players to use forced demat if they absolutely need the handbrake on. It adds a reason to use forced takeoff. I'm not implying that i want it to stay that way, all i'm saying is i thought about the idea gameplay-wise.

Maybe in advanced mode, physlock would need to be on. But I think that making them synonims isn't very great

**Comment by parar020100** [comment]
> 
> 
> The artron absorber works for both demat and remat within a radius of the device
> I dunno why thats split into two points if the absorber is going to be one

Because forbidding to materialise would also be useable if there's an ability to materialise in someone else's TARDIS
It would be as part of shields

**Comment by francodml** [comment]
We already have stuff in place to tell the base teleport system if it can or can't mat/demat. For a way to TARDIS-Proof areas, I'm thinking of a tool that defines volumes where TARDISes can't teleport to (#122). If we ever add support for addons/gamemodes with power management, we could link them to something like the Artron Absorber.

**Comment by francodml** [comment]
Actually, the power management bit would be part of Wiremod support instead, so the volumes can be turned on or off at will using Wiremod.
