### ISSUE TITLE
Advanced mode

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#36]
How will this work in the rewrite? I think that it should be forceable by admins, but if forcing is off - players can choose for themselves and the setting carries across servers (client option).

**Comment by Noname12345GER** [comment]
With will turn in if you enable it?

Fuel System
Part System
Damage System
Disabled 3D teleport
Power management system...

**Comment by benrob0329** [comment]
I think that it would be handy to have an interior controlled API (similar to the original TARDIS)

**Comment by Noname12345GER** [comment]
I don't understand what you mean, benrob

**Comment by benrob0329** [comment]
I mean that the buttons and levers are all scripted in the extention, so its basically just triggering the internal "this button was pushed" api.

**Comment by Noname12345GER** [comment]
So that ewery action is 
Hardcoded into the button 
entity like:

If User == valid then
---Isomorph = true
End

**Comment by Cerbinwedd** [comment]
Advanced mode should work like in Legacy - more manual button functionality, system checks, etc. This could also mean that if you select a destination via the menu and left click, you would go back to the console to trigger the correct systems to arrive there.

So, select destination, lock destination, lock doors, physical lock enable, remove brake (for smooth flight), etc.

**Comment by kennyrkun** [comment]
Who in their right mind would release the brake, @Cerbinwedd????

**Comment by Cerbinwedd** [comment]
@kennyrkun anyone who doesn't want to hear the vwoorp. It's what the Doctor is supposed to do, and enables a peaceful flight.

**Comment by kennyrkun** [comment]
@Cerbinwedd who in their right mind wouldn't want to hear the vworp???????

This will never do. It must be optional!

**Comment by Cerbinwedd** [comment]
That's the intention. Clearly it CAN fly with the brake on, hence the origin of the vwoorp, but for those who don't want to hear the vwoorp, they can release the brake.

**Comment by Cerbinwedd** [comment]
The tutorial, should he add it, would  mention it as such:

"Reminder: operators must release Space-Rotor Handbrake for optimal TARDIS transport. Failure to do so will result in Cloister Bell malfunction, signaling improper flight operation."

Or some other handbook-esque message

**Comment by MattJeanes** [comment]
@Win7yes has very nicely added advanced mode for the rewrite in the next update
