### ISSUE TITLE
Fixes for visual gui in the future updates

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#360]
There are many things we want to be added later from the review https://github.com/MattJeanes/TARDIS/pull/359
The list will be at this issue

**Comment by parar020100** [comment]
1. Better label texts if the button texture is missing
"Textonly" theme should be returned for debugging purposes
Conversation: https://github.com/MattJeanes/TARDIS/pull/359#discussion_r580690094

**Comment by parar020100** [comment]
2. "Virtual Console" was renamed into "Console" for the order of buttons.
It should be returned, while a new ordering system is added

Conversation: https://github.com/MattJeanes/TARDIS/pull/359#discussion_r580690325

**Comment by parar020100** [comment]
3. There should be a better way of naming themes rather than just folder names

Conversation: https://github.com/MattJeanes/TARDIS/pull/359#discussion_r580690925

**Comment by parar020100** [comment]
4. Make themes able to inherit each other somehow

> Themes should have a "base" concept to reduce duplication, as we can see with the default / vortex everything is copied apart from the background which isn't great at all. I would recommend building a manifest of all the files for each folder, starting from the furthest down one that has no base at all, and then overriding any existing files as you go back up to the top level, and saving that in a global variable somewhere which can be accessed to find appropriate textures without duplicating them - much like how the AddInterior code works. 

Conversation: https://github.com/MattJeanes/TARDIS/pull/359#discussion_r580693804

**Comment by parar020100** [comment]
5. Make panel buttons scale properly

**Comment by parar020100** [comment]
6. Codestyle: 
Go through all previous changes
Remove commented out lines
Make "do" and "then" at same lines as "while" and "if"

**Comment by parar020100** [comment]
7. Remove color changing background, which still blends through the new UI
Add black screen as background instead

**Comment by parar020100** [comment]
8. Text wrapping for UI without icons
Now it's overlapping a lot 

Example: 
![изображение](https://user-images.githubusercontent.com/32988384/109049155-f92e8d80-76e8-11eb-9b6b-5c7cb911024e.png)

**Comment by parar020100** [comment]
9. Add padding to the bottom of spawnmenu options
Currently there isn't any

![изображение](https://user-images.githubusercontent.com/32988384/109053213-87a50e00-76ed-11eb-9332-4b948c4b4d1e.png)

**Comment by parar020100** [comment]
10. Add frames for icons so that two copies of same icon for different states don't have to exist

**Comment by parar020100** [comment]
10. Make possible to specify default "numrows" values for interiors and a chackbox to override them

**Comment by francodml** [comment]
> 10. Make possible to specify default "numrows" values for interiors and a chackbox to override them

If interiors can override this, I'd recommend trying to guess numrows from screen size. If not, maybe adding it to the screen definition bits on interiors.

**Comment by MattJeanes** [comment]
Some of this is now done, happy for others to be left as part of this release

**Comment by parar020100** [comment]
1,3,4,6,7,9, 10 done

**Comment by parar020100** [comment]
11. Bug: you can press invisible buttons on the screen if invisibility was set by scrolling

**Comment by parar020100** [comment]
12. Return text only theme icons (accidentally changed)

**Comment by parar020100** [comment]
2 is done

**Comment by parar020100** [comment]
11 is fixed
Remaining: 5,8,12

**Comment by parar020100** [comment]
Fixed 5
8 isn't really related to this feature, should be in a different one, I will create it

**Comment by parar020100** [comment]
With #423 merged, I suppose this is closed
