### ISSUE TITLE
Dynamic external light from Legacy

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#361]
>like maybe that would be an option as dynamic lights are FPS intensive
> yep you're absolutely right there was a tardis_dynamiclight convar which controlled the dynamic light on the top of legacy

https://github.com/MattJeanes/TARDIS/blob/legacy/lua/entities/sent_tardis/cl_init.lua#L171-L186

**Comment by MattJeanes** [comment]
Done
