### ISSUE TITLE
Replace default interior with legacy

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#363]
We should change the default interior to legacy and add legacy materials/models into rewrite so that it isn't dependant
+ TODO: Make it compatible with legacy so that there aren't any duplicate files (I have a script for converting models)

Win has been working on default, but it's very far from being finished. When it is, we can revert it, or add it as another option. 
But having an untextured default when there is a textured and functional one is unreasonable.

**TODO** by Matt at #385 (duplicate):
* Remove current "default" interior + models
* Rename "legacy" interior to "default"
* Import models from legacy addon, and recompile the ones in legacy branch to name them as such

**Comment by parar020100** [comment]
Adding this to "Feature Parity" because having an interior and controls is definetely it

**Comment by MattJeanes** [comment]
This is now complete
