### ISSUE TITLE
Seperate 3D screen for scanner

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#365]
Will be useful for all TARDISes with several screens
Round screen in legacy/2010 is an example where it's needed

**Comment by parar020100** [comment]
This actually is feature parity related, since there was a scanner screen in legacy (round screen)

**Comment by AmyJeanes** [comment]
Done see #325 

New control `toggle_scanners` exists and this is how you can add them to an interior:

![image](https://user-images.githubusercontent.com/2363642/187090025-e6ccf230-35b6-46b6-acff-90d7b24bbea8.png)
