### ISSUE TITLE
Message (notifications / log / debug) system for all controls

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#367]
#30 asks a better way to show notifications to a player than chat messages, but until it's done, no messages exist at all.

We need to add a function like TARDIS:PrintMsg() for printing messages, and make messages for **all controls** into it
(with unified controls from #366)

For now, these messages will be in chat; after #30 is done, we'll just change print function PrintMsg() and won't have to change for all controls.

Also, it would be convenient to have a TARDIS:PrintDebug() for printing debug messages in the console.
They will be disabled by default, but enabled with tardis2_enable_debug command or similar

**Comment by Brundoob** [comment]
Ryan used the in game notifications for messages, such as power, you could upgrade all current notifications and future ones to use this system for a cleaner look
