### ISSUE TITLE
Random location travel

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#368]
This would be useable in many other issues, including HADS and advanced travel
I suggest a new control for it:
* We randomly check different points of the map to spawn the interior
* For a random destination, we do the same, but instead of choosing the highest available, we do "get to floor" for every found location ("get to floor" like R in destination select)
* Also, if TARDIS has travelled, it could randomly select out of previous locations

**Comment by Brundoob** [comment]
You could create an internal table of some sort to backlog the last 10-20 locations so it can pick one from random (ignoring duplications) and pick randomly between the previous destinations or the random destination as mentioned above
