### ISSUE TITLE
Random location in HADS

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#369]
Currently, the TARDIS just drifts away into vortex if attacked. Unless it is linked to a sonic, which a player may forget to do, the TARDIS is lost.

Suggestion: the TARDIS should travel to a random location instead (like in "Cold War")

**Comment by Brundoob** [comment]
If the TARDIS is trapped at any point in the vortex without a screwdriver linked and nobody inside, it should land at a saved/random location. This would also come into play with the HADS mechanic, preventing it from disappearing due to damage, eliminating the need to spawn a new one each time

**Comment by parar020100** [comment]
By @DJNEFFYFRESH from issue #531:
> Suggestion: If the sonic is not linked to the Tardis and HADS gets triggered the Tardis will land somewhere random.

> Alternative Suggestion: If the Tardis gets triggered by HADS and there is no sonic linked it will eventually land on you possibly giving you a chat warning. But if your sonic is linked It will still land at a random place or on a waypoint but your sonic might get a signal that you can track.

**Comment by parar020100** [comment]
## **References:**
sh_tp_main.lua
* line 62: function ENT:SetRandomDestination(grounded)

sh_hads.lua
* lines 33-34: the HADS activation itself

sh_tp_vortex.lua
* line 44: function ENT:AutoDemat(pos, ang, callback) used in sh_hads.lua
