### ISSUE TITLE
Implement my TARDIS E2 functions as native

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#37]
Things like remote commands were really useful, and I want to have something native for this.

**Comment by MattJeanes** [comment]
Original E2: https://gist.github.com/MattJeanes/c642afea526cbaab3d1b2f4d38d2c9e6

**Comment by parar020100** [comment]
Is there a list for those somewhere?

**Comment by MattJeanes** [comment]
I think that using the E2 for this is fine especially since it'll work in the rewrite now. It's not super lore friendly to just have chat commands and we want users to be able to customize it so E2 works best here I think.
