### ISSUE TITLE
Shields, health and repair improvements

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#371]
This would solve #62, and also maybe #60
I know that shields have been suggested before in #284, but this has a different system suggested, so it's easier to create a new issue than to update that one

**Shields:**
* Enabled by default
* Should be able to be disabled manually
* Shot/hit outside + shields on => health stays, shields--
* Shot/hit outside + shields off => health--
* Shot/hit inside => health-- not depending on shields
* From same consequences (shot/hit), health damage must be by several times more severe than shield damage
  * It's much easier to break TARDIS from the inside ("YOU SHOT MY TARDIS!!!")
* Shields = 0 => shields off
* Shields > 0, not under attack for some time => shields regenerating
* Shields on => you can't teleport into the TARDIS or materialise inside with other TARDISes

**Health system:**
* With shields protecting in most cases, low health could have much worse effects
* There will be four states depending on the health: ok, damaged, severely damaged, dead
* 

  | OK | Damaged | Severely damaged | Dead
-- | -- | -- | -- | --
Health | >40% | >20% | >0% | 0%
Example | Most episodes | Landing in "Christmas invasion", after the chase in "Runaway Bride" | "Eleventh hour" | "Rise of the Cybermen" + "Turn left" (parallel universe version)
Effects | None | Landing and flying with broken sounds | Red lights, cloister bell | No lights at all
Controls | All work | Small chance of controls not working with broken sound (have to flick 1-2 times) | Big chance of controls not working with broken sound (have to flick several times) | Controls don't react to anything
Teleport | As intended | Small chance of random location (#368), a bigger chance of shifting the landing location by a small random vector | Always random location (#368) | Doesn't work at all <br>               If died at vortex, falls out at random location (#368) without materialisation sound ("Rise of the Cybermen")
Flight | As intended | A bit violent, goes from side to side, sometimes mistakes right and left | Random direction change like legacy | Doesn't move
Physlock & anti-gravs | As intended | As intended | [difficulty (#372): easy] As intended, if controls work <br>[difficulty (#372): hard] Don't        work at all | Don't work at all
Self-repair | Can be turned on for redecorating | Can be done without exiting, if it is parked and on handbrake (#357)               Just needs some time | Needs exiting, like it works now | [difficulty (#372): easy] Needs exiting, like it works now <br> [difficulty (#372): hard] Unavailable
Screens | ok | ok | ok | [difficulty (#372): hard] disabled <br> [difficulty (#372): easy]: Accessible through 3rd person, off in the interior

**Comment by parar020100** [comment]
Also see #62 #40

**Comment by parar020100** [comment]
[ ] test

**Comment by PoogieTheGoose** [comment]
- [x] - Display
- [x] - Handle damage
- [x] - Shields passive regen
- [ ] - Instant regen control(artron --)

**Comment by PoogieTheGoose** [comment]
- [x] - Shields icon

**Comment by PoogieTheGoose** [comment]
- [x] - Different amount of shields setting

**Comment by PoogieTheGoose** [comment]
- [x] - Remained damage if shields level < dmg
