### ISSUE TITLE
Dematerialisation causes the exterior skin to switch from 0 to 1 temporarily

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#376]
I've heard this reported a few times, it's only a problem with exteriors with multiple skins - the 2005 tardis has been reported to show this issue as well as others. Need to look into what is causing it.

**Comment by francodml** [comment]
This might have to do with [this line](https://github.com/MattJeanes/TARDIS/blob/bbf3c1b2aac7c503379a6b2cf7ef1255c8522a2b/lua/entities/gmod_tardis/modules/sh_teleport.lua#L64). There are no mentions of setting skins in that file, so I'm guessing that's the most likely culprit.

**Comment by MattJeanes** [comment]
I agree, I couldn't find any other culprits personally - maybe there is a quirk of SetBodygroup which also ends up changing the skin somehow? Can we reproduce this bug at all on the 2005 tardis or any other interior? I wonder if it is a bug caused by an extension as well

**Comment by francodml** [comment]
> I wonder if it is a bug caused by an extension
I was thinking the same, since we don't explicitly change skins when we dematerialize anywhere.
Also, some exteriors have certain features as bodygroups instead of skins, which may cause this as well.

**Comment by MattJeanes** [comment]
The reason this exists is for an exterior specific feature on the default exterior to disable the black interior of the exterior shell designed for use when the portals are disabled but it made the demat look all weird. We should probably handle this in the interior file instead somehow.

**Comment by francodml** [comment]
Crimson Thunder#5721 on Discord:
> After rigorous testing I've discovered what addon is causing issue #376 on the git hub
It's dodo's DeLorean mod

I'll be checking this out when I have the time

**Comment by MattJeanes** [comment]
I would love to know how that causes this, maybe an override of the set colour or set bodygroup functions?

**Comment by francodml** [comment]
Could possibly be an incorrect hook on "SkinChanged". Although I can't see that hook on the GMod wiki. Is this something we've implemented somewhere? (Doors possibly?)

**Comment by Dodobro** [comment]
`ENT:AddHook("MatStart", "BTTF_Mat", function(self)
    for k,v in pairs(ents.FindInSphere(self:GetPos(),350)) do
        if ( IsValid(v)) then
            if v:GetModel("models/delorean_drivable.mdl") then
                v:SetSkin(1)
            end
        end
    end
end)`

This one was on me. The culprit was the 'easteregg' I added into my DeLorean addon. I incorrectly checked the model before setting it to change skin if a TARDIS was near-by. I've updated the addon and tested it with fixed code, and the problem no longer occurs.
