### ISSUE TITLE
ERROR while setting a destination without selecting one

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#377]
From gitlab by @CrethFox:

If a user tries to set a destination without having actually selected one an error is produced
[tardis-core-new_gui] addons/tardis-core-new_gui/lua/tardis/screens/sh_destination.lua:261: bad argument #1 to 'WriteVector' (Vector expected, got number)

WriteVector - [C]:-1
func - addons/tardis-core-new_gui/lua/tardis/screens/sh_destination.lua:261
3. SendMessage - addons/tardis-core-new_gui/lua/entities/gmod_tardis/modules/libraries/sh_message.lua:12
4. DoClick - addons/tardis-core-new_gui/lua/tardis/screens/sh_destination.lua:260
5. unknown - lua/vgui/dlabel.lua:237

Attempting to then set a viable location produces this:
[tardis-core-new_gui] Warning! A net message (TARDIS-MessageExt) is already started! Discarding in favor of the new message! (TARDIS-MessageExt)

SendMessage - addons/tardis-core-new_gui/lua/entities/gmod_tardis/modules/libraries/sh_message.lua:8
DoClick - addons/tardis-core-new_gui/lua/tardis/screens/sh_destination.lua:260
3. unknown - lua/vgui/dlabel.lua:237

This does not affect the TARDIS's ability to correctly demat and remat at the set location

**Comment by francodml** [comment]
Something is wrong with those traces, as lines 260 and 261 on the destinations screen are at the very end, and don't actually define any functions.

**Comment by parar020100** [comment]
Found the issue, when coords aren't set, pos equals 0 instead of nil
Fixed

**Comment by MattJeanes** [comment]
Fixed in #486
