### ISSUE TITLE
Manual light toggle

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#38]
Apparently useful for lighting up dark areas, though I'm not sure why they didn't just bring a torch? Not sure about this one yet.

**Comment by SingularMix** [comment]
This makes sense why it could be kinda useless. At the same time i understand how it just makes sense to have it. instead of it just being the normal tardis exterior flight light how about it gets really bright - as in way more powerful than a simple torch. That way it is worth turning on.

**Comment by Noname12345GER** [comment]
I was thinking if the Sonic could do that.

**Comment by MattJeanes** [comment]
Linked to #290 - think that would be nicer than this so closing in favour of that
