### ISSUE TITLE
Fix GUI rendering for big screens

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#384]
Currently, big 3D screens don't work on computers with low resolution - some elements are missing.
This is the reason it was impossible to implement a screen for 1983.

It happens because the 3D screens are rendered in the normal screen, and for big sizes, the render size is bigger than the actual screen.

**Comment by MattJeanes** [comment]
Fixed in https://github.com/MattJeanes/TARDIS/commit/ee6d9f7c255a0f4d1549591e2438c751cf1ab00e
