### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#39]
How is music gonna work in the new interior with no gramophone? It's a feature that I want to return - but I'm not sure how to implement it yet.

**Comment by AshtonBrigman** [comment]
Could use the monitors if you do have a GUI for them, have a music tab?

**Comment by MattJeanes** [comment]
Not a bad idea actually

**Comment by MattJeanes** [comment]
I also want custom music to be a thing, which is stored on the client too. It may also be possible to play files directly from the user's computer (as long as it's inside the gmod folder) using [sound.PlayFile](http://wiki.garrysmod.com/page/sound/PlayFile).

**Comment by techno156** [comment]
What about if you want to play custom music for everyone currently in the TARDIS, rather than just you?

**Comment by MattJeanes** [comment]
Will be possible, just as it is in legacy. Only the list will be clientside.

**Comment by Noname12345GER** [comment]
Would´nt it create network traffic ?

**Comment by MattJeanes** [comment]
Sorry might have caused confusion there. Custom as in custom links on the internet. Playing sounds from user computer would only work locally.

**Comment by MattJeanes** [comment]
Music is implemented but not currently networked, raised #322 for this
