### ISSUE TITLE
Default interior doorframe

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#398]
Currently the default (previously legacy) interior is missing it's door frame for reasons of portals, we should add it back because the floating portal in the doorway doesn't look too great

**Comment by parar020100** [comment]
Is this an easy thing to do? 
For example, if you have to remodel the whole thing or do something as complicated, I'd suggest you don't: with extensions present, default interior isn't often used except for testing

**Comment by MattJeanes** [comment]
Maybe as a quick win we can add it back without any collisions at all, need to look at the model. I think maybe you underestimate how many people use the default interior simply because they do not know there are others

**Comment by parar020100** [comment]
ok

**Comment by MattJeanes** [comment]
Fixed good enough in #487
