### ISSUE TITLE
If a TARDIS redecorates, all props from inside fall out somewhere in the world

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#407]

**Comment by MattJeanes** [comment]
Could make the cordon system in the Doors addon shared instead of clientside only as it currently is, which maintains a list of props inside the interior (for the purposes of making them invisible in the sky to other players) and use this list on removal to clear out the interior

**Comment by AmyJeanes** [comment]
Moved out of scope of the PR, now in https://github.com/MattJeanes/Doors/pull/26

**Comment by parar020100** [comment]
@MattJeanes this is resolved, isn't it?

**Comment by AmyJeanes** [comment]
Yep, Doors handles this as of https://github.com/MattJeanes/Doors/pull/27
