### ISSUE TITLE
Interior portals don't work in vortex

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#413]
if you demat in 2010, portals break

**Comment by MattJeanes** [comment]
Unable to reproduce, can you elaborate?
![image](https://user-images.githubusercontent.com/2363642/111543159-96ba3180-876a-11eb-9612-9181099f7901.png)

**Comment by MattJeanes** [comment]
Fixed in https://github.com/MattJeanes/Doors/commit/ab16ed37f62a423e109c19a8f1a0112aa44c5660
