### ISSUE TITLE
Add legacy/default helmic and atom accelerator rotating

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#418]

**Comment by parar020100** [comment]
On second thought, default/legacy interior is almost never used. 
Is this worth spending time on?

**Comment by MattJeanes** [comment]
As it's part of feature parity and pretty low effort I'd say it's worth doing. While a lot of people may end up using an extension, the first impressions of the main addon and default interior are important.

**Comment by AmyJeanes** [comment]
Done
