### ISSUE TITLE
Mat/Demat sounds aren't synced with the animation

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#419]

**Comment by parar020100** [comment]
Parameters suggested by Valentine:

> Teleport={
        SequenceSpeed=0.77,
        SequenceSpeedFast=0.935,
        DematSequence={
            175,
            230,
            100,
            150,
            50,
            100,
            0
        },
        MatSequence={
            100,
            50,
            150,
            100,
            200,
            150,
            255
        }
    }

**Comment by MattJeanes** [comment]
Duplicate of #414, is the actual sequence changed though? I have only updated the speed. If so maybe reopen linked issue with details
