### ISSUE TITLE
Map ambience can be heard inside the TARDIS

### ISSUE THREAD

**Issue by Brundoob** [MattJeanes/TARDIS#422]
on gm_construct you can hear birds tweeting from inside, there could potentially be a way to mute map sounds locally when it registers the player as inside a TARDIS

**Comment by MattJeanes** [comment]
As far as I'm aware it's not possible to at runtime override map ambience (soundscapes). It could be done for everyone I think at the start of the game with https://wiki.facepunch.com/gmod/sound.AddSoundOverrides but I don't think we can do it just while players are inside the TARDIS, but I will keep this open in case we discover or a method is added to GMod

**Comment by francodml** [comment]
If I recall correctly there should be console commands to disable soundscapes. We could use these to disable them while inside.

**Comment by francodml** [comment]
Those concommands are marked as cheats, so we can't use them in the end.

**Comment by MattJeanes** [comment]
Closing as I believe this is simply not possible but happy to re-open if we have any bright ideas

**Comment by AmyJeanes** [comment]
I've revisited this with @DoctorHugoSource and was able to get this working by using console commands from lua (only when sv_cheats is enabled though) but one big problem is that `cl_soundscape_flush` causes a lag spike, 0.135 seconds on my PC which is very annoying when leaving the TARDIS and breaks the bigger on the inside illusion.

Currently unable to find a workaround to determine the correct map soundscape to play or reset it without lag spiking, so unless we can find a solution to this we still can't do this, as the lag spike is unacceptable.

```lua
-- lua\entities\gmod_tardis_interior\modules\cl_soundscape.lua

-- Soundscape

ENT:AddHook("Initialize", "soundscape", function(self)
    self.cheats = GetConVar("sv_cheats")
end)

ENT:AddHook("PlayerEnter", "soundscape", function(self)
    if not self.cheats:GetBool() then return end
    RunConsoleCommand("playsoundscape", "Nothing")
end)

ENT:AddHook("PlayerExit", "soundscape", function(self)
    if not self.cheats:GetBool() then return end
    RunConsoleCommand("cl_soundscape_flush")
end)
```
