### ISSUE TITLE
TARDIS in vortex can interact with outside world

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#424]
When in vortex, TARDIS can still interact** with the outside world. For example, you can place dynamite at a place where it was when it dematerialised, and kill the TARDIS in vortex. 
Vortex is spawned at the spot where TARDIS dematerialised. The easiest way to solve the issue is change that, I suggest we spawn the vortex at the top of the map, using an algorythm we have for interior spawning.

**Comment by francodml** [comment]
Easiest way to fix this is to disable exterior damage when in vortex.

**Comment by MattJeanes** [comment]
Agree with @francodml, don't think we should change the demat position as it can cause a lot more problems than it may solve

**Comment by MattJeanes** [comment]
Closing as part of #430 but there is a follow up bug with #447
