### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by judo-jay** [MattJeanes/TARDIS#428]
hi was playing with the new update and for some reason some buttons don't work and it just comes up with that the Tardis addon is creating errors ,I didn't know if that was for everyone or just me. could you have a look as its an amazing addon to play with

**Comment by MattJeanes** [comment]
Hi there, as far as I'm aware the addon itself is functioning no problem. Could you try these steps to help debug the issue?

* How many addons do you have installed? If you have a lot of addons GMod doesn't like it and starts breaking down
* Disable every addon except TARDIS and Doors and see if your issue persists, if it does - you either have to many addons or something is conflicting with the TARDIS. If it's still broken please open the GMod console and copy paste the errors here
* Try re-enabling your other addons again to see if it works, sometimes this just works

**Comment by judo-jay** [comment]
yeah i had to many of the same tardis going but all working now, keep up with the great work i love this

**Comment by MattJeanes** [comment]
Fantastic
