### ISSUE TITLE
Default visGUI theme elements for each interior

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#437]
Interior makers should have the opportunity to set default elements for GUI, like background or frame styles

**Comment by parar020100** [comment]
I don't think interiors should choose one of the existing themes, because that wouldn't allow customizations at all.
Instead, there should be elements selected for this interior specifically, with all others set by the theme chosen by user.
It should be possible to toggle (turn off) interior-specific elements as well.

**Comment by parar020100** [comment]
I've been planning to do this, but I don't think I want to spend time on it now.
The GUI isn't supposed to be such an important part of the experience to customize too much.

**Comment by MattJeanes** [comment]
Yeah happy to close if you are @parar020100

**Comment by parar020100** [comment]
Reopening since this has been requested a lot

**Comment by parar020100** [comment]
From Divided in #705:
> Themes should have a default setting which just means interior preference, the preference will still be the default screen as it is today but it means that if a user hasn't explicitly changed the theme it will default to whatever that interior wants.
> 
> Basically exactly like how tips work

**Comment by parar020100** [comment]
Done in #821
