### ISSUE TITLE
"Custom" visGUI theme 

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#438]
It would be nice to have a theme setting that allows user to choose, which theme to take each element from. The way I see it is we could add a seperate tab in the settings with lists for each theme

**Comment by parar020100** [comment]
I've been planning to do this, but I don't think I want to spend time on it now.
The GUI isn't supposed to be such an important part of the experience to customize too much.

**Comment by MattJeanes** [comment]
Agreed, happy to close if you want to @parar020100
