### ISSUE TITLE
Improved passive interior lighting (round things)

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#44]
Try to get all the lights around the top floor working using the sprites (vcmod/photon etc)

**Comment by MattJeanes** [comment]
They should also change colour and do special effects to show danger for example, if possible.

**Comment by Noname12345GER** [comment]
Links with #188

**Comment by Noname12345GER** [comment]
Are you able to make Sprites only visible to the passengers?

**Comment by MattJeanes** [comment]
They already are

**Comment by AmyJeanes** [comment]
No longer relevant as the default interior has changed
