### ISSUE TITLE
Remove the old UI (main screen, virtual console)

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#440]
Creating the issue for discussion, not sure myself

**Comment by MattJeanes** [comment]
The main reason I wanted to keep it about for a little bit was as a fallback for if there were any big issues, but I'm pretty happy with how it's all working so I'd say get rid of it.

**Comment by FuzzyLeo** [comment]
wanna add that the new ui crashes the game for macs so removing it would only make things worse imo

**Comment by parar020100** [comment]
Since it doesn't work for macs, not sure whether it should be removed completely
