### ISSUE TITLE
Make TARDIS GUI openable in context menu ("C")

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#444]
Perhaps we could get rid of the "open interface" button in options part of spawnmenu, if we add this, finish #436 and add the "pin" button to the context menu for keeping the popup

**Comment by MattJeanes** [comment]
We would need to move settings fully out to the spawnmenu options first to do this

**Comment by parar020100** [comment]
Do we? If it's still openable from context menu.
But I wouldn't get rid of "open interface" button yet before 436, but the main thing in this issue is doable

**Comment by MattJeanes** [comment]
Fixed in #486
