### ISSUE TITLE
Allowing classic style doors to be possible

### ISSUE THREAD

**Issue by FuzzyLeo** [MattJeanes/TARDIS#448]
In the show the only 'canonical' appearance of the view through the classic doors has shown us that the police box doors are completely absent from the interior, now no matter how much anyone may dislike this, its how it is in both the classic and reboot of the show and therefore should at least be a possibility for those who _do_ want it.

Pictures from the show:
![image](https://user-images.githubusercontent.com/23579757/112070011-cac79500-8b64-11eb-9241-cb073ac92dbf.png)
![image](https://user-images.githubusercontent.com/23579757/112070026-d1560c80-8b64-11eb-887b-9ed83fd426e2.png)
![image](https://user-images.githubusercontent.com/23579757/112070046-d915b100-8b64-11eb-87d3-3900147a2cab.png)
![image](https://user-images.githubusercontent.com/23579757/112070182-19752f00-8b65-11eb-87db-1b6e709e0466.png)

The most plausable way it could be done from the interior is when you're inside the interior it would make the exterior invisible, producing an effect like this (assuming the portal has been adusted in the rewrites code):
![image](https://user-images.githubusercontent.com/23579757/112070491-aa4c0a80-8b65-11eb-8aa1-6759b6dff478.png)

and from the exterior it would be done by allowing the exterior doors to render on top of the portal (which also solves the issue of the portal seam being visible), which would look something like this:
![image](https://user-images.githubusercontent.com/23579757/112071321-6823c880-8b67-11eb-9015-ca3982c4861d.png)
![image](https://user-images.githubusercontent.com/23579757/112071338-72de5d80-8b67-11eb-9342-cc976ae5e563.png)

These two methods combined would make it possible for classic style doors to be created with the added benifit of making the portal a huge amount less noticable.

**Comment by parar020100** [comment]
Are different-sized portals already supported?

**Comment by francodml** [comment]
Should be. We just need to tweak some rendering code.

**Comment by MattJeanes** [comment]
@parar020100 yes they are, you just set different sizes in exterior vs interior in the metadata - the tricky bit is rendering a door over the portal

**Comment by MattJeanes** [comment]
@francodml how you feeling about this one? I'm happy to close if you're not working on this one

**Comment by francodml** [comment]
> @francodml how you feeling about this one? I'm happy to close if you're not working on this one

I'm not currently working on this due to time constraints on my end. I might start looking into it once I'm free in a few weeks.

**Comment by parar020100** [comment]
Internal doors should  not be openable by hand; they need to open at start or be openable by sonic
