### ISSUE TITLE
3D2D screens

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#47]
Need to implement interactivity and menus and things.

Use: https://github.com/HandsomeMatt/3d2d-vgui

**Comment by AshtonBrigman** [comment]
That would seriously look interesting if you were to go to the gui and do stuff I dunno! My point is that would be cool if you could do something with this like in secondlife if you have ever looked at the tardises in that game, they all have 3D indicators telling you which control is which and such. As well as that it could function in ways I dunno yet!

**Comment by MattJeanes** [comment]
Fixed in https://github.com/MattJeanes/TARDIS/commit/f6a03b10d0babb7128aecf20a752091acbe83685
