### ISSUE TITLE
tardis interior not working

### ISSUE THREAD

**Issue by epichowlon** [MattJeanes/TARDIS#474]
the interior look like it was put in a blender and i have no idea how to fix it. please help

**Comment by MattJeanes** [comment]
Can you show some screenshots / video of the issue?

**Comment by epichowlon** [comment]
> Can you show some screenshots / video of the issue?

![20210429104723_1](https://user-images.githubusercontent.com/83416908/116579974-8c966180-a8d8-11eb-8ea5-772447b7b71f.jpg)
![20210429104740_1](https://user-images.githubusercontent.com/83416908/116580005-94560600-a8d8-11eb-9425-30dacdbdee3b.jpg)

**Comment by MattJeanes** [comment]
Wow that is quite something! Can you check your model / texture quality settings and try setting them to the highest to see if that fixes it? You might need to reboot your game after to see the effects.

**Comment by epichowlon** [comment]
> Wow that is quite something! Can you check your model / texture quality settings and try setting them to the highest to see if that fixes it? You might need to reboot your game after to see the effects.

wow that worked i up both texture and model detail and it fixed it. thank you

**Comment by MattJeanes** [comment]
Great to know, you can probably get away with changing texture detail back down if you're running low on frames, but I think model detail needs to be on high otherwise various models just completely freak out - it is super strange! Glad I could help
