### ISSUE TITLE
2013/Default Tardis can't get out of vortex

### ISSUE THREAD

**Issue by DrERRORz** [MattJeanes/TARDIS#476]
Once I pull the lever and I'm fully in the vortex, it won't go out of the vortex by pulling the lever. (There is no con log)

**Comment by parar020100** [comment]
Hello
Sorry for the late reply
Try to update this addon to the latest version and disable other addons
Please tell me the whether the problem still happens

**Comment by parar020100** [comment]
I'm closing this issue due to the lack of response
If you come back and the problem still happens, feel free to reopen - we'll be happy to help
