### ISSUE TITLE
Self Repair doesn't work on multiplayer

### ISSUE THREAD

**Issue by NovaAstral** [MattJeanes/TARDIS#477]
Like the title says, Self Repair doesn't work in multiplayer, I've tried in both P2P and Dedicated and it doesn't work on either (I've tried with both the E2 function and the actual lever)

**Comment by parar020100** [comment]
Hello
Sorry for the late reply
Does it still happen? Could you check whether it happens if you disable all other addons?

**Comment by parar020100** [comment]
I'm closing this issue due to the lack of response
I failed to reproduce the problem
If you come back and the problem still happens, feel free to reopen - we'll be happy to help
