### ISSUE TITLE
When entering flight mode by pressing 'E' on the console, you cannot see the TARDIS exterior

### ISSUE THREAD

**Issue by SFMPlayz** [MattJeanes/TARDIS#478]
Whenever I enter a TARDIS, being an extension or the actual TARDIS itself. If i press 'E' on the console to enter flight mode. I cannot see the TARDIS exterior. Only the inside of my player model in a random part of the map, presumably the area that the TARDIS interior has been placed. Linked below is a video I recorded of this happening with 3 different TARDISes
https://youtu.be/ZiFaznIKCJA

**Comment by parar020100** [comment]
Hello
Sorry for the late reply
Also, does it happen on all maps or some specific ones?
Try to update this addon to the latest version and disable other addons
Please tell me the whether the problem still happens

**Comment by SFMPlayz** [comment]
Hi

Thanks for getting back to me
I figured out the issue, it was conflicting with other addons I had
installed.
Maybe a goal would be to aim for better compatibility with other mods?
Love the mod
Thanks

**Comment by parar020100** [comment]
> Maybe a goal would be to aim for better compatibility with other mods?
Depends
Some things can not be done due to engine limitations
Which addons did the TARDIS conflict with?
