### ISSUE TITLE
The tardis being damaged by me shooting out of the door portal

### ISSUE THREAD

**Issue by Terminusmaximus** [MattJeanes/TARDIS#479]
When i shoot out of the portal the tardis is damaged even though i am shooting the door portal and not the actual tardis or console which makes shooting out the portal a useless feature since you are probably gonna destroy your tardis before you will kill the person.

**Comment by MattJeanes** [comment]
What gun are you using? There are overrides that should work with most things but there are probably some incompatibilities. Normal built in guns like the SMG should work - can you try that? Also make sure you're running the latest version of world-portals in particular if not using workshop.

**Comment by Terminusmaximus** [comment]
I used hl2 gun and they still do the exact same things such as the pistol

**Comment by Terminusmaximus** [comment]
and i am using the latest doors addon because i reinstalled it afew days ago

**Comment by Terminusmaximus** [comment]
After a bit more testing it seems to the distance at which at shoot the at the portal and the point i shoot at

**Comment by Terminusmaximus** [comment]
Sometimes the bullets dont pass the through the portal and hit the outside instead hitting the actual portal which makes the tardis get damaged

**Comment by Terminusmaximus** [comment]
At a certain point while i move my mouse upwards and shoot the bullets stop going through the portal and instead hit it like shoot the tardis interior normally which makes it damage it.

**Comment by MattJeanes** [comment]
What interior are you using? Some interiors may not work super well with it - see how the default one works shouldn't really have any issues.

**Comment by Terminusmaximus** [comment]
I used the default one and it still has the same problem

**Comment by Terminusmaximus** [comment]
Do you think the map may also cause a problem with the portal

**Comment by MattJeanes** [comment]
Map shouldn't cause any problems - do you have similar issues shooting from the outside to the inside? Try putting a prop on the inside you can shoot at and see if any of the bullets do damage to the TARDIS itself or not

**Comment by Terminusmaximus** [comment]
Ok i checked and the interior port works perfectly fine

**Comment by Terminusmaximus** [comment]
All my shots hit the prop without daming the tardis

**Comment by Terminusmaximus** [comment]
its just shooting things from the inside of the tardis portal, the outside portal works perfectly

**Comment by parar020100** [comment]
Moving this issue to #940
