### ISSUE TITLE
Fix interior being unfreezable

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#48]
[GM:PlayerUnfrozeObject](http://wiki.garrysmod.com/page/GM/PlayerUnfrozeObject)

You can apparently return true/false to stop it unfreezing, but unconfirmed.

**Comment by AshtonBrigman** [comment]
I have another method for doing this but I have to go dig it up from my tardis addon real fast...

**Comment by AshtonBrigman** [comment]
Actually this was your old method in the legacy but this is a snippet of it 
function ENT:Initialize()
	self.phys = self:GetPhysicsObject()
	if (self.phys:IsValid()) then
		self.phys:EnableMotion(false)
	end	
end

**Comment by MattJeanes** [comment]
That only applies when it's spawned.

**Comment by MattJeanes** [comment]
Fixed in https://github.com/MattJeanes/TARDIS/commit/f6a03b10d0babb7128aecf20a752091acbe83685
