### ISSUE TITLE
Tardis interior lighting not working 

### ISSUE THREAD

**Issue by judojay2003** [MattJeanes/TARDIS#480]
every time i want to do the power in the tardis it always says there is a error not sure why?? please let me know a way to fix it as i love what you have created

![2021-10-10](https://user-images.githubusercontent.com/92273289/136711040-2c79c67b-5916-4021-8d30-754193f0dba8.png)

**Comment by parar020100** [comment]
Hi
Sorry for the delay
Could you please update the addon and see whether the error still happens?

**Comment by parar020100** [comment]
I'm closing this issue due to the lack of response
If you come back and the problem still happens, feel free to reopen - I'll be happy to help
