### ISSUE TITLE
Reduce flight speed with opened doors

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#485]
I think this would improve the gameplay
As we know from "The Runaway Bride", the TARDIS isn't very good at flying with open doors

**Comment by Brundoob** [comment]
I don't think it's a case of it being hard to fly with doors open, as much as it was trying to fly it from the doorway instead of the control panel. The 12th Doctor and Clara were mapping out london and he was flying with no trouble with open doors

**Comment by MattJeanes** [comment]
Maybe if the doors are open we should automatically disable spinning at least, that might be a good tweak to make

**Comment by parar020100** [comment]
> I don't think it's a case of it being hard to fly with doors open, as much as it was trying to fly it from the doorway instead of the control panel. The 12th Doctor and Clara were mapping out london and he was flying with no trouble with open doors

12 and Clara were flying very very slowly

**Comment by parar020100** [comment]
As for flying from the doorway... it relates to #374, I'll think of a way to do both
