### ISSUE TITLE
Cloak effect

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#49]
How is this gonna work in the rewrite, if at all?

**Comment by AshtonBrigman** [comment]
Completely de-render the portal on the outside of the tardis before cloak effect happens?

**Comment by MattJeanes** [comment]
I don't need technical details - I know all that, I'm thinking logic

**Comment by SingularMix** [comment]
If the doors are open just have the portal stay visible but the exterior police box turns invisible. Thats how it looked in the show the few times it turned invisible with doors open. Then if the doors are closed just make everything invsible.

**Comment by SingularMix** [comment]
You could also make it so if something makes contact with invisible TARDIS then you can barely see an outline of it.

**Comment by Noname12345GER** [comment]
Im agreeing with @SingularMix . I would also make an option if a de-cloak will play the phase sound but reversed ?

**Comment by parar020100** [comment]
I suppose this is done now
