### ISSUE TITLE
TARDIS Light States

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#492]
We can add two dynamic lights to the TARDIS
But many people wish that those lights could be changed
There are currently three light states - normal, health-warning and turned off, but even for those people even make different part textures

I'm proposing we add a new light system, where we can specify them somehow like this:
LightProfiles = {
  profile1 = {
    normal = { lights = {...}, textures = {...} } ,
    warning-state = {...},
    off = {...},
  profile2 = {...},
...
}
 etc.

Each light state in each profile would specify a list of lights used, as well as list of part textures which change

It should be possible to switch between the light states with controls, individually for each TARDIS

**Comment by MattJeanes** [comment]
I think as long as there is a fallback system to the original then this sounds good to me

**Comment by parar020100** [comment]
If done, #373 would be closed

**Comment by parar020100** [comment]
Done in #720
