### ISSUE TITLE
onControlToggled hook

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#498]
We're aiming towards a unified control system with the use of TARDIS:Control()
Such hook will be useful, for example, for toggling levers while GUI controls are used

**Comment by MattJeanes** [comment]
Yeah syncing levers etc when controlled via other methods e.g. E2 / pilot controls is something I've wanted for a while

**Comment by parar020100** [comment]
I forgot this has already been added
`TARDIS:Control()`  ends with:
`ext:CallHook("TardisControlUsed", control_id, ply)`
`int:CallHook("TardisControlUsed", control_id, ply)`
