### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#499]
It has been asked several times to make possible translations to other languages
I thought it is worth creating an issue for this anyway

**Comment by MattJeanes** [comment]
We can certainly do this, it's just a case of whether it's worth the effort and also we need people fluent in both English and the target language to provide translations, something I am definitely not :)

**Comment by parar020100** [comment]
Another problem this would solve is people not liking the texts
Someone was refusing to add TARDIS:Conrol() to their extensions because they didn't like "vortex flight" instead of "long flight"...
I don't like that, but this would make everyone happy

**Comment by parar020100** [comment]
@MattJeanes I believe this should be closed

**Comment by AmyJeanes** [comment]
Will be closed on release

**Comment by AmyJeanes** [comment]
This isn't actually quite completed yet so holding this open

**Comment by MattJeanes** [comment]
Translation files are in so closing

**Comment by AmyJeanes** [comment]
This is now done
