### ISSUE TITLE
TARDIS ErrorMessage with type 2

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#503]
Currently, error messages are only different from normal ones in type 3
We should add an [ERROR] prefix or something

![изображение](https://user-images.githubusercontent.com/32988384/141681563-728e40b8-b43d-42b3-8dd1-0537bb86db91.png)

![изображение](https://user-images.githubusercontent.com/32988384/141681588-d356bc36-01e3-44ba-93b0-b3d4260b87e5.png)

**Comment by MattJeanes** [comment]
Fixed
