### ISSUE TITLE
Default interior door gap

### ISSUE THREAD

**Issue by thedoctor1415** [MattJeanes/TARDIS#508]
![image](https://user-images.githubusercontent.com/21987457/141830205-8f0f4daa-84a6-4d5c-9d52-2bfd54d933d3.png)
There is a clear gap under the door, between the portal and the floor

**Comment by MattJeanes** [comment]
This is a known issue but moving it lower would break player collisions, so maybe we can have something fake there instead with no collisions just to pad out the space

**Comment by parar020100** [comment]
Fixed
