### ISSUE TITLE
NPCs have no collision with the TARDIS exterior

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#511]
Reported by Cheaple on Discord - might just be how NPCs are as their collisions are very weird - need to review.

**Comment by parar020100** [comment]
From @CrethFox:

> its a gmod thing: from what it seems NPCs work weirdly with the physgun 
when pulling npcs around it seems they can be phased through and into literally anything that isn't map environment, the Tardis included
Cars, boxes, health balls and even other people

> though depending on what it is sometimes they automatically push away to become unstuck inside each other, sometimes they just remain

> in the Tardis's case technically its a hollow object so npcs just sit inside the box because theres no matter being displaced so to speak; but outside of the physgun it seems to work normally

> 
![изображение](https://user-images.githubusercontent.com/32988384/150129316-6764b75c-c31f-443a-9e9a-1bc36307002f.png)

**Comment by parar020100** [comment]
@MattJeanes do you think this one can be closed?

**Comment by AmyJeanes** [comment]
Yeah don't think we can fix this
