### ISSUE TITLE
PART.SoundPos parameter

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#523]
This is required for parts which are far from the center, but need sounds

Example: 2010 interior doors

**Comment by MattJeanes** [comment]
This should be possible to calculate from the collision mesh in most cases, I imagine this is for parts where they spawn at 0,0,0 but their model offset puts them in the right place in the interior. Would be nice to not have to manually specify positions if possible, but this still might be a good idea anyway for more fine-tuned control when required.

**Comment by parar020100** [comment]
@MattJeanes collision mesh won't calculate anything when a part is located in opposite corners of the interior

2010 has portals triggered by the doors, and the doors at both sides of the portals are the same part

**Comment by MattJeanes** [comment]
Yeah it won't work for all cases like that example, but should work for most

**Comment by parar020100** [comment]
I think that in most cases, sound-producing parts are controls and having them at (0,0,0) is okay
Sound-making parts far from the console are rare, it wouldn't be an issue to specify coordinates for them
I don't think bothering with collisions is required

**Comment by MattJeanes** [comment]
Okay sounds good
