### ISSUE TITLE
Better in-flight HUD

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#53]
Again I want something more in-universe for this.

**Comment by TheDetecttive** [comment]
If you've heard of the Doctor Who Client mod, for Minecraft, you could do a HUD similar to that, where it looks like your staring through the TARDIS scanner with some spinning Gallifreyan text all 'round.

**Comment by Noname12345GER** [comment]
Should be able to turn it off.
Heavy Support for Extension developers.

**Comment by Noname12345GER** [comment]
Ability to move hud Elements is essential for DarkRP as legacy got overlayed by health.

**Comment by MattJeanes** [comment]
Yep, the hud would be extensible or modifiable by extension devs

**Comment by MattJeanes** [comment]
Don't think we need to bother with this really, works fine as is
