### ISSUE TITLE
Redecoration improvements

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#530]
**1. Enable self-repair instantly when redecoration is enabled**
Too many clicks are confusing and annoying

**2. Random interior if one isn't selected**
Since we have a special redecoration toggle control, it should do something even if the interior is not selected
It should be optional, but I suggest that if the new interior is not specified, redecoration should choose one randomly

**3. A help message telling how to select an interior (in spawnmenu)**

**Comment by MattJeanes** [comment]
Released
