### ISSUE TITLE
Fall out at a random place after undo-ing TARDIS in vortex

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#533]
Currently, when you just get back to the last position of the TARDIS, it's cheaty and game-breaking (allows to return back quickly)

Falling out at a random place would fix that

**Comment by parar020100** [comment]
I'd say it's a way to quickly return back after flying away

**Comment by francodml** [comment]
Fair enough. Perhaps leaving the player in a random spot along the way to their current destination from the point of departure, or a random spawn point if there's no destination set (safer than random positions, could end up inside a wall if we don't account for that)
