### ISSUE TITLE
Visual time vortex

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#54]
I experimented with this back in the legacy, but it never really took off at all. I'd like to see it done properly here.

**Comment by MattJeanes** [comment]
![image](https://cloud.githubusercontent.com/assets/2363642/18042002/d0947862-6db5-11e6-98fb-3738489bde83.png)

**Comment by benrob0329** [comment]
**claps**

**Comment by benrob0329** [comment]
It doesn't quite look right with the bit of space in the middle though, perhaps there could just be a double cone per vortex type?

**Comment by MattJeanes** [comment]
The models used are from the [Time Vortex Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=673981855) workshop addon, I'd pop over there to ask for improvements.

Anyway this is now feature complete and tested, but I can't get it rendering over everything else so if part of the world is in the cone you will still see it. It's not a breaking feature though and everything can be turned off to work just like before with a nice client option so release is fine with this.

**Comment by kennyrkun** [comment]
would it possible/viable to have the TARDIS teleport somewhere that isn't near anything once it's fully dematerialized, then teleport it back once you rematerialize?

**Comment by Noname12345GER** [comment]
You mean like an actual place where the TARDIS goes for vortex?

**Comment by kennyrkun** [comment]
Yes, could be the top of the map or something. If there is a way to detect objects, have the TARDIS find the area with the least within a certain radius and teleport there.

**Comment by Noname12345GER** [comment]
I'd like to refer to the demat in the series;

The TARDIS will cloak, fly upward and then dematts away from planets.

**Comment by Noname12345GER** [comment]
*celebratin'*

**Comment by thehornydragon** [comment]
I know the issue is already fixed for the next update, but for some reason the Vortex overlapping the map already worked in this particular TRON map, I've uploaded a video here: [https://youtu.be/_L9nfjHcBp4](url)

**Comment by MattJeanes** [comment]
Interesting, maybe the world was rendered differently on that map. No idea - but yeah it's already fixed for every map as you say but cool to know.

**Comment by thehornydragon** [comment]
To add one more thing to it, it seems that the Vortex only overlaps the floor of the map. It doesn't work for the glass "zone" surrounding it, you can still see that while inside the Vortex.
