### ISSUE TITLE
TARDIS doesn't work in world saves and dupes

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#542]
Not sure whether this is fixable, but I'll leave it here

**Comment by francodml** [comment]
It might just work if we modify the way gmod tries to serialise the entity to only keep the important details (health, current interior, etc), and essentially just respawn the TARDIS and set the appropriate values on load

**Comment by MattJeanes** [comment]
Yeah there are hooks to help with this, it will likely have the side effect of fixing it for the duplicator as well

**Comment by Garth1002** [comment]
*suggestion* 
I haven't got a problem with the tardis not being in the save, but even there could be a fix/option to save the options I have selected (like preferences on the tardis skin & favouriting the ones I want the most for redecoration), like even that as just a work around would be nice, just being able to just need to respawn the tardis & not have to redo the settings every time.. Sorry if this is a no go also, but just thought I'd throw it in as an optional work around to make it less annoying I guess
