### ISSUE TITLE
Random Location Terrain Issue

### ISSUE THREAD

**Issue by CrethFox** [MattJeanes/TARDIS#547]
When using Random Location (ground) Destination travel on maps with terrain such as hills and cliffs, often it is possible for the Tardis to land on these inclines, however it does not snap to them and results in the Tardis falling, resulting in damage depending on the fall
![Tardis](https://user-images.githubusercontent.com/79445896/144027347-c5c967e3-5639-4cdc-a58d-1ab2048023bf.png)
.
![Tardis 2](https://user-images.githubusercontent.com/79445896/144027371-a4f70d77-a148-4d87-bf2f-5f50b4259620.png)

**Comment by francodml** [comment]
It might be possible to include traces to find an appropriate rotation for random destinations. Snap to Floor (R on dest select) would benefit too.

**Comment by MattJeanes** [comment]
We can defo fix this for the most part, if its extremely uneven terrain might still not work but can certainly account for ramps and things, the trace will come with a hit angle, we actually do this when teleporting with the sonic already I believe
