### ISSUE TITLE
TARDIS can be locked and unlocked by any player from outside

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#552]
It basically ruins the point of locking if anyone can open it back with the sonic

**Comment by MattJeanes** [comment]
Prop protection rules apply here (specifically if a player can use the toolgun on the TARDIS) so in a multiplayer scenario this should work fine, I'm not sure what you have in mind to improve this?

**Comment by francodml** [comment]
Maybe letting the lock respect isomorphic or the planned "companions/friends list" thing

**Comment by parar020100** [comment]
Should be fixed in the sonic addon
It doesn't allow to open the TARDIS when Isomorphic Security is enabled
