### ISSUE TITLE
A different centre for counting the interior exit distance

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#555]
I'm not sure how this works, but I don't think it's supported
Basically, there are non-symmetrical interiors, where the centre of the whole thing is far from (0,0,0)

Hell bent is an example

In order to reduce the interior size, we should make possible ot have that centre at a different position

**Comment by MattJeanes** [comment]
This would likely end up being a change in the Doors addon but don't see why not to add this
