### ISSUE TITLE
Full legacy mode

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#556]
People still miss the legacies and think that some things used to be better in them. Others don't like the black portals while computers aren't strong enough to render the normal ones.
Some just like the old mechanics.

We should add a legacy mode, in which "e" just teleports into the TARDIS.

**Comment by MattJeanes** [comment]
You can just press Alt+E to enter or exit via teleport, I'm not sure we need to do anything beyond this?
