### ISSUE TITLE
A native way of 'flight tracking' from inside the TARDIS

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#56]
Maybe in the GUI? Legacy requires sonic or E2 to do it, so I want a native method.

**Comment by Noname12345GER** [comment]
Selecting players and Props thru the Screen´s top view

**Comment by MattJeanes** [comment]
To be fair that's not a bad idea, if I add a 3D view which you can also use for teleporting, you could just point at a prop and lock to it.

**Comment by Noname12345GER** [comment]
It would be nice to see some additional Info if you point in something with the screen like:

Health
Player Name
Model
Coordinates
A compass (such an XYZ-Cross)

**Comment by theangelcastiel** [comment]
Could we make it so you can choose an object to track the same way you choose where to teleport in 3rd person?
