### ISSUE TITLE
Console error after repair

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#577]
[TARDIS] lua/entities/gmod_tardis/modules/sh_health.lua:163: attempt to index local 'ent' (a nil value)
1. FinishRepair - lua/entities/gmod_tardis/modules/sh_health.lua:163
   2. v - lua/entities/gmod_tardis/modules/sh_health.lua:288
    3. CallHook - lua/entities/gmod_tardis/shared.lua:58
     4. unknown - lua/entities/gmod_door_exterior/init.lua:85

Conditions: unsure

**Comment by parar020100** [comment]
I believe this was fixed in commit a98fba9907376b9a8d96a8b8db8b6562fb45d878 + Doors addon (PR #22, commit 9d9823851308352d72e93e254490eca77b65b224)

**Comment by MattJeanes** [comment]
Fix released
