### ISSUE TITLE
Geting error when trying to spawn tardis with RDV requisition

### ISSUE THREAD

**Issue by KyberNetworks** [MattJeanes/TARDIS#590]
it spawns it but the tardis is inviable and when you click it you get this error 
 
[TARDIS] lua/entities/gmod_tardis/modules/sh_doors.lua:209: attempt to index field 'metadata' (a nil value)
  1. v - lua/entities/gmod_tardis/modules/sh_doors.lua:209
   2. CallHook - lua/entities/gmod_tardis/shared.lua:64
    3. unknown - lua/entities/gmod_tardis/modules/sh_doors.lua:205
     4. func - lua/entities/gmod_tardis/modules/libraries/sh_message.lua:34
      5. unknown - lua/includes/extensions/net.lua:33 (x2)

**Comment by MattJeanes** [comment]
What is RDV Requestion? Spawning the TARDIS outside the spawn menu is not supported at this time due to the complex nature of the addon

**Comment by KyberNetworks** [comment]
Thanks for the fast reply

**Comment by KyberNetworks** [comment]
> What is RDV Requestion? Spawning the TARDIS outside the spawn menu is not supported at this time due to the complex nature of the addon

This video explains what it is https://www.youtube.com/watch?v=8ERbwIEWnUg

**Comment by MattJeanes** [comment]
Ah okay, the author of that addon will need to add compatibility to spawn in the TARDIS if they want that to possible, and there isn't really much I can do about it myself. Hope that helps.
