### ISSUE TITLE
Change "third person" keys: "Alt+E" instead of "E" (on the console)

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#596]
This is a solution to #184 which seems to be simple enough, so I'll close that one

* alt+E on the console => third person
* E on the console => a notification message telling to use alt to open third person 
* an option to disable this; from @MattJeanes:
  > i think if it comes with an option to revert to normal behaviour that should be fine
i can see people moaning about it

**Comment by AmyJeanes** [comment]
Note that Alt in this context is the WALK key, which is usually bound to Alt but not always

**Comment by parar020100** [comment]
Fixed in #605
