### ISSUE TITLE
Security systems

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#60]
There needs to be a way of stopping people getting in without permission. Maybe a whitelist/blacklist option and a player selection thing? Admins will be able to bypass it though.

**Comment by sonicspeed9903** [comment]
could we have a tick-box to enable whitelists/blacklists and then you type peoples usernames down in a list EG: bob123 and now bob123 wont be able to access the tardis (I am basicly saying that we could have it as a menu / list configuration)

**Comment by MattJeanes** [comment]
I am planning sort of menu similar to what you described but I can't let you type in a players name because they can change. I could let you input a steamid though.

**Comment by SingularMix** [comment]
How 'bout if you are not on whitelist then you could be set on fire or something if you step in the TARDIS XD

**Comment by Noname12345GER** [comment]
What about the TARDIS will Blacklist ewery player,so you can allow users to enter if you "tag" them with the Sonic Screwdriver because no function is sharing interacting with players.

**Comment by MattJeanes** [comment]
I think this is an important addition especially now that people can teleport to you and be brought inside the tardis since the latest update. I'll probably go with what I said before about a simple menu with checkboxes allowing you to specifically allow or deny certain players. List would be clientside so would move across servers.

**Comment by Noname12345GER** [comment]
I would strongly prefer a whitelist

**Comment by MattJeanes** [comment]
You would be able to choose.

**Comment by Noname12345GER** [comment]
Will this thread include the Isomorph?

**Comment by MattJeanes** [comment]
Yes

**Comment by Noname12345GER** [comment]
What about making the Whitelist apply to the iso?
I don't know on with degree you want to add Security Systems, but im looking forward to see all the sub Systems of the hads.

**Comment by jasontomasi** [comment]
Could the World Portal be made to do a check on whichever serverside Prop Protection addon exists?

**Comment by kennyrkun** [comment]
@jasontomasi what would be the purpose of this?

**Comment by Noname12345GER** [comment]
Wire TargetFinder already has Buddy checks. Maybe take a look there.

**Comment by Cerbinwedd** [comment]
To prevent players from teleporting to you while in a TARDIS, there should be a feature that somehow registers your last position (the TARDIS current position) and places them offset of it. So they'd teleport to you, but would appear just outside the TARDIS

**Comment by parar020100** [comment]
I don't think letting/not letting people in through the portal is a good thing. Too op.
There is a feature - lock, and it should have a purpose, which is exactly security.

There should be shields not allowing others to teleport inside while the doors **are closed**.
However, the point of having the key is to prevent others from opening those doors. 
Doors should be openable when they are not locked.
And there should still be isomophyc controls.

**Comment by parar020100** [comment]
Shields have been suggested in #371 
If they are added, they will forbid teleporting into the TARDIS, but I think that's it:

* isomorphic security system should prevent controls from being used
* if TARDIS unlocked, anyone can open doors
* anyone can enter through opened doors
* only owner can lock/unlock doors
* shields prevent from teleporting inside unless doors are closed

This all seems to work fine.
Maybe we need to stop guests (those who don't have access to the controls with isomorphic) from respawning in the TARDIS,
so that the owner could banish intruders by just killing (would work better than it sounds, lmao)

**Comment by AmyJeanes** [comment]
No longer required, superseded by #371 - with isomorphic controls in place we're pretty much at parity with legacy.
