### ISSUE TITLE
Add support for fixing the gap between interior door and portal

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#603]
Found solution: add a door_mirror part (similarly to the way classic doors work)

Specify interior door coords normally, and the coords for door_mirror with offset from the portal

**Comment by AmyJeanes** [comment]
I'm not sure I agree with this solution, maybe worth digging into the world portals code and see if the gap can be removed there first? This feels hacky

**Comment by parar020100** [comment]
@MattJeanes should this be closed now?

**Comment by AmyJeanes** [comment]
Yep!
