### ISSUE TITLE
Chameleon circuit

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#61]
I'm still unsure about this. But I'll put it here anyway.

**Comment by Noname12345GER** [comment]
Should disable the Doors addon because im not sure about how to see inside then.
I think entering the TARDIS should mimic the legacy then.

**Comment by MattJeanes** [comment]
Yeah it would most likely just be teleport in if I did add this.

**Comment by Noname12345GER** [comment]
Is there any re-consideration about chamelion since some time passed?

**Comment by MattJeanes** [comment]
I'm gonna be mainly porting over the legacy features first then I'll consider any extras

**Comment by Cerbinwedd** [comment]
The circuit should be limited to props of similar shape (4 planes, like the barrel or a box, fridge, etc)

**Comment by MattJeanes** [comment]
I think we actually should do this but a very simple version, not worrying about portals or doors opening. Basically the same as model manipulator but built in a bit more, a predefined list perhaps of props it can turn into (with extension support) which will automatically set the doors to teleport mode and disable the portals.

Should be a relatively easy thing to do and considering everyone asks for this I think it would go down well with the community.

**Comment by parar020100** [comment]
With classic doors being added, we might consider having several different exterior models

**Comment by Artixc** [comment]
Heres my Take on this issue. If you have any questions or concerns dm me at
Artixc#3028
![image](https://user-images.githubusercontent.com/97102223/154743399-adada87b-fda3-4b67-85db-a3f093a639a6.png)
