### ISSUE TITLE
players geting this error

### ISSUE THREAD

**Issue by KyberNetworks** [MattJeanes/TARDIS#622]
[TheTardisGuy63|7|STEAM_0:1:218105959] Lua Error:
[TARDIS] lua/tardis/screens/cl_screen_coordinates.lua:49: bad argument #1 to 'SetText' (string expected, got nil)
1. SetText - [C]:-1
2. updatetextinputs - lua/tardis/screens/cl_screen_coordinates.lua:49
3. unknown - lua/tardis/screens/cl_screen_coordinates.lua:74
4. LoadScreenUI - lua/tardis/sh_screen_ui.lua:479
5. HUDScreen - lua/tardis/sh_screen_ui.lua:269
6. DoClick - lua/tardis/sh_menuoptions.lua:14
7. unknown - lua/vgui/dlabel.lua:237

**Comment by KyberNetworks** [comment]
[TARDIS] lua/entities/gmod_tardis/modules/sh_lock.lua:85: attempt to index field 'metadata' (a nil value)
    1. unknown - lua/entities/gmod_tardis/modules/sh_lock.lua:85
        2. func - lua/entities/gmod_tardis/modules/libraries/sh_message.lua:34
            3. unknown - lua/includes/extensions/net.lua:33

**Comment by parar020100** [comment]
Thanks for reporting!
This is included in #334 and #645, so I'm gonna close this issue
I will try to fix these errors soon
