### ISSUE TITLE
Redecoration fails when attempting to redecorate to a different variant of the same interior

### ISSUE THREAD

**Issue by AmyJeanes** [MattJeanes/TARDIS#632]
Reported by MrPolaroid600 on Steam bug reports:

> Been playing around with the new settings system. It seems that the redecoration function bugs out when you attempt to have it to a different variant of the same interior (for example, changing the roof and exterior settings of the 1963). It doesn't seem to recognise that an interior has been selected for redecoration and therefor changes to a random one.
From my experimenting, it seems to be linked to trying to change settings while keeping the same base interior. For example if I want to keep the 1963 white version but change a couple of its options, it will either randomise to a completely different interior or apply the changes but change to the default 1963 instead of the white version.

**Comment by parar020100** [comment]
Not sure how to process the settings, since some of them don't define the interior version at all

For example, one of the settings is interior doors auto-closing, and you can toggle that setting while being in the interior - it will apply instantly. It is defenetely not a reason to redecorate...

**Comment by parar020100** [comment]
I guess we could make it so that the "select for redecoration" button overrides everything else and even allows to redecorate into itself... That could work

**Comment by parar020100** [comment]
I need to check this one, it might have been fixed already
