### ISSUE TITLE
Community sourced map locations

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#64]
This could be an interesting one. A public database of locations for players to pick and choose from might be a good idea. Sort of like the dupes workshop, but not the dupes workshop because its awful.

**Comment by Noname12345GER** [comment]
I am disagreeing with this. It should take some effort to save coordiantes and stuff.
And the Coordiantes disc should fit in here.

**Comment by MattJeanes** [comment]
Yeah going to bin this one off, would get messy fast and everyone wants something different
