### ISSUE TITLE
errors remain across the game

### ISSUE THREAD

**Issue by SergeantBeckett** [MattJeanes/TARDIS#641]
this has come up in my console, can you help?

[TARDIS]
[TARDIS] Failed to find template mccc_base required for interior tuatcl
1. MergeInteriorTemplates - lua/tardis/interiors/modules/sh_templates.lua:132
2. MergeTemplates - lua/tardis/interiors/modules/sh_templates.lua:155
3. FullReloadInteriors - lua/tardis/sh_interiors.lua:14
4. unknown - lua/tardis/sh_interiors.lua:67
5. include - [C]:-1
6. LoadFolder - lua/autorun/tardis.lua:27
7. unknown - lua/autorun/tardis.lua:38

[TARDIS]
[TARDIS] Failed to find template mccc_controls required for interior tuatcl
1. MergeInteriorTemplates - lua/tardis/interiors/modules/sh_templates.lua:132
2. MergeTemplates - lua/tardis/interiors/modules/sh_templates.lua:155
3. FullReloadInteriors - lua/tardis/sh_interiors.lua:14
4. unknown - lua/tardis/sh_interiors.lua:67
5. include - [C]:-1
6. LoadFolder - lua/autorun/tardis.lua:27
7. unknown - lua/autorun/tardis.lua:38

[TARDIS]
[TARDIS] Failed to find template mccc_base required for interior ruth
1. MergeInteriorTemplates - lua/tardis/interiors/modules/sh_templates.lua:132
2. MergeTemplates - lua/tardis/interiors/modules/sh_templates.lua:155
3. FullReloadInteriors - lua/tardis/sh_interiors.lua:14
4. unknown - lua/tardis/sh_interiors.lua:67
5. include - [C]:-1
6. LoadFolder - lua/autorun/tardis.lua:27
7. unknown - lua/autorun/tardis.lua:38

[TARDIS]
[TARDIS] Failed to find template mccc_controls required for interior ruth
1. MergeInteriorTemplates - lua/tardis/interiors/modules/sh_templates.lua:132
2. MergeTemplates - lua/tardis/interiors/modules/sh_templates.lua:155
3. FullReloadInteriors - lua/tardis/sh_interiors.lua:14
4. unknown - lua/tardis/sh_interiors.lua:67
5. include - [C]:-1
6. LoadFolder - lua/autorun/tardis.lua:27
7. unknown - lua/autorun/tardis.lua:38

[TARDIS]
[TARDIS] Failed to find template mccc_base required for interior tuat
1. MergeInteriorTemplates - lua/tardis/interiors/modules/sh_templates.lua:132
2. MergeTemplates - lua/tardis/interiors/modules/sh_templates.lua:155
3. FullReloadInteriors - lua/tardis/sh_interiors.lua:14
4. unknown - lua/tardis/sh_interiors.lua:67
5. include - [C]:-1
6. LoadFolder - lua/autorun/tardis.lua:27
7. unknown - lua/autorun/tardis.lua:38

[TARDIS]
[TARDIS] Failed to find template mccc_controls required for interior tuat
1. MergeInteriorTemplates - lua/tardis/interiors/modules/sh_templates.lua:132
2. MergeTemplates - lua/tardis/interiors/modules/sh_templates.lua:155
3. FullReloadInteriors - lua/tardis/sh_interiors.lua:14
4. unknown - lua/tardis/sh_interiors.lua:67
5. include - [C]:-1
6. LoadFolder - lua/autorun/tardis.lua:27
7. unknown - lua/autorun/tardis.lua:38

[TARDIS] lua/tardis/interiors/modules/sh_templates.lua:130: attempt to call method 'ChatPrint' (a nil value)
1. MergeInteriorTemplates - lua/tardis/interiors/modules/sh_templates.lua:130
2. MergeTemplates - lua/tardis/interiors/modules/sh_templates.lua:155
3. FullReloadInteriors - lua/tardis/sh_interiors.lua:14
4. unknown - lua/tardis/sh_interiors.lua:67
5. include - [C]:-1
6. LoadFolder - lua/autorun/tardis.lua:23
7. unknown - lua/autorun/tardis.lua:38

[TARDIS] lua/entities/gmod_tardis/modules/sh_redecorate.lua:117: Tried to use a NULL physics object!
1. Sleep - [C]:-1
2. v - lua/entities/gmod_tardis/modules/sh_redecorate.lua:117
3. CallHook - lua/entities/gmod_tardis/shared.lua:54
4. Initialize - lua/entities/gmod_door_exterior/init.lua:75
5. unknown - lua/entities/gmod_tardis/init.lua:38
6. Spawn - [C]:-1
7. SpawnFunction - lua/entities/gmod_door_exterior/init.lua:22
8. SpawnTARDIS - lua/tardis/interiors/modules/sh_spawn_tardis.lua:51
9. Redecorate - lua/entities/gmod_tardis/modules/sh_redecorate.lua:51
10. FinishRepair - lua/entities/gmod_tardis/modules/sh_health.lua:162
11. v - lua/entities/gmod_tardis/modules/sh_health.lua:265
12. CallHook - lua/entities/gmod_tardis/shared.lua:54
13. unknown - lua/entities/gmod_door_exterior/init.lua:91

[TARDIS] Attempted to create invalid part: warmasterstand44
1. SetupParts - lua/tardis/sh_parts.lua:268
2. v - lua/entities/gmod_tardis_interior/modules/sh_parts.lua:5
3. CallHook - lua/entities/gmod_tardis_interior/shared.lua:45
4. Initialize - lua/entities/gmod_door_interior/init.lua:63
5. Initialize - lua/entities/gmod_tardis_interior/init.lua:26
6. v - lua/entities/gmod_door_exterior/modules/sh_interior.lua:73
7. CallHook - lua/entities/gmod_door_exterior/shared.lua:32
8. CallHook - lua/entities/gmod_tardis/shared.lua:48
9. unknown - lua/entities/gmod_door_exterior/init.lua:91

**Comment by parar020100** [comment]
> [TARDIS] Failed to find template mccc_base required for interior tuatcl
You have TUAT installed, but you don't have the MCCC addon (from its dependency)
You should always install all addon dependencies in Steam

> [TARDIS] Attempted to create invalid part: warmasterstand44
This one happens with the War Master's TARDIS addon when you spawn it
Its creators need to be contacted for this to be fixed

I think the others should be fixed once you install MCCC, please tell if they aren't
