### ISSUE TITLE
Black portal doors bug

### ISSUE THREAD

**Issue by TardisGal** [MattJeanes/TARDIS#646]
When I open the doors the portal doesn't load and it's just black and doesn't show anything. I can walk through just fine, just annoying that the whole bigger on the inside effect doesn't work

**Comment by jasontomasi** [comment]
Which maps have you tried this on - does it happen on maps with a sufficiently large sky? (gm_flatgrass, gm_hillscape)

**Comment by TardisGal** [comment]
> Which maps have you tried this on - does it happen on maps with a sufficiently large sky? (gm_flatgrass, gm_hillscape)

I've tried it on gm_construct in flatgrass. and it still does it. I'll test it on some other maps, gm_fork also has the issue

**Comment by TardisGal** [comment]
Just tried on flatgrass, still getting the issue

**Comment by parar020100** [comment]
Hi
Is there a chance you could have the "Portals" setting disabled?

**Comment by parar020100** [comment]
Closing the issue due to inactivity
Please reopen if the problem still happens / needs help
