### ISSUE TITLE
Incompatibility with the Star Trek addons

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#653]
![изображение](https://user-images.githubusercontent.com/32988384/165234623-4a865381-a9e1-418a-882f-8c20b67b1d52.png)
- according to MatthewR1996, this seems to happen when these three addons are installed:

https://steamcommunity.com/sharedfiles/filedetails/?id=2711305622
https://steamcommunity.com/sharedfiles/filedetails/?id=2711309738
https://steamcommunity.com/sharedfiles/filedetails/?id=2711304805

**Comment by AmyJeanes** [comment]
This addon utilises world portals from the Doors addon, the author has been in contact with me a few times about it to help them out and make patches to it. 

If it's shipping it's own version of world portals it could very well be breaking things, I'll have to extract the addons and take a look

**Comment by oninoni** [comment]
On it

**Comment by oninoni** [comment]
Has been Fixed on STM with:
https://github.com/oninoni/startrekmodules/commit/2f9298ed73440372696027dd1860003507bb6264

**Comment by AmyJeanes** [comment]
Looks to be fixed from what I can tell, thanks very much @oninoni appreciate it
