### ISSUE TITLE
Improve exterior light speed (suggestion)

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#661]
From Rose Callisto in Discord:
> `(math.sin(CurTime()3.7)+0.2)(255/4)+(255/2)-70 or 100`
> fixed it, this is the perfect settings for the lamp perfect speed
We experimented a little to get it just right so far that’s the best

Perhaps it should also be synced to the demat/mat sequence?

**Comment by parar020100** [comment]
Initial Discord discussion:

Rose Callisto
> yeah, plus i know i haven't shut up about this and i know its annoying but i'd also love for the lamp sprite to just slow down a little
like theres definitely a speed setting in the files that can be modified but idk where to find it so i can't do it myself, having it the right speed would make it look better

Divided
> this is the calculation for the pulsing animation on the exterior sprite
(math.sin(CurTime()8)+1)(255/4)+(255/2)-50 or 100
lol
idk why it's so complicated
anyway that 8 number is probably what needs tweaking but it's not currently configurable by extensions
its in lua\entities\gmod_tardis\modules\sh_light.lua line 54

Rose Callisto
> is there also gonna be an option or a way to make the actual light light pulse?
also what tardis does this belong to

Divided
> that's just the actual tardis addon
and there could be yeah, i'm not really working on the addon but if artiom wants to add this when he sees this then sure

Rose Callisto
> `(math.sin(CurTime()3.7)+0.2)(255/4)+(255/2)-70 or 100` fixed it, this is the perfect settings for the lamp perfect speed

Divided
> okay neat 👌 it's been a while so I'm assuming the 3.7 is the frequency and the 70 is minimum / maximum brightness that's been changed here
if it works well it could become the new default but also made configurable by extension authors

Rose Callisto
> Noice
Yeah the 3.7 was where the 8 was and the 70 use to be -50 or sumn

Divided
> noice, @Artiom not sure if you wanted to make an issue to track customising the exterior lamp sprite animation for this?

Rose Callisto
> Yeah when you have light stuff active the exterior lamp has a sprite that gives off the effect of it glowing and anytime you take off or are in flight it pulses, me and a friend worked together to make it the right speed instead of crackhead mode that it was for all these years

Artiom
> So wait
Did you actually try changing that in the code?

Rose Callisto
> Yes and it worked what I send here should be updated into the actual code by you if you agree on it cause it’s soooo good

**Comment by AmyJeanes** [comment]
This should be synced to the demat/mat sequence as per #703
