### ISSUE TITLE
Project TARDIS sChinese

### ISSUE THREAD

**Issue by Fox2shadow** [MattJeanes/TARDIS#671]
Hello, I would like to translate your Garry's mod addon "TARDIS" for Chinese people, I will not use it for Commercial. And I will show the origin url and the origin information in the description. so could I reupload and translate it? Please.

My email: bitlex@foxmail.com

**Comment by parar020100** [comment]
Hi

The license (https://github.com/MattJeanes/TARDIS/blob/dev/LICENSE) allows project modifications with preservation of copyright and license notices
However, re-uploading the addon in Steam is a matter to be discussed with @MattJeanes

I must say, however, that having a separate addon version would cause some trouble with syncing the updates and changes. On the other hand, allowing in-built localization in this addon should not be too hard. Perhaps we could work on that one together?

**Comment by AmyJeanes** [comment]
Hi there,

Re-uploading the TARDIS to Steam Workshop is not allowed if it is public. You can have an unlisted / friends only version but in order to prevent conflicts and confusion I request that people do not re-upload it publicly and I will request to Steam Workshop moderators that it be removed if it is left public.

A better suggestion as @parar020100 mentions is adding official translation support to the addon itself, then Chinese users (and users of other languages) can benefit without having to use a separate version of the mod and it will stay up to date when we make updates to the addon.

We are tracking this issue in #499 already but it might be worth doing this now if we have people available and willing to translate to other languages.

**Comment by Fox2shadow** [comment]
I have uploaded my modified version. Can I - keep it in the Steam Workshop?

**Comment by AmyJeanes** [comment]
You may keep it if it is not set to public for example unlisted, friends-only or hidden.

![image](https://user-images.githubusercontent.com/2363642/177989830-de68758c-b27e-4691-a431-6770f29ee9ab.png)

I hope to very soon implement multi language into the addon so then you can simply fill out a translation file which will allow the addon to work in Chinese or other languages. I will let you know as we progress with this I hope to have something ready in the next week.

**Comment by Fox2shadow** [comment]
Thanks, I've setting it  friends-only, and I'm expect to supporting multiple languages. :)

**Comment by AmyJeanes** [comment]
Thank you very much, multiple languages sounds great!

**Comment by AmyJeanes** [comment]
Hey, I've started working on this now and the translation feature is in but we still need some time to add all of the existing text into the new translation system

If you look here you can see a sample of the English (default) language file - you can simply create another file here with your preferred language and override the ones you want and the rest will fall back to the English file: https://github.com/MattJeanes/TARDIS/blob/dev/lua/tardis/languages/en.lua

I'll let you know when we've finished adding everything and it's ready to be used.

**Comment by Fox2shadow** [comment]
I'll follow up on the translation. Love you guys

**Comment by Fox2shadow** [comment]
@MattJeanes 

I have finished translating, should I push it to the dev branch?

And I want to test it on game.

**Comment by AmyJeanes** [comment]
You can fork this repository and drop this addon into your addons folder to test locally on your gmod. You can raise a pull request from your fork to this repository and then it will be included with the addon for everyone

Note that there are a lot more language strings to be added these are only the first few

**Comment by Fox2shadow** [comment]
I packaged it as a gma file and put it in the addons folder, but Gmod doesn't load it.

But the previous version didn't have any problems.

**Comment by AmyJeanes** [comment]
Okay so you can download the addon from GitHub as a ZIP file and extract it into your GMod addons folder - make sure you disable/uninstall the workshop version for this to work properly

**Comment by AmyJeanes** [comment]
Hey @ALexZekio I have completed the translation of the TARDIS addon now and all strings are now available if you wish to finish the translations 😄 

https://github.com/MattJeanes/TARDIS/blob/dev/lua/tardis/languages/en.lua

Note this is not yet in live workshop as some of the language code needs work but all the strings are ready for translation to other languages now!

**Comment by parar020100** [comment]
@MattJeanes @ALexZekio can this be closed?

**Comment by AmyJeanes** [comment]
I will close this when it is released to workshop but yes the work is pretty much don

**Comment by AmyJeanes** [comment]
Changed my mind - Translation files are in so closing
