### ISSUE TITLE
I want to make game saves, but when I load them I just get lua errors.. 

### ISSUE THREAD

**Issue by Garth1002** [MattJeanes/TARDIS#676]
Those are the errors & when I load up said game save the tardis is also gone & again I just a load of them lua errors, I cut back on some add-ons thinking that was the case but nope... I really just have no clue what these errors mean & any research on these errors well I just don't know enough to even know what I'm properly searching for... Any help would be appreciated
![Garry's Mod Screenshot 2022 07 30 - 10 23 18 49](https://user-images.githubusercontent.com/110284180/181904561-9a35a0e1-91b2-40dd-ac87-5e9aa97aaaa3.png)

**Comment by AmyJeanes** [comment]
Hi thank you for this report, we are already tracking this under #542 so I will close this issue
