### ISSUE TITLE
Mix and match exteriors and interiors

### ISSUE THREAD

**Issue by AmyJeanes** [MattJeanes/TARDIS#700]
This suggestion comes from FuzzyLeo#8109 on Discord

With the addition of the classic doors feature where the outside view can show the exterior doors but the inside view showing completely different doors, the ability to mix and match exteriors and interiors becomes much more viable as we don't need to worry about stuff lining up as much.

This should be a setting to override the exterior of any TARDIS to any exterior but it will come with a disclaimer / warning saying that this may result in unexpected behaviour or glitches. Under the hood it will use the same tech as the classic doors feature to fuse the two together.

Some example images:
![image](https://user-images.githubusercontent.com/2363642/187288859-8bcf0681-7992-4084-b1fe-671a9e1125bd.png)
![image](https://user-images.githubusercontent.com/2363642/187288871-db57b93a-a2f2-47e7-83e8-a2d402e9279e.png)

**Comment by FuzzyLeo** [comment]
it may be good to have a checkbox as part of the feature called "override interior doors" where it would replace the interior doors of the tardis like the image above, if the box is unchecked it would use the classic doors approach where the interior doors would be separate and while inside it would use the default doors for that interior

i believe this would benefit it as (again like the image above shows) there are interiors that would actually look better using the appropriate interior doors as the dimensions are very similar, but there are also interiors that wouldn't look as good with that approach (for example a classic exterior with a new series interior) so having the best of both worlds is a good option imo

overally i feel like the more options the better as while you can't account for every extension, you can allow the user to change it themselves, therefore eliminating the issue altogether

**Comment by FuzzyLeo** [comment]
heres some visual examples of what i mean

heres where classic style doors would benefit
![image](https://user-images.githubusercontent.com/23579757/187297192-40fe20cf-b8a0-4865-85e2-e7b8001ee085.png)


and heres an example of where the interior doors being changed would actually improve its appearance as it would be more consistent with the exterior
![image](https://user-images.githubusercontent.com/23579757/187296977-2ae0b2e3-b94b-4f7f-8a5a-f835fa5c0023.png)

**Comment by parar020100** [comment]
Is this different from #61  ?

**Comment by FuzzyLeo** [comment]
this was one potential way of doing it by utilising the classic doors, its more detailed than the ones mentioned in that issue

**Comment by parar020100** [comment]
@FuzzyLeo @MattJeanes I presume with chameleon this one can be closed, can't it?

**Comment by AmyJeanes** [comment]
Agree
