### ISSUE TITLE
Interior settings in the spawnmenu don't appear to persist after game reload

### ISSUE THREAD

**Issue by AmyJeanes** [MattJeanes/TARDIS#701]
As reported by @Cem111333, LexBex and others there appears to be an issue where changing the interior settings or adding them to favourites no longer appears to consistently save properly and work once the game is reloaded

https://user-images.githubusercontent.com/2363642/187290007-4e73529e-7052-4c6e-a785-bb451f86a473.mp4

**Comment by AmyJeanes** [comment]
I'm unable to reproduce this problem, settings save fine and work after game reload/restart

**Comment by AmyJeanes** [comment]
Unable to replicate, closing until someone can give me a repro

**Comment by CrimsonThunder02** [comment]
The settings not saving is happening to me too recently now
