### ISSUE TITLE
Change E2 Functions to return Vector/Angle userdata

### ISSUE THREAD

**Issue by vurvdev** [MattJeanes/TARDIS#706]
This is an issue to warn that any functions that return the ``vector`` or ``angle`` E2 type will be broken if they aren't converted from returning lua tables of three numbers, for example ``{0, 0, 0}`` to instead returning the glua userdata ``Vector(0, 0, 0)`` or ``Angle(0, 0, 0)``.

This is part of an effort to ensure the amount of extensions broken by wiremod/wire#2399 is minimal.

Scanning your repo, [I only see one potential instance](https://github.com/MattJeanes/TARDIS/blob/75ce25c82e622f8b3efae4c1de5b43c334c97f15/lua/entities/gmod_tardis/modules/teleport/sv_tp_wiremod_e2.lua#L62), but I'm posting this just in case since you would likely know where to look as the maintainer.

**Comment by AmyJeanes** [comment]
Thank you for the heads up! Can we make this change now or do we have to wait for wiremod to update?

**Comment by AmyJeanes** [comment]
I agree with your search I can only see that one instance also and have fixed it in https://github.com/MattJeanes/TARDIS/commit/e1d80d1ed198bccdc96ef62ec7f4b6a1e1f68978
