### ISSUE TITLE
Error: demat-pos ends up being a table instead of a vector

### ISSUE THREAD

**Issue by Blazer100** [MattJeanes/TARDIS#708]
[TARDIS] lua/entities/gmod_tardis/modules/teleport/sh_tp_main.lua:126: bad argument #1 to 'WriteVector' (Vector expected, got table)
  1. WriteVector - [C]:-1
   2. func - lua/entities/gmod_tardis/modules/teleport/sh_tp_main.lua:126
    3. SendMessage - lua/entities/gmod_tardis/modules/libraries/sh_message.lua:12
     4. Demat - lua/entities/gmod_tardis/modules/teleport/sh_tp_main.lua:126
      5. ext_func - lua/tardis/controls/sh_control_teleport.lua:14
       6. Control - lua/tardis/sh_control.lua:44
        7. unknown - lua/tardis/sh_parts.lua:86

**Comment by parar020100** [comment]
Seems to be this line: 
```lua
            self:SendMessage("premat",function() net.WriteVector(self:GetData("demat-pos",Vector())) end)
```

Needs checking
