### ISSUE TITLE
Only light windows when power is enabled

### ISSUE THREAD

**Issue by MattJeanes** [MattJeanes/TARDIS#72]
No idea how possible this is, but we'll see about it.

**Comment by Jimmycuhula** [comment]
You could have it so the Tardis would fade between 2 different textures. 1 with lit up windows and another with darkened windows.

**Comment by MattJeanes** [comment]
I can't think of any ways of fading between textures.

**Comment by Jimmycuhula** [comment]
Yeah the fading part sounds difficult. Maybe it would just switch between them, almost like someone switching the skins but on an automated system.

**Comment by MattJeanes** [comment]
Yeah instant is possible.

**Comment by UnheardPi** [comment]
I really like this idea. It makes the TARDIS feel more close to the show / intended immersion.

**Comment by Noname12345GER** [comment]
I like this idea.

**Comment by Noname12345GER** [comment]
if you wanted to improve the power off on the legacy, try applying Color(84,84,84) on the interior

**Comment by MattJeanes** [comment]
This can be done on an extension by extension basis by hooking onto the power calls and changing skins on the exterior, it's not something I plan to add to the native addon so will close this for that reason
