### ISSUE TITLE
Angles Problems

### ISSUE THREAD

**Issue by Matspyder51** [MattJeanes/TARDIS#75]
When the tardis was incline, we had problem to go inside and outside, if I go inside, my player was teleport in a tardis wall door, and if I go outside, it was block me in tardis wall too.

Sorry for my English

**Comment by MattJeanes** [comment]
This is caused by the player collision box being square, and there isn't much I can do apart from increase the size of the exterior - which I can't really do.

See my [Facepunch post](http://facepunch.com/showthread.php?t=1300340&p=47487523&viewfull=1#post47487523) about this for more details.

**Comment by Matspyder51** [comment]
Why don't change code of portals, test if the Tardis have an Angle of 90° or -90° and teleport player ?
