### ISSUE TITLE
Unable to merge branches

### ISSUE THREAD

**Issue by Fox2shadow** [MattJeanes/TARDIS#756]
I fixed some errors in the Simplified Chinese translation.
But there an error occurred when I committed the merge branch.

![image](https://user-images.githubusercontent.com/54586683/208029830-3bb1549b-e6fd-4316-b669-8450b4e6eaf7.png)

What causes this? Also, I tried executing this script locally, but it didn't work.

Please help me? :)

**Comment by AmyJeanes** [comment]
Translation files should be updated through CrowdIn to avoid this issue but I think that it's broken as it's not expecting PRs from outside the repo to be updating those files 🙂
