### ISSUE TITLE
Lights are broken in multiplayer sessions

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#760]
Reported by @CrethFox 

![image](https://user-images.githubusercontent.com/32988384/208844380-57fc67b1-b74f-4fd1-a8d4-f2718b5f2c10.png)
![image](https://user-images.githubusercontent.com/32988384/208844402-45fee942-7cbf-4953-94ac-94cbc1f43361.png)
![image](https://user-images.githubusercontent.com/32988384/208844422-55be5af1-c245-4938-bef2-cd79a004421e.png)

**Comment by AmyJeanes** [comment]
Fixed in above commit @parar020100, close this if you are happy with the fix
