### ISSUE TITLE
Multiple Tardis Bug

### ISSUE THREAD

**Issue by Matspyder51** [MattJeanes/TARDIS#77]
In singlePlayer, when I spawn a Tardis, I open the doors and spawn a second Tardis and open the doors of the second, I show the door emplacement of the first Tardis

**Comment by MattJeanes** [comment]
I don't understand, picture?

**Comment by Matspyder51** [comment]
I redownload it and take a screen.
So, It's possible for modify your code to create big personnal Builds rooms ?

**Comment by Matspyder51** [comment]
I can't reproduce this bug, I don't know why, but I have found an other bug, In Flatgrass, when I spawn a Tardis inside an other Tardis and go inside, The tardis was teleport on the top of the map and I have a strange bug
![Image](http://image.noelshack.com/fichiers/2015/18/1430161317-tardis.png)

**Comment by MattJeanes** [comment]
This is known.
