### ISSUE TITLE
The mod is causing errors (this is what shows up)

### ISSUE THREAD

**Issue by ghost** [MattJeanes/TARDIS#779]
[TARDIS] lua/tardis/sh_screen_ui.lua:501: bad argument #1 to 'SetText' (string expected, got nil)
    1. SetText - [C]:-1
        2. func - lua/tardis/sh_screen_ui.lua:501
            3. LoadButtons - lua/tardis/sh_screen_ui.lua:668
                4. LoadScreenUI - lua/tardis/sh_screen_ui.lua:497
                    5. LoadScreen - lua/tardis/sh_screen_ui.lua:760
                        6. LoadScreens - lua/entities/gmod_tardis_interior/modules/sh_interior_screens.lua:75
                            7. v - lua/entities/gmod_tardis_interior/modules/sh_interior_screens.lua:90
                                8. CallHook - lua/entities/gmod_tardis_interior/shared.lua:49
                                    9. func - lua/entities/gmod_door_exterior/cl_init.lua:38
                                        10. unknown - lua/includes/extensions/net.lua:33

**Comment by ghost** [comment]
Its something to do with the TARDIS UI thing on the screens

**Comment by parar020100** [comment]
Hi
You probably have the old UI enabled in the settings
It is currently broken (it should get fixed soon), for now you just need to disable the setting
