### ISSUE TITLE
Not installing Doors prevents the player from opening the spawnmenu

### ISSUE THREAD

**Issue by NovaAstral** [MattJeanes/TARDIS#913]
As the title says, if one does not have the Doors addon enabled it will entirely prevent the player from opening the spawn menu

**Comment by DJNEFFYFRESH** [comment]
its your sign to install doors

**Comment by AmyJeanes** [comment]
Fixed by https://github.com/MattJeanes/TARDIS/commit/8864751819d401122848776cb57c58d0b99159f8
