### ISSUE TITLE
Portals breaking when close to LSCS lightsaber mod 'force entities'

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#930]
I am not sure which addon causes the issue, since the behaviour is rather weird
This needs looking into, although my guess is that LSCS force entities are using some sort of rendering code that breaks the TARDIS portals

For some reason whether the portals break or not depend on the location
They do break next to where the force entity was spawned, however, a TARDIS can spawn with normal portals far away.
It doesn't matter whether the entity exists or not - the portals break IF the entity has been spawned on the map. Map cleanup doesn't help. 

Here's the video / demonstration:
https://youtu.be/tmLLJOrwnFg

**Comment by parar020100** [comment]
Seems like this is the force entity code

https://github.com/Blu-x92/lscs_public/blob/28768cf14fcf56bd75acfb2d39457fc2465c8074/lua/entities/lscs_force_base.lua#L38

**Comment by parar020100** [comment]
https://github.com/Blu-x92/lscs_public/issues/18

**Comment by AmyJeanes** [comment]
https://github.com/Blu-x92/lscs_public/issues/19

**Comment by parar020100** [comment]
Resolved
