### ISSUE TITLE
Move door bodygroup related code to default addon's hooks

### ISSUE THREAD

**Issue by parar020100** [MattJeanes/TARDIS#957]
Complaint from VT:

![Image](https://github.com/MattJeanes/TARDIS/assets/32988384/b1d02a76-842d-4fed-8411-7b6564e7174c)

This code is creating some issues with the models from other extensions
Should be legacy only

**Comment by parar020100** [comment]
@MattJeanes it's safe to remove this, isn't it?

**Comment by AmyJeanes** [comment]
I expect so yeah unless you know of any extensions making use of it
