### ISSUE TITLE
Script error when pressing demat while already going into the vortex in third person

### ISSUE THREAD

**Issue by CrimsonThunder02** [MattJeanes/TARDIS#977]
This is specifically with both  the beta and alpha versions-I tried doing this with the workshop version to see and i found that when ever i did this it kept draining artron every time you click demat so maybe that has something to do with it, i've recorded a vid of it below.

https://github.com/MattJeanes/TARDIS/assets/126357241/ff10a8b1-3132-48a3-be5a-29c07cd4c2c3

**Comment by CrimsonThunder02** [comment]
![Screenshot_20231107-214630~2](https://github.com/MattJeanes/TARDIS/assets/126357241/26125c06-eb74-4e93-b2c7-ce5e91150e1c)

**Comment by AmyJeanes** [comment]
Thanks, fixed
